# 2to3-2
# Autogenerated from man page /usr/share/man/man1/2to3-2.7.1.gz
complete -c 2to3-2 -s h -l help -d 'show this help message and exit'
complete -c 2to3-2 -s d -l doctests_only -d 'Fix up doctests only'
complete -c 2to3-2 -s f -l fix -d 'Each FIX specifies a transformation; default: all'
complete -c 2to3-2 -s j -l processes -d 'Run 2to3 concurrently'
complete -c 2to3-2 -s x -l nofix -d 'Prevent a transformation from being run'
complete -c 2to3-2 -s l -l list-fixes -d 'List available transformations'
complete -c 2to3-2 -s p -l print-function -d 'Modify the grammar so that print() is a function'
complete -c 2to3-2 -s v -l verbose -d 'More verbose logging'
complete -c 2to3-2 -l no-diffs -d 'Don\'t show diffs of the refactoring'
complete -c 2to3-2 -s w -l write -d 'Write back modified files'
complete -c 2to3-2 -s n -l nobackups -d 'Don\'t write backups for modified files'

