# aa-status
# Autogenerated from man page /usr/share/man/man8/aa-status.8.gz
complete -c aa-status -l enabled -d 'returns error code if AppArmor is not enabled'
complete -c aa-status -l profiled -d 'displays the number of loaded AppArmor policies'
complete -c aa-status -l enforced -d 'displays the number of loaded enforcing AppArmor policies'
complete -c aa-status -l complaining -d 'displays the number of loaded non-enforcing AppArmor policies'
complete -c aa-status -l verbose -d 'displays multiple data points about loaded AppArmor policy set (the default a…'
complete -c aa-status -l json -d 'displays multiple data points about loaded AppArmor policy set in a \\s-1JSON\\…'
complete -c aa-status -l pretty-json -d 'same as --json, formatted to be readable by humans as well as by machines'

