# add-apt-repository
# Autogenerated from man page /usr/share/man/man1/add-apt-repository.1.gz
complete -c add-apt-repository -s h -l help -d 'Show help message and exit'
complete -c add-apt-repository -s m -l massive-debug -d 'Print a lot of debug information to the command line'
complete -c add-apt-repository -s r -l remove -d 'Remove the specified repository'
complete -c add-apt-repository -s y -l yes -d 'Assume yes to all queries'
complete -c add-apt-repository -s u -l update -d 'After adding the repository, update the package cache with packages from this…'
complete -c add-apt-repository -s k -l keyserver -d 'Use a custom keyserver URL instead of the default'
complete -c add-apt-repository -s s -l enable-source -d 'Allow downloading of the source packages from the repository REPOSITORY STRIN…'

