# bccmd
# Autogenerated from man page /usr/share/man/man1/bccmd.1.gz
complete -c bccmd -o 't<transport>' -d 'Specify the communication transport.  Valid options are: . RS'
complete -c bccmd -s t -d 'Specify the communication transport'
complete -c bccmd -s d -d 'Specify a particular device to operate on'
complete -c bccmd -s r

