# brasero
# Autogenerated from man page /usr/share/man/man1/brasero.1.gz
complete -c brasero -s p -l project -d 'Open the specified project'
complete -c brasero -s a -l audio -d 'Open an empty audio project'
complete -c brasero -s d -l data -d 'Open an empty data project'
complete -c brasero -s c -l copy -d 'Copy a disc'
complete -c brasero -s j -l cover -d 'Cover to use'
complete -c brasero -s o -l video -d 'Open a video project adding the URIs given on the command line'
complete -c brasero -s i -l image -d 'Uri of an image file or a cue file to be burnt (autodetected)'
complete -c brasero -s e -l empty -d 'Force brasero to display the project selection page'
complete -c brasero -s b -l blank -d 'Open the blank disc dialog'
complete -c brasero -s k -l check -d 'Open the check disc dialog'
complete -c brasero -s n -l ncb -d 'Open a data project with the contents of burn:/// URI'
complete -c brasero -s r -l burn-and-remove-project -d 'Burn the specified project and REMOVE it'
complete -c brasero -l display -d 'X display to use'
complete -c brasero -s '?' -l help -d 'Show summary of options'

