# btattach
# Autogenerated from man page /usr/share/man/man1/btattach.1.gz
complete -c btattach -s B -l bredr -d 'Attach a BR/EDR controller'
complete -c btattach -s A -l amp -d 'Attach an AMP controller'
complete -c btattach -s P -l protocol -d 'Specify the protocol type for talking to the device.  Supported values are: '
complete -c btattach -s R -d 'Set the device into raw mode (the kernel and bluetoothd will ignore it)'

