# bundle-outdated2
# Autogenerated from man page /usr/share/man/man1/bundle-outdated2.7.1.gz
complete -c bundle-outdated2 -l local -d 'Do not attempt to fetch gems remotely and use the gem cache instead'
complete -c bundle-outdated2 -l pre -d 'Check for newer pre-release gems'
complete -c bundle-outdated2 -l source -d 'Check against a specific source'
complete -c bundle-outdated2 -l strict -d 'Only list newer versions allowed by your Gemfile requirements'
complete -c bundle-outdated2 -l parseable -l porcelain -d 'Use minimal formatting for more parseable output'
complete -c bundle-outdated2 -l group -d 'List gems from a specific group'
complete -c bundle-outdated2 -l groups -d 'List gems organized by groups'
complete -c bundle-outdated2 -l update-strict -d 'Strict conservative resolution, do not allow any gem to be updated past lates…'
complete -c bundle-outdated2 -l minor -d 'Prefer updating only to next minor version'
complete -c bundle-outdated2 -l major -d 'Prefer updating to next major version (default)'
complete -c bundle-outdated2 -l patch -d 'Prefer updating only to next patch version'
complete -c bundle-outdated2 -l filter-major -d 'Only list major newer versions'
complete -c bundle-outdated2 -l filter-minor -d 'Only list minor newer versions'
complete -c bundle-outdated2 -l filter-patch -d 'Only list patch newer versions'

