# bundle-add2
# Autogenerated from man page /usr/share/man/man1/bundle-add2.7.1.gz
complete -c bundle-add2 -l version -s v -d 'Specify version requirements(s) for the added gem'
complete -c bundle-add2 -l group -s g -d 'Specify the group(s) for the added gem'
complete -c bundle-add2 -l source -s s -d 'Specify the source for the added gem'
complete -c bundle-add2 -l git -d 'Specify the git source for the added gem'
complete -c bundle-add2 -l branch -d 'Specify the git branch for the added gem'
complete -c bundle-add2 -l skip-install -d 'Adds the gem to the Gemfile but does not install it'
complete -c bundle-add2 -l optimistic -d 'Adds optimistic declaration of version '

