# cdxa2mpeg
# Autogenerated from man page /usr/share/man/man1/cdxa2mpeg.1.gz
complete -c cdxa2mpeg -s v -l verbose -d 'be verbose'
complete -c cdxa2mpeg -s q -l quiet -d 'show only critical messages'
complete -c cdxa2mpeg -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c cdxa2mpeg -s '?' -l help -d 'Show this help message'
complete -c cdxa2mpeg -l usage -d 'Display brief usage message AUTHOR Written by Herbert Valerio Riedel and Rock…'

