# chmem
# Autogenerated from man page /usr/share/man/man8/chmem.8.gz
complete -c chmem -s b -l blocks -d 'Use a BLOCKRANGE parameter instead of RANGE or SIZE for the --enable and --di…'
complete -c chmem -s d -l disable -d 'Set the specified RANGE, SIZE, or BLOCKRANGE of memory offline'
complete -c chmem -s e -l enable -d 'Set the specified RANGE, SIZE, or BLOCKRANGE of memory online'
complete -c chmem -s z -l zone -d 'Select the memory ZONE where to set the specified RANGE, SIZE, or BLOCKRANGE …'
complete -c chmem -s h -l help -d 'Print a short help text, then exit'
complete -c chmem -s v -l verbose -d 'Verbose mode.  Causes chmem to print debugging messages about it\'s progress'
complete -c chmem -s V -l version -d 'Print the version number, then exit'

