# choom
# Autogenerated from man page /usr/share/man/man1/choom.1.gz
complete -c choom -s p -l pid -d 'Specifies process ID'
complete -c choom -s n -l adjust -d 'Specify the adjust score value'
complete -c choom -s h -l help -d 'Display help text and exit'
complete -c choom -s V -l version -d 'Display version information and exit'

