# dbxtool
# Autogenerated from man page /usr/share/man/man1/dbxtool.1.gz
complete -c dbxtool -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c dbxtool -s v -l verbose -d 'Show extra debugging information'
complete -c dbxtool -l version -d 'Show the calculated version of the dbx'
complete -c dbxtool -s l -l list -d 'List entries in dbx'
complete -c dbxtool -s a -l apply -d 'Apply update files'
complete -c dbxtool -s d -l dbx -d 'Specify the dbx database file'
complete -c dbxtool -s f -l force -d 'Apply update even when not advised'

