# dig
# Autogenerated from man page /usr/share/man/man1/dig.1.gz
complete -c dig -s 4 -d 'Use IPv4 only'
complete -c dig -s 6 -d 'Use IPv6 only'
complete -c dig -s b -d 'Set the source IP address of the query'
complete -c dig -s c -d 'Set the query class'
complete -c dig -s f -d 'Batch mode: dig reads a list of lookup requests to process from the given file'
complete -c dig -s k -d 'Sign queries using TSIG using a key read from the given file'
complete -c dig -s m -d 'Enable memory usage debugging'
complete -c dig -s p -d 'Send the query to a non-standard port on the server, instead of the default p…'
complete -c dig -s q -d 'The domain name to query'
complete -c dig -s r -d 'Do not read options from ${HOME}/. digrc'
complete -c dig -s t -d 'The resource record type to query.  It can be any valid query type'
complete -c dig -s u -d 'Print query times in microseconds instead of milliseconds'
complete -c dig -s v -d 'Print the version number and exit'
complete -c dig -s x -d 'Simplified reverse lookups, for mapping addresses to names'
complete -c dig -s y -d 'Sign queries using TSIG with the given authentication key'
complete -c dig -s h -d 'option is given'

