# dpkg-buildpackage
# Autogenerated from man page /usr/share/man/man1/dpkg-buildpackage.1.gz
complete -c dpkg-buildpackage -l build -d 'Specifies the build type from a comma-separated list of components (since dpk…'
complete -c dpkg-buildpackage -s g -d 'Equivalent to --build=source,all (since dpkg 1. 17. 11)'
complete -c dpkg-buildpackage -s G -d 'Equivalent to --build=source,any (since dpkg 1. 17. 11)'
complete -c dpkg-buildpackage -s b -d 'Equivalent to --build=binary or --build=any,all'
complete -c dpkg-buildpackage -s B -d 'Equivalent to --build=any'
complete -c dpkg-buildpackage -s A -d 'Equivalent to --build=all'
complete -c dpkg-buildpackage -s S -d 'Equivalent to --build=source'
complete -c dpkg-buildpackage -s F -d 'Equivalent to --build=full, --build=source,binary or --build=source,any,all (…'
complete -c dpkg-buildpackage -l target -d 'TQ  "--target " target[,. ] . TQ  -T ", " --rules-target= target[,'
complete -c dpkg-buildpackage -l as-root -d 'Only meaningful together with --target (since dpkg 1. 15. 0)'
complete -c dpkg-buildpackage -o si -d 'TQ  -sa . TQ  -sd . TQ  -v version . TQ  -C changes-description '
complete -c dpkg-buildpackage -s a -l host-arch -d 'Specify the Debian architecture we build for (long option since dpkg 1. 17'
complete -c dpkg-buildpackage -s t -l host-type -d 'Specify the GNU system type we build for (long option since dpkg 1. 17. 17)'
complete -c dpkg-buildpackage -l target-arch -d 'Specify the Debian architecture the binaries built will build for (since dpkg…'
complete -c dpkg-buildpackage -l target-type -d 'Specify the GNU system type the binaries built will build for (since dpkg 1'
complete -c dpkg-buildpackage -s P -l build-profiles -d 'Specify the profile(s) we build, as a comma-separated list (since dpkg 1. 17'
complete -c dpkg-buildpackage -s j -l jobs -d 'Number of jobs allowed to be run simultaneously, number of jobs matching the …'
complete -c dpkg-buildpackage -s J -l jobs-try -d 'This option (since dpkg 1. 18. 2, long option since dpkg 1. 18'
complete -c dpkg-buildpackage -s D -l check-builddeps -d 'Check build dependencies and conflicts; abort if unsatisfied (long option sin…'
complete -c dpkg-buildpackage -s d -l no-check-builddeps -d 'Do not check build dependencies and conflicts (long option since dpkg 1. 18'
complete -c dpkg-buildpackage -l ignore-builtin-builddeps -d 'Do not check built-in build dependencies and conflicts (since dpkg 1. 18. 2)'
complete -c dpkg-buildpackage -l rules-requires-root -d 'Do not honor the Rules-Requires-Root field, falling back to its legacy defaul…'
complete -c dpkg-buildpackage -o nc -l no-pre-clean -d 'Do not clean the source tree before building (long option since dpkg 1. 18'
complete -c dpkg-buildpackage -l pre-clean -d 'Clean the source tree before building (since dpkg 1. 18. 8)'
complete -c dpkg-buildpackage -o tc -l post-clean -d 'Clean the source tree (using  gain-root-command  "debian/rules clean" ) after…'
complete -c dpkg-buildpackage -l no-post-clean -d 'Do not clean the source tree after the package has been built (since dpkg 1'
complete -c dpkg-buildpackage -s r -l root-command -d 'When  dpkg-buildpackage needs to execute part of the build process as root, i…'
complete -c dpkg-buildpackage -s R -l rules-file -d 'Building a Debian package usually involves invoking  debian/rules as a comman…'
complete -c dpkg-buildpackage -l check-command -d 'Command used to check the '
complete -c dpkg-buildpackage -l check-option -d 'Pass option opt to the check-command specified with DEB_CHECK_COMMAND or --ch…'
complete -c dpkg-buildpackage -l hook- -d 'Set the specified shell code hook-command as the hook hook-name, which will r…'
complete -c dpkg-buildpackage -l buildinfo-option -d 'Pass option opt to dpkg-genbuildinfo (since dpkg 1. 18. 11)'
complete -c dpkg-buildpackage -s p -l sign-command -d 'When dpkg-buildpackage needs to execute GPG to sign a source control ('
complete -c dpkg-buildpackage -s k -l sign-key -d 'Specify a key-ID to use when signing packages (long option since dpkg 1. 18'
complete -c dpkg-buildpackage -o us -l unsigned-source -d 'Do not sign the source package (long option since dpkg 1. 18. 8)'
complete -c dpkg-buildpackage -o ui -l unsigned-buildinfo -d 'Do not sign the . buildinfo file (since dpkg 1. 18. 19)'
complete -c dpkg-buildpackage -o uc -l unsigned-changes -d 'Do not sign the . buildinfo and . changes files (long option since dpkg 1. 18'
complete -c dpkg-buildpackage -l no-sign -d 'Do not sign any file, this includes the source package, the '
complete -c dpkg-buildpackage -l force-sign -d 'Force the signing of the resulting files (since dpkg 1. 17'
complete -c dpkg-buildpackage -o sn -d 'TQ  -ss . TQ  -sA . TQ  -sk . TQ  -su . TQ  -sr . TQ  -sK . TQ  -sU '
complete -c dpkg-buildpackage -l source-option -d 'Pass option opt to dpkg-source (since dpkg 1. 15. 6)'
complete -c dpkg-buildpackage -l changes-option -d 'Pass option opt to dpkg-genchanges (since dpkg 1. 15. 6)'
complete -c dpkg-buildpackage -l admindir -d 'TQ  "--admindir " dir Change the location of the dpkg database (since dpkg 1'
complete -c dpkg-buildpackage -s '?' -l help -d 'Show the usage message and exit'
complete -c dpkg-buildpackage -s T -l rules-target -d 'Calls debian/rules target once per target specified, after having setup the b…'
complete -c dpkg-buildpackage -o sa
complete -c dpkg-buildpackage -o sd
complete -c dpkg-buildpackage -s v
complete -c dpkg-buildpackage -s C
complete -c dpkg-buildpackage -s m -l release-by
complete -c dpkg-buildpackage -s e -l build-by -d 'Passed unchanged to dpkg-genchanges.  See its manual page'
complete -c dpkg-buildpackage -s c -d 'instead of passing arguments individually to the command to be run'
complete -c dpkg-buildpackage -o ss
complete -c dpkg-buildpackage -o sA
complete -c dpkg-buildpackage -o sk
complete -c dpkg-buildpackage -o su
complete -c dpkg-buildpackage -o sr
complete -c dpkg-buildpackage -o sK
complete -c dpkg-buildpackage -o sU
complete -c dpkg-buildpackage -o sR
complete -c dpkg-buildpackage -s i -l diff-ignore
complete -c dpkg-buildpackage -s I -l tar-ignore
complete -c dpkg-buildpackage -s z -l compression-level
complete -c dpkg-buildpackage -s Z -l compression -d 'Passed unchanged to dpkg-source.  See its manual page'
complete -c dpkg-buildpackage -l version -d 'Show the version and exit'

