# dpkg-scanpackages
# Autogenerated from man page /usr/share/man/man1/dpkg-scanpackages.1.gz
complete -c dpkg-scanpackages -s t -l type -d 'Scan for *. type packages, instead of *. deb'
complete -c dpkg-scanpackages -s e -l extra-override -d 'Scan file to find supplementary overrides (the file can be compressed since d…'
complete -c dpkg-scanpackages -s a -l arch -d 'Use a pattern consisting of *_all. deb and *_arch'
complete -c dpkg-scanpackages -s h -l hash -d 'Only generate file hashes for the comma-specified list specified (since dpkg 1'
complete -c dpkg-scanpackages -s m -l multiversion -d 'Include all found packages in the output'
complete -c dpkg-scanpackages -s M -l medium -d 'Add an X-Medium field containing the value id-string (since dpkg 1. 15. 5)'
complete -c dpkg-scanpackages -s '?' -l help -d 'Show the usage message and exit'
complete -c dpkg-scanpackages -l version -d 'Show the version and exit'

