# dpkg-distaddfile
# Autogenerated from man page /usr/share/man/man1/dpkg-distaddfile.1.gz
complete -c dpkg-distaddfile -s f -d 'Read or write the list of files to be uploaded here, rather than using  debia…'
complete -c dpkg-distaddfile -s '?' -l help -d 'Show the usage message and exit'
complete -c dpkg-distaddfile -l version -d 'Show the version and exit'

