# dpkg-buildflags
# Autogenerated from man page /usr/share/man/man1/dpkg-buildflags.1.gz
complete -c dpkg-buildflags -l dump -d 'Print to standard output all compilation flags and their values'
complete -c dpkg-buildflags -l list -d 'Print the list of flags supported by the current vendor (one per line)'
complete -c dpkg-buildflags -l status -d 'Display any information that can be useful to explain the behaviour of dpkg-b…'
complete -c dpkg-buildflags -l export -d 'Print to standard output commands that can be used to export all the compilat…'
complete -c dpkg-buildflags -l get -d 'Print the value of the flag on standard output'
complete -c dpkg-buildflags -l origin -d 'Print the origin of the value that is returned by --get'
complete -c dpkg-buildflags -l query -d 'Print any information that can be useful to explain the behaviour of the prog…'
complete -c dpkg-buildflags -l query-features -d 'Print the features enabled for a given area (since dpkg 1. 16. 2)'
complete -c dpkg-buildflags -l help -d 'Show the usage message and exit'
complete -c dpkg-buildflags -l version -d 'Show the version and exit'
complete -c dpkg-buildflags -o Wl -d 'and , have to be stripped from these options).  Default value: empty'
complete -c dpkg-buildflags -o D_LARGEFILE_SOURCE -o D_FILE_OFFSET_BITS
complete -c dpkg-buildflags -o Werror
complete -c dpkg-buildflags -o Wformat -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS and OBJCXXFLAGS'
complete -c dpkg-buildflags -o D_FORTIFY_SOURCE -d 'to CPPFLAGS'
complete -c dpkg-buildflags -o fstack-protector -l param -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS'
complete -c dpkg-buildflags -o nostdlib -o ffreestanding -d 'stackprotectorstrong This setting (enabled by default) adds'
complete -c dpkg-buildflags -o fstack-protector-strong -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS'
complete -c dpkg-buildflags -s z -d 'to LDFLAGS'
complete -c dpkg-buildflags -o fPIE -d 'CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS, and'
complete -c dpkg-buildflags -o pie -d 'When the setting is disabled and gcc injects the flags, it adds'
complete -c dpkg-buildflags -o fno-PIE -d 'CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS, and'
complete -c dpkg-buildflags -o no-pie -d LDFLAGS
complete -c dpkg-buildflags -o fPIC -d 'Can be linked into any program and shared library'
complete -c dpkg-buildflags -o Wdate-time -d 'to CPPFLAGS'
complete -c dpkg-buildflags -o ffile-prefix-map -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS whe…'
complete -c dpkg-buildflags -o fdebug-prefix-map -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, GCJFLAGS, FFLAGS and FCFLAGS whe…'

