# dumpe2fs
# Autogenerated from man page /usr/share/man/man8/dumpe2fs.8.gz
complete -c dumpe2fs -s b -d 'print the blocks which are reserved as bad in the filesystem'
complete -c dumpe2fs -s o -d 'use the block  superblock when examining the filesystem'
complete -c dumpe2fs -s f -d 'force dumpe2fs to display a filesystem even though it may have some filesyste…'
complete -c dumpe2fs -s g -d 'display the group descriptor information in a machine readable colon-separate…'
complete -c dumpe2fs -s h -d 'only display the superblock information and not any of the block group descri…'
complete -c dumpe2fs -s i -d 'display the filesystem data from an image file created by  e2image , using  d…'
complete -c dumpe2fs -s m -d 'If the  mmp feature is enabled on the filesystem, check if  device is in use …'
complete -c dumpe2fs -s x -d 'print the detailed group information block numbers in hexadecimal format'
complete -c dumpe2fs -s V -d 'print the version number of dumpe2fs and exit'

