# dvd+rw-format
# Autogenerated from man page /usr/share/man/man1/dvd+rw-format.1.gz
complete -c dvd+rw-format -o force -d 'This forces to format dvd as new while wiping any existing data'
complete -c dvd+rw-format -o blank -d 'This blanks dvd while changing to sequential mode'
complete -c dvd+rw-format -o lead-out -d 'This relocates the lead-out next to outermost written sector as well as makes…'

