# fixcvsdiff
# Autogenerated from man page /usr/share/man/man1/fixcvsdiff.1.gz
complete -c fixcvsdiff -s b -d 'Keep a . bak backup file'
complete -c fixcvsdiff -s p -d 'Print out the cvs add and cvs remove commands that must be made after applyin…'

