# flipdiff
# Autogenerated from man page /usr/share/man/man1/flipdiff.1.gz
complete -c flipdiff -s p -l strip-match -d 'When comparing filenames, ignore the first n pathname components from both pa…'
complete -c flipdiff -s q -l quiet -d 'Quieter output'
complete -c flipdiff -s U -l unified -d 'Attempt to display n lines of context (requires at least n lines of context i…'
complete -c flipdiff -s d -l drop-context -d 'Don\\*(Aqt display any context on files that match the shell wildcard pattern'
complete -c flipdiff -s i -l ignore-case -d 'Consider upper- and lower-case to be the same'
complete -c flipdiff -s w -l ignore-all-space -d 'Ignore whitespace changes in patches'
complete -c flipdiff -s b -l ignore-space-change -d 'Ignore changes in the amount of whitespace'
complete -c flipdiff -s B -l ignore-blank-lines -d 'Ignore changes whose lines are all blank'
complete -c flipdiff -s z -l decompress -d 'Decompress files with extensions . gz and . bz2'
complete -c flipdiff -l in-place -d 'Write output to the original input files'
complete -c flipdiff -l help -d 'Display a short usage message'
complete -c flipdiff -l version -d 'Display the version number of flipdiff'

