# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.minix.8.gz
complete -c fsck -l list -d 'List all filenames'
complete -c fsck -l repair -d 'Perform interactive repairs'
complete -c fsck -l auto -d 'Perform automatic repairs'
complete -c fsck -l super -d 'Output super-block information'
complete -c fsck -s m -l uncleared -d 'Activate MINIX-like "mode not cleared" warnings'
complete -c fsck -l force -d 'Force a filesystem check even if the filesystem was marked as valid'

