# fwupdagent
# Autogenerated from man page /usr/share/man/man1/fwupdagent.1.gz
complete -c fwupdagent -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c fwupdagent -s v -l verbose -d 'Show extra debugging information'
complete -c fwupdagent -l force -d 'Override warnings and force the action'

