# gcloud_beta_dataflow_logs_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_dataflow_logs_list.1.gz
complete -c gcloud_beta_dataflow_logs_list -l after
complete -c gcloud_beta_dataflow_logs_list -l before
complete -c gcloud_beta_dataflow_logs_list -l importance
complete -c gcloud_beta_dataflow_logs_list -l region
complete -c gcloud_beta_dataflow_logs_list -l filter
complete -c gcloud_beta_dataflow_logs_list -l sort-by -l limit
complete -c gcloud_beta_dataflow_logs_list -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_dataflow_logs_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_dataflow_logs_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_dataflow_logs_list -l verbosity

