# gcloud_beta_compute_start-iap-tunnel
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_start-iap-tunnel.1.gz
complete -c gcloud_beta_compute_start-iap-tunnel -l iap-tunnel-disable-connection-check
complete -c gcloud_beta_compute_start-iap-tunnel -l local-host-port
complete -c gcloud_beta_compute_start-iap-tunnel -l zone
complete -c gcloud_beta_compute_start-iap-tunnel -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_start-iap-tunnel -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_start-iap-tunnel -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_start-iap-tunnel -l verbosity

