# gcloud_alpha_service-directory_services_resolve
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_service-directory_services_resolve.1.gz
complete -c gcloud_alpha_service-directory_services_resolve -l location
complete -c gcloud_alpha_service-directory_services_resolve -l namespace
complete -c gcloud_alpha_service-directory_services_resolve -l endpoint-filter
complete -c gcloud_alpha_service-directory_services_resolve -l max-endpoints
complete -c gcloud_alpha_service-directory_services_resolve -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_service-directory_services_resolve -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_service-directory_services_resolve -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_service-directory_services_resolve -l verbosity

