# gcloud_alpha_ml_vision_product-search_products_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ml_vision_product-search_products_create.1.gz
complete -c gcloud_alpha_ml_vision_product-search_products_create -l location
complete -c gcloud_alpha_ml_vision_product-search_products_create -l category
complete -c gcloud_alpha_ml_vision_product-search_products_create -l display-name
complete -c gcloud_alpha_ml_vision_product-search_products_create -l description
complete -c gcloud_alpha_ml_vision_product-search_products_create -l product-labels
complete -c gcloud_alpha_ml_vision_product-search_products_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ml_vision_product-search_products_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ml_vision_product-search_products_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ml_vision_product-search_products_create -l verbosity

