# gcloud_alpha_healthcare_consent-stores_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_healthcare_consent-stores_delete.1.gz
complete -c gcloud_alpha_healthcare_consent-stores_delete -l dataset
complete -c gcloud_alpha_healthcare_consent-stores_delete -l location
complete -c gcloud_alpha_healthcare_consent-stores_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_healthcare_consent-stores_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_healthcare_consent-stores_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_healthcare_consent-stores_delete -l verbosity

