# gcloud_beta_composer_environments_storage_dags_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_composer_environments_storage_dags_delete.1.gz
complete -c gcloud_beta_composer_environments_storage_dags_delete -l environment
complete -c gcloud_beta_composer_environments_storage_dags_delete -l location
complete -c gcloud_beta_composer_environments_storage_dags_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_composer_environments_storage_dags_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_composer_environments_storage_dags_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_composer_environments_storage_dags_delete -l verbosity

