# gcloud_alpha_compute_routers_update-interface
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_routers_update-interface.1.gz
complete -c gcloud_alpha_compute_routers_update-interface -l interface-name
complete -c gcloud_alpha_compute_routers_update-interface -l ip-address
complete -c gcloud_alpha_compute_routers_update-interface -l mask-length
complete -c gcloud_alpha_compute_routers_update-interface -l region
complete -c gcloud_alpha_compute_routers_update-interface -l interconnect-attachment
complete -c gcloud_alpha_compute_routers_update-interface -l interconnect-attachment-region
complete -c gcloud_alpha_compute_routers_update-interface -l vpn-tunnel
complete -c gcloud_alpha_compute_routers_update-interface -l vpn-tunnel-region
complete -c gcloud_alpha_compute_routers_update-interface -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_routers_update-interface -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_routers_update-interface -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_routers_update-interface -l verbosity

