# gcloud_beta_events_namespaces_init
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_events_namespaces_init.1.gz
complete -c gcloud_beta_events_namespaces_init -l authentication
complete -c gcloud_beta_events_namespaces_init -l copy-default-secret
complete -c gcloud_beta_events_namespaces_init -l platform
complete -c gcloud_beta_events_namespaces_init -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_namespaces_init -l cluster
complete -c gcloud_beta_events_namespaces_init -l context
complete -c gcloud_beta_events_namespaces_init -l kubeconfig
complete -c gcloud_beta_events_namespaces_init -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_events_namespaces_init -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_events_namespaces_init -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_events_namespaces_init -l verbosity

