# gcloud_artifacts_print-settings_python
# Autogenerated from man page /usr/share/man/man1/gcloud_artifacts_print-settings_python.1.gz
complete -c gcloud_artifacts_print-settings_python -l json-key
complete -c gcloud_artifacts_print-settings_python -l repository
complete -c gcloud_artifacts_print-settings_python -l location
complete -c gcloud_artifacts_print-settings_python -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_artifacts_print-settings_python -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_artifacts_print-settings_python -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_artifacts_print-settings_python -l verbosity

