# gcloud_beta
# Autogenerated from man page /usr/share/man/man1/gcloud_beta.1.gz
complete -c gcloud_beta -l account
complete -c gcloud_beta -l billing-project
complete -c gcloud_beta -l help
complete -c gcloud_beta -l configuration
complete -c gcloud_beta -l flags-file
complete -c gcloud_beta -l flatten
complete -c gcloud_beta -l sort-by -l filter -l limit
complete -c gcloud_beta -l format
complete -c gcloud_beta -l project
complete -c gcloud_beta -l quiet -s q
complete -c gcloud_beta -l verbosity
complete -c gcloud_beta -l version -s v
complete -c gcloud_beta -s h
complete -c gcloud_beta -l access-token-file
complete -c gcloud_beta -l impersonate-service-account
complete -c gcloud_beta -l log-http
complete -c gcloud_beta -l trace-token
complete -c gcloud_beta -l user-output-enabled
complete -c gcloud_beta -l no-user-output-enabled -d GROUPS

