# gcloud_alpha_deployment-manager_operations_list
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_deployment-manager_operations_list.1.gz
complete -c gcloud_alpha_deployment-manager_operations_list -l simple-list
complete -c gcloud_alpha_deployment-manager_operations_list -l format -d 'LIST COMMAND FLAGS'
complete -c gcloud_alpha_deployment-manager_operations_list -l filter
complete -c gcloud_alpha_deployment-manager_operations_list -l sort-by -l limit
complete -c gcloud_alpha_deployment-manager_operations_list -l page-size
complete -c gcloud_alpha_deployment-manager_operations_list -l flatten
complete -c gcloud_alpha_deployment-manager_operations_list -l uri
complete -c gcloud_alpha_deployment-manager_operations_list -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_deployment-manager_operations_list -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_deployment-manager_operations_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_deployment-manager_operations_list -l verbosity

