# gcloud_alpha_trace_sinks_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_trace_sinks_delete.1.gz
complete -c gcloud_alpha_trace_sinks_delete -l project
complete -c gcloud_alpha_trace_sinks_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_trace_sinks_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_trace_sinks_delete -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_trace_sinks_delete -l verbosity

