# gcloud_beta_container_operations
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_container_operations.1.gz
complete -c gcloud_beta_container_operations -l region
complete -c gcloud_beta_container_operations -l zone -s z

