# gcloud_kms_keys_versions_destroy
# Autogenerated from man page /usr/share/man/man1/gcloud_kms_keys_versions_destroy.1.gz
complete -c gcloud_kms_keys_versions_destroy -l key
complete -c gcloud_kms_keys_versions_destroy -l keyring
complete -c gcloud_kms_keys_versions_destroy -l location
complete -c gcloud_kms_keys_versions_destroy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_kms_keys_versions_destroy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_kms_keys_versions_destroy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_kms_keys_versions_destroy -l verbosity

