# gcloud_beta_debug_snapshots_wait
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_debug_snapshots_wait.1.gz
complete -c gcloud_beta_debug_snapshots_wait -l all
complete -c gcloud_beta_debug_snapshots_wait -l all-users
complete -c gcloud_beta_debug_snapshots_wait -l location
complete -c gcloud_beta_debug_snapshots_wait -l target
complete -c gcloud_beta_debug_snapshots_wait -l timeout
complete -c gcloud_beta_debug_snapshots_wait -l filter
complete -c gcloud_beta_debug_snapshots_wait -l sort-by -l limit
complete -c gcloud_beta_debug_snapshots_wait -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_debug_snapshots_wait -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_debug_snapshots_wait -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_debug_snapshots_wait -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_debug_snapshots_wait -l verbosity

