# gcloud_alpha_compute_diagnose_sosreport
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_diagnose_sosreport.1.gz
complete -c gcloud_alpha_compute_diagnose_sosreport -l download-dir -d 'resulting from the VM'
complete -c gcloud_alpha_compute_diagnose_sosreport -l dry-run
complete -c gcloud_alpha_compute_diagnose_sosreport -l force-key-file-overwrite
complete -c gcloud_alpha_compute_diagnose_sosreport -l plain
complete -c gcloud_alpha_compute_diagnose_sosreport -l python-path
complete -c gcloud_alpha_compute_diagnose_sosreport -l reports-path
complete -c gcloud_alpha_compute_diagnose_sosreport -l sosreport-install-path
complete -c gcloud_alpha_compute_diagnose_sosreport -l ssh-flag
complete -c gcloud_alpha_compute_diagnose_sosreport -l ssh-key-file
complete -c gcloud_alpha_compute_diagnose_sosreport -l strict-host-key-checking
complete -c gcloud_alpha_compute_diagnose_sosreport -l user
complete -c gcloud_alpha_compute_diagnose_sosreport -l zone
complete -c gcloud_alpha_compute_diagnose_sosreport -l ssh-key-expiration
complete -c gcloud_alpha_compute_diagnose_sosreport -l ssh-key-expire-after
complete -c gcloud_alpha_compute_diagnose_sosreport -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_diagnose_sosreport -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_diagnose_sosreport -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_diagnose_sosreport -l verbosity

