# gcloud_org-policies_reset
# Autogenerated from man page /usr/share/man/man1/gcloud_org-policies_reset.1.gz
complete -c gcloud_org-policies_reset -l folder
complete -c gcloud_org-policies_reset -l organization
complete -c gcloud_org-policies_reset -l project
complete -c gcloud_org-policies_reset -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_org-policies_reset -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_org-policies_reset -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_org-policies_reset -l verbosity

