# gcloud_access-context-manager_perimeters_dry-run_enforce
# Autogenerated from man page /usr/share/man/man1/gcloud_access-context-manager_perimeters_dry-run_enforce.1.gz
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l policy
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l async
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce -l verbosity

