# gcloud_alpha_healthcare_dicom-stores_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_healthcare_dicom-stores_create.1.gz
complete -c gcloud_alpha_healthcare_dicom-stores_create -l dataset
complete -c gcloud_alpha_healthcare_dicom-stores_create -l location
complete -c gcloud_alpha_healthcare_dicom-stores_create -l pubsub-topic
complete -c gcloud_alpha_healthcare_dicom-stores_create -l send-for-bulk-import
complete -c gcloud_alpha_healthcare_dicom-stores_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_healthcare_dicom-stores_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_healthcare_dicom-stores_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_healthcare_dicom-stores_create -l verbosity

