# gcloud_alpha_compute_project-info_set-default-service-account
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_project-info_set-default-service-account.1.gz
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l service-account
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l no-service-account
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_project-info_set-default-service-account -l verbosity

