# gcloud_compute_packet-mirrorings_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_packet-mirrorings_create.1.gz
complete -c gcloud_compute_packet-mirrorings_create -l collector-ilb
complete -c gcloud_compute_packet-mirrorings_create -l network
complete -c gcloud_compute_packet-mirrorings_create -l async
complete -c gcloud_compute_packet-mirrorings_create -l description
complete -c gcloud_compute_packet-mirrorings_create -l enable
complete -c gcloud_compute_packet-mirrorings_create -l no-enable
complete -c gcloud_compute_packet-mirrorings_create -l filter-cidr-ranges
complete -c gcloud_compute_packet-mirrorings_create -l filter-direction
complete -c gcloud_compute_packet-mirrorings_create -l filter-protocols
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-instances
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-subnets
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-tags
complete -c gcloud_compute_packet-mirrorings_create -l region
complete -c gcloud_compute_packet-mirrorings_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_packet-mirrorings_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_packet-mirrorings_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_packet-mirrorings_create -l verbosity

