# gcloud_alpha_asset_get-history
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_asset_get-history.1.gz
complete -c gcloud_alpha_asset_get-history -l asset-names
complete -c gcloud_alpha_asset_get-history -l content-type
complete -c gcloud_alpha_asset_get-history -l start-time
complete -c gcloud_alpha_asset_get-history -l organization
complete -c gcloud_alpha_asset_get-history -l project
complete -c gcloud_alpha_asset_get-history -l end-time
complete -c gcloud_alpha_asset_get-history -l relationship-types
complete -c gcloud_alpha_asset_get-history -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_asset_get-history -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_asset_get-history -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_asset_get-history -l verbosity

