# gcloud_functions_deploy
# Autogenerated from man page /usr/share/man/man1/gcloud_functions_deploy.1.gz
complete -c gcloud_functions_deploy -l region
complete -c gcloud_functions_deploy -l allow-unauthenticated
complete -c gcloud_functions_deploy -l egress-settings
complete -c gcloud_functions_deploy -l entry-point
complete -c gcloud_functions_deploy -l ignore-file
complete -c gcloud_functions_deploy -l ingress-settings
complete -c gcloud_functions_deploy -l memory
complete -c gcloud_functions_deploy -l retry
complete -c gcloud_functions_deploy -l runtime
complete -c gcloud_functions_deploy -l security-level
complete -c gcloud_functions_deploy -l service-account
complete -c gcloud_functions_deploy -l source
complete -c gcloud_functions_deploy -l stage-bucket
complete -c gcloud_functions_deploy -l timeout
complete -c gcloud_functions_deploy -l update-labels
complete -c gcloud_functions_deploy -l build-env-vars-file
complete -c gcloud_functions_deploy -l clear-build-env-vars
complete -c gcloud_functions_deploy -l set-build-env-vars
complete -c gcloud_functions_deploy -l remove-build-env-vars
complete -c gcloud_functions_deploy -l update-build-env-vars
complete -c gcloud_functions_deploy -l build-worker-pool
complete -c gcloud_functions_deploy -l clear-build-worker-pool
complete -c gcloud_functions_deploy -l clear-env-vars
complete -c gcloud_functions_deploy -l env-vars-file
complete -c gcloud_functions_deploy -l set-env-vars
complete -c gcloud_functions_deploy -l remove-env-vars
complete -c gcloud_functions_deploy -l update-env-vars
complete -c gcloud_functions_deploy -l clear-labels
complete -c gcloud_functions_deploy -l remove-labels
complete -c gcloud_functions_deploy -l clear-max-instances
complete -c gcloud_functions_deploy -l max-instances
complete -c gcloud_functions_deploy -l clear-vpc-connector
complete -c gcloud_functions_deploy -l vpc-connector
complete -c gcloud_functions_deploy -l trigger-bucket -l trigger-http -l trigger-event -d 'AND --trigger-resource) when deploying a new function'
complete -c gcloud_functions_deploy -l trigger-topic
complete -c gcloud_functions_deploy -l trigger-resource
complete -c gcloud_functions_deploy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_functions_deploy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_functions_deploy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_functions_deploy -l verbosity

