# gcloud_alpha_access-context-manager_perimeters_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_access-context-manager_perimeters_create.1.gz
complete -c gcloud_alpha_access-context-manager_perimeters_create -l policy
complete -c gcloud_alpha_access-context-manager_perimeters_create -l title
complete -c gcloud_alpha_access-context-manager_perimeters_create -l access-levels
complete -c gcloud_alpha_access-context-manager_perimeters_create -l async
complete -c gcloud_alpha_access-context-manager_perimeters_create -l description
complete -c gcloud_alpha_access-context-manager_perimeters_create -l egress-policies
complete -c gcloud_alpha_access-context-manager_perimeters_create -l ingress-policies
complete -c gcloud_alpha_access-context-manager_perimeters_create -l perimeter-type
complete -c gcloud_alpha_access-context-manager_perimeters_create -l resources
complete -c gcloud_alpha_access-context-manager_perimeters_create -l restricted-services
complete -c gcloud_alpha_access-context-manager_perimeters_create -l enable-vpc-accessible-services
complete -c gcloud_alpha_access-context-manager_perimeters_create -l vpc-allowed-services
complete -c gcloud_alpha_access-context-manager_perimeters_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_access-context-manager_perimeters_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_access-context-manager_perimeters_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_access-context-manager_perimeters_create -l verbosity

