# gcloud_dataproc_workflow-templates_add-job_presto
# Autogenerated from man page /usr/share/man/man1/gcloud_dataproc_workflow-templates_add-job_presto.1.gz
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l step-id
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l execute -s e
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l file -s f
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l workflow-template
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l region
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l client-tags
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l continue-on-failure
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l driver-log-levels
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l labels
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l properties
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l query-output-format
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l start-after
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dataproc_workflow-templates_add-job_presto -l verbosity

