# gcloud_alpha_builds_enterprise-config_bitbucketserver_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_builds_enterprise-config_bitbucketserver_create.1.gz
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l admin-access-token-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l api-key
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l host-uri
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l read-access-token-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l user-name
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l webhook-secret-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l peered-network
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_create -l verbosity

