# gcloud_beta_healthcare_consent-stores_check-data-access
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_healthcare_consent-stores_check-data-access.1.gz
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l dataset
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l location
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l data-id
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l request-attributes
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_healthcare_consent-stores_check-data-access -l verbosity

