# gcloud_alpha_apigee_archives_deploy
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_apigee_archives_deploy.1.gz
complete -c gcloud_alpha_apigee_archives_deploy -l environment
complete -c gcloud_alpha_apigee_archives_deploy -l organization
complete -c gcloud_alpha_apigee_archives_deploy -l async
complete -c gcloud_alpha_apigee_archives_deploy -l labels
complete -c gcloud_alpha_apigee_archives_deploy -l bundle-file
complete -c gcloud_alpha_apigee_archives_deploy -l source
complete -c gcloud_alpha_apigee_archives_deploy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_apigee_archives_deploy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_apigee_archives_deploy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_apigee_archives_deploy -l verbosity

