# gcloud_beta_spanner_instances_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_spanner_instances_update.1.gz
complete -c gcloud_beta_spanner_instances_update -l async
complete -c gcloud_beta_spanner_instances_update -l description
complete -c gcloud_beta_spanner_instances_update -l nodes
complete -c gcloud_beta_spanner_instances_update -l processing-units
complete -c gcloud_beta_spanner_instances_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_spanner_instances_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_spanner_instances_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_spanner_instances_update -l verbosity

