# gcloud_beta_scc_findings_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_scc_findings_create.1.gz
complete -c gcloud_beta_scc_findings_create -l organization
complete -c gcloud_beta_scc_findings_create -l source
complete -c gcloud_beta_scc_findings_create -l category
complete -c gcloud_beta_scc_findings_create -l resource-name
complete -c gcloud_beta_scc_findings_create -l event-time
complete -c gcloud_beta_scc_findings_create -l external-uri
complete -c gcloud_beta_scc_findings_create -l source-properties
complete -c gcloud_beta_scc_findings_create -l state
complete -c gcloud_beta_scc_findings_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_scc_findings_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_scc_findings_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_scc_findings_create -l verbosity

