# gcloud_alpha_dns_record-sets_transaction
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dns_record-sets_transaction.1.gz
complete -c gcloud_alpha_dns_record-sets_transaction -l transaction-file

