# gcloud_alpha_web-security-scanner_scan-configs_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_web-security-scanner_scan-configs_update.1.gz
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l blacklist-patterns
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l display-name
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l export-to-security-center
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l no-export-to-security-center
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l max-qps
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l risk-level
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l schedule-interval-days
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l schedule-next-start
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l starting-urls
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l target-platforms
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l user-agent
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l auth-password
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l auth-type
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l auth-url
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l auth-user
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_web-security-scanner_scan-configs_update -l verbosity

