# gcloud_alpha_service-directory_services_set-iam-policy
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_service-directory_services_set-iam-policy.1.gz
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l location
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l namespace
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_service-directory_services_set-iam-policy -l verbosity

