# gcloud_alpha_data-catalog_entries_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_data-catalog_entries_create.1.gz
complete -c gcloud_alpha_data-catalog_entries_create -l entry-group
complete -c gcloud_alpha_data-catalog_entries_create -l location
complete -c gcloud_alpha_data-catalog_entries_create -l gcs-file-patterns
complete -c gcloud_alpha_data-catalog_entries_create -l description
complete -c gcloud_alpha_data-catalog_entries_create -l display-name
complete -c gcloud_alpha_data-catalog_entries_create -l schema
complete -c gcloud_alpha_data-catalog_entries_create -l schema-from-file
complete -c gcloud_alpha_data-catalog_entries_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_data-catalog_entries_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_data-catalog_entries_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_data-catalog_entries_create -l verbosity

