# gcloud_alpha_builds_deploy_configure_gke
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_builds_deploy_configure_gke.1.gz
complete -c gcloud_alpha_builds_deploy_configure_gke -l cluster
complete -c gcloud_alpha_builds_deploy_configure_gke -l location
complete -c gcloud_alpha_builds_deploy_configure_gke -l repo-name
complete -c gcloud_alpha_builds_deploy_configure_gke -l repo-type
complete -c gcloud_alpha_builds_deploy_configure_gke -l repo-owner -d selected:
complete -c gcloud_alpha_builds_deploy_configure_gke -l branch-pattern
complete -c gcloud_alpha_builds_deploy_configure_gke -l tag-pattern
complete -c gcloud_alpha_builds_deploy_configure_gke -l pull-request-pattern
complete -c gcloud_alpha_builds_deploy_configure_gke -l pull-request-preview
complete -c gcloud_alpha_builds_deploy_configure_gke -l comment-control
complete -c gcloud_alpha_builds_deploy_configure_gke -l preview-expiry
complete -c gcloud_alpha_builds_deploy_configure_gke -l app-name
complete -c gcloud_alpha_builds_deploy_configure_gke -l config
complete -c gcloud_alpha_builds_deploy_configure_gke -l dockerfile
complete -c gcloud_alpha_builds_deploy_configure_gke -l expose
complete -c gcloud_alpha_builds_deploy_configure_gke -l gcs-config-staging-dir
complete -c gcloud_alpha_builds_deploy_configure_gke -l namespace
complete -c gcloud_alpha_builds_deploy_configure_gke -l timeout
complete -c gcloud_alpha_builds_deploy_configure_gke -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_builds_deploy_configure_gke -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_builds_deploy_configure_gke -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_builds_deploy_configure_gke -l verbosity

