# gcloud_alpha_dialogflow_intents_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dialogflow_intents_update.1.gz
complete -c gcloud_alpha_dialogflow_intents_update -l is-fallback
complete -c gcloud_alpha_dialogflow_intents_update -l ml-enabled
complete -c gcloud_alpha_dialogflow_intents_update -l no-ml-enabled
complete -c gcloud_alpha_dialogflow_intents_update -l other-properties
complete -c gcloud_alpha_dialogflow_intents_update -l priority
complete -c gcloud_alpha_dialogflow_intents_update -l responses
complete -c gcloud_alpha_dialogflow_intents_update -l training-phrases
complete -c gcloud_alpha_dialogflow_intents_update -l flags-file
complete -c gcloud_alpha_dialogflow_intents_update -l billing-project -l configuration -l flatten
complete -c gcloud_alpha_dialogflow_intents_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dialogflow_intents_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dialogflow_intents_update -l verbosity

