# gcloud_compute_operations_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_operations_describe.1.gz
complete -c gcloud_compute_operations_describe -l global
complete -c gcloud_compute_operations_describe -l region
complete -c gcloud_compute_operations_describe -l zone
complete -c gcloud_compute_operations_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_operations_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_operations_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_operations_describe -l verbosity

