# gcloud_alpha_firebase_test_ios_run
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_firebase_test_ios_run.1.gz
complete -c gcloud_alpha_firebase_test_ios_run -l device -d '$ gcloud alpha firebase test ios run --test=XCTEST_ZIP \\     --device=model=i…'
complete -c gcloud_alpha_firebase_test_ios_run -l scenario-numbers -d '$ gcloud alpha firebase test ios run --type=game-loop \\     --app=app'
complete -c gcloud_alpha_firebase_test_ios_run -l other-files -d '$ gcloud alpha firebase test ios run --type=game-loop \\     --app=app'
complete -c gcloud_alpha_firebase_test_ios_run -l test
complete -c gcloud_alpha_firebase_test_ios_run -l timeout
complete -c gcloud_alpha_firebase_test_ios_run -l type
complete -c gcloud_alpha_firebase_test_ios_run -l xcode-version
complete -c gcloud_alpha_firebase_test_ios_run -l xctestrun-file
complete -c gcloud_alpha_firebase_test_ios_run -l additional-ipas
complete -c gcloud_alpha_firebase_test_ios_run -l app
complete -c gcloud_alpha_firebase_test_ios_run -l async
complete -c gcloud_alpha_firebase_test_ios_run -l client-details
complete -c gcloud_alpha_firebase_test_ios_run -l directories-to-pull
complete -c gcloud_alpha_firebase_test_ios_run -l num-flaky-test-attempts
complete -c gcloud_alpha_firebase_test_ios_run -l record-video
complete -c gcloud_alpha_firebase_test_ios_run -l no-record-video
complete -c gcloud_alpha_firebase_test_ios_run -l results-bucket
complete -c gcloud_alpha_firebase_test_ios_run -l results-dir
complete -c gcloud_alpha_firebase_test_ios_run -l results-history-name
complete -c gcloud_alpha_firebase_test_ios_run -l test-special-entitlements
complete -c gcloud_alpha_firebase_test_ios_run -l filter
complete -c gcloud_alpha_firebase_test_ios_run -l sort-by -l limit
complete -c gcloud_alpha_firebase_test_ios_run -l page-size
complete -c gcloud_alpha_firebase_test_ios_run -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_firebase_test_ios_run -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_firebase_test_ios_run -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_firebase_test_ios_run -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_firebase_test_ios_run -l verbosity

