# gcloud_beta_app_migrate-config_queue-xml-to-yaml
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_app_migrate-config_queue-xml-to-yaml.1.gz
complete -c gcloud_beta_app_migrate-config_queue-xml-to-yaml -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_app_migrate-config_queue-xml-to-yaml -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_app_migrate-config_queue-xml-to-yaml -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_app_migrate-config_queue-xml-to-yaml -l verbosity

