# gcloud_dns_record-sets_changes_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_dns_record-sets_changes_describe.1.gz
complete -c gcloud_dns_record-sets_changes_describe -l zone -s z
complete -c gcloud_dns_record-sets_changes_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dns_record-sets_changes_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dns_record-sets_changes_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dns_record-sets_changes_describe -l verbosity

