# gcloud_container_clusters_upgrade
# Autogenerated from man page /usr/share/man/man1/gcloud_container_clusters_upgrade.1.gz
complete -c gcloud_container_clusters_upgrade -l async
complete -c gcloud_container_clusters_upgrade -l cluster-version
complete -c gcloud_container_clusters_upgrade -l image-type
complete -c gcloud_container_clusters_upgrade -l master
complete -c gcloud_container_clusters_upgrade -l node-pool
complete -c gcloud_container_clusters_upgrade -l region
complete -c gcloud_container_clusters_upgrade -l zone -s z
complete -c gcloud_container_clusters_upgrade -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_container_clusters_upgrade -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_container_clusters_upgrade -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_container_clusters_upgrade -l verbosity

