# gcloud_alpha_run_services_set-iam-policy
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_run_services_set-iam-policy.1.gz
complete -c gcloud_alpha_run_services_set-iam-policy -l platform
complete -c gcloud_alpha_run_services_set-iam-policy -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_alpha_run_services_set-iam-policy -l region
complete -c gcloud_alpha_run_services_set-iam-policy -l cluster
complete -c gcloud_alpha_run_services_set-iam-policy -l context
complete -c gcloud_alpha_run_services_set-iam-policy -l kubeconfig
complete -c gcloud_alpha_run_services_set-iam-policy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_run_services_set-iam-policy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_run_services_set-iam-policy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_run_services_set-iam-policy -l verbosity

