# gcloud_beta_auth_print-access-token
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_auth_print-access-token.1.gz
complete -c gcloud_beta_auth_print-access-token -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_auth_print-access-token -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_auth_print-access-token -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_auth_print-access-token -l verbosity

