# gcloud_beta_dns_record-sets_export
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_dns_record-sets_export.1.gz
complete -c gcloud_beta_dns_record-sets_export -l zone -s z
complete -c gcloud_beta_dns_record-sets_export -l zone-file-format
complete -c gcloud_beta_dns_record-sets_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_dns_record-sets_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_dns_record-sets_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_dns_record-sets_export -l verbosity

