# gcloud_components_list
# Autogenerated from man page /usr/share/man/man1/gcloud_components_list.1.gz
complete -c gcloud_components_list -l only-local-state
complete -c gcloud_components_list -l show-platform
complete -c gcloud_components_list -l show-versions
complete -c gcloud_components_list -l filter
complete -c gcloud_components_list -l sort-by -l limit
complete -c gcloud_components_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_components_list -l billing-project -l configuration -l flags-file
complete -c gcloud_components_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_components_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_components_list -l verbosity

