# gcloud_alpha_compute_url-maps_set-default-service
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_url-maps_set-default-service.1.gz
complete -c gcloud_alpha_compute_url-maps_set-default-service -l default-backend-bucket
complete -c gcloud_alpha_compute_url-maps_set-default-service -l default-service
complete -c gcloud_alpha_compute_url-maps_set-default-service -l global
complete -c gcloud_alpha_compute_url-maps_set-default-service -l region
complete -c gcloud_alpha_compute_url-maps_set-default-service -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_url-maps_set-default-service -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_url-maps_set-default-service -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_url-maps_set-default-service -l verbosity

