# gcloud_beta_compute_vpn-gateways_get-status
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_vpn-gateways_get-status.1.gz
complete -c gcloud_beta_compute_vpn-gateways_get-status -l region
complete -c gcloud_beta_compute_vpn-gateways_get-status -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_vpn-gateways_get-status -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_vpn-gateways_get-status -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_vpn-gateways_get-status -l verbosity

