# gcloud_alpha_dlp_datasources_gcs_inspect
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dlp_datasources_gcs_inspect.1.gz
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l exclude-info-types
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l file-size-limit
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l include-quote
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l info-types
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l job-id
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l max-findings
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l max-findings-per-item
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l max-time
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l min-likelihood
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l min-time
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l output-table
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l output-topics
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dlp_datasources_gcs_inspect -l verbosity

