# gcloud_beta_runtime-config_configs_waiters_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_runtime-config_configs_waiters_create.1.gz
complete -c gcloud_beta_runtime-config_configs_waiters_create -l config-name
complete -c gcloud_beta_runtime-config_configs_waiters_create -l success-cardinality-path
complete -c gcloud_beta_runtime-config_configs_waiters_create -l timeout
complete -c gcloud_beta_runtime-config_configs_waiters_create -l async
complete -c gcloud_beta_runtime-config_configs_waiters_create -l failure-cardinality-number
complete -c gcloud_beta_runtime-config_configs_waiters_create -l failure-cardinality-path
complete -c gcloud_beta_runtime-config_configs_waiters_create -l success-cardinality-number
complete -c gcloud_beta_runtime-config_configs_waiters_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_runtime-config_configs_waiters_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_runtime-config_configs_waiters_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_runtime-config_configs_waiters_create -l verbosity

