# gcloud_beta_compute_vpn-tunnels_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_vpn-tunnels_create.1.gz
complete -c gcloud_beta_compute_vpn-tunnels_create -l shared-secret
complete -c gcloud_beta_compute_vpn-tunnels_create -l peer-address
complete -c gcloud_beta_compute_vpn-tunnels_create -l peer-external-gateway
complete -c gcloud_beta_compute_vpn-tunnels_create -l peer-gcp-gateway
complete -c gcloud_beta_compute_vpn-tunnels_create -l peer-gcp-gateway-region
complete -c gcloud_beta_compute_vpn-tunnels_create -l target-vpn-gateway
complete -c gcloud_beta_compute_vpn-tunnels_create -l target-vpn-gateway-region
complete -c gcloud_beta_compute_vpn-tunnels_create -l vpn-gateway
complete -c gcloud_beta_compute_vpn-tunnels_create -l vpn-gateway-region
complete -c gcloud_beta_compute_vpn-tunnels_create -l description
complete -c gcloud_beta_compute_vpn-tunnels_create -l ike-version
complete -c gcloud_beta_compute_vpn-tunnels_create -l interface
complete -c gcloud_beta_compute_vpn-tunnels_create -l local-traffic-selector
complete -c gcloud_beta_compute_vpn-tunnels_create -l peer-external-gateway-interface
complete -c gcloud_beta_compute_vpn-tunnels_create -l region
complete -c gcloud_beta_compute_vpn-tunnels_create -l remote-traffic-selector
complete -c gcloud_beta_compute_vpn-tunnels_create -l router
complete -c gcloud_beta_compute_vpn-tunnels_create -l router-region
complete -c gcloud_beta_compute_vpn-tunnels_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_vpn-tunnels_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_vpn-tunnels_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_vpn-tunnels_create -l verbosity

