# gcloud_alpha_container_hub_config-management_fetch-for-apply
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_hub_config-management_fetch-for-apply.1.gz
complete -c gcloud_alpha_container_hub_config-management_fetch-for-apply -l membership
complete -c gcloud_alpha_container_hub_config-management_fetch-for-apply -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_hub_config-management_fetch-for-apply -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_hub_config-management_fetch-for-apply -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_hub_config-management_fetch-for-apply -l verbosity

