# gcloud_compute_routers_nats_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_routers_nats_delete.1.gz
complete -c gcloud_compute_routers_nats_delete -l router
complete -c gcloud_compute_routers_nats_delete -l region
complete -c gcloud_compute_routers_nats_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_routers_nats_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_routers_nats_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_routers_nats_delete -l verbosity

