# gcloud_alpha_ai_custom-jobs_local-run
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ai_custom-jobs_local-run.1.gz
complete -c gcloud_alpha_ai_custom-jobs_local-run -l executor-image-uri
complete -c gcloud_alpha_ai_custom-jobs_local-run -l extra-dirs
complete -c gcloud_alpha_ai_custom-jobs_local-run -l extra-packages
complete -c gcloud_alpha_ai_custom-jobs_local-run -l gpu
complete -c gcloud_alpha_ai_custom-jobs_local-run -l local-package-path
complete -c gcloud_alpha_ai_custom-jobs_local-run -l output-image-uri
complete -c gcloud_alpha_ai_custom-jobs_local-run -l requirements
complete -c gcloud_alpha_ai_custom-jobs_local-run -l service-account-key-file
complete -c gcloud_alpha_ai_custom-jobs_local-run -l python-module
complete -c gcloud_alpha_ai_custom-jobs_local-run -l script
complete -c gcloud_alpha_ai_custom-jobs_local-run -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ai_custom-jobs_local-run -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ai_custom-jobs_local-run -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ai_custom-jobs_local-run -l verbosity

