# gcloud_beta_builds_log
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_builds_log.1.gz
complete -c gcloud_beta_builds_log -l region
complete -c gcloud_beta_builds_log -l stream
complete -c gcloud_beta_builds_log -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_builds_log -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_builds_log -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_builds_log -l verbosity

