# gcloud_alpha_container_backup-restore_backup-plans_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_backup-restore_backup-plans_describe.1.gz
complete -c gcloud_alpha_container_backup-restore_backup-plans_describe -l location -d 'the attributes of this resource'
complete -c gcloud_alpha_container_backup-restore_backup-plans_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_backup-restore_backup-plans_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_backup-restore_backup-plans_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_backup-restore_backup-plans_describe -l verbosity

