# gcloud_beta_game_servers_deployments_fetch-state
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_game_servers_deployments_fetch-state.1.gz
complete -c gcloud_beta_game_servers_deployments_fetch-state -l location
complete -c gcloud_beta_game_servers_deployments_fetch-state -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_game_servers_deployments_fetch-state -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_game_servers_deployments_fetch-state -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_game_servers_deployments_fetch-state -l verbosity

