# gcloud_compute_instance-groups_managed_instance-configs_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_instance-groups_managed_instance-configs_create.1.gz
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l instance
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l instance-update-minimal-action
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l update-instance -d 'INSTANCE_UPDATE_MINIMAL_ACTION must be one of: none No action'
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l stateful-disk
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l stateful-metadata
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l region
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l zone
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_instance-groups_managed_instance-configs_create -l verbosity

