# gcloud_alpha_identity_groups_memberships_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_identity_groups_memberships_describe.1.gz
complete -c gcloud_alpha_identity_groups_memberships_describe -l group-email
complete -c gcloud_alpha_identity_groups_memberships_describe -l member-email
complete -c gcloud_alpha_identity_groups_memberships_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_identity_groups_memberships_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_identity_groups_memberships_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_identity_groups_memberships_describe -l verbosity

