# gcloud_asset_list
# Autogenerated from man page /usr/share/man/man1/gcloud_asset_list.1.gz
complete -c gcloud_asset_list -l folder
complete -c gcloud_asset_list -l organization
complete -c gcloud_asset_list -l project
complete -c gcloud_asset_list -l asset-types
complete -c gcloud_asset_list -l content-type
complete -c gcloud_asset_list -l relationship-types
complete -c gcloud_asset_list -l snapshot-time
complete -c gcloud_asset_list -l filter
complete -c gcloud_asset_list -l sort-by -l limit
complete -c gcloud_asset_list -l page-size
complete -c gcloud_asset_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_asset_list -l billing-project -l configuration -l flags-file
complete -c gcloud_asset_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_asset_list -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_asset_list -l verbosity

