# gcloud_beta_config_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_config_list.1.gz
complete -c gcloud_beta_config_list -l all
complete -c gcloud_beta_config_list -l filter
complete -c gcloud_beta_config_list -l sort-by -l limit
complete -c gcloud_beta_config_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_config_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_config_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_config_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_config_list -l verbosity
complete -c gcloud_beta_config_list -l region -d 'to this value, if set.  ai_platform region'
complete -c gcloud_beta_config_list -l zone -d 'this value, if set.  To see valid choices, run gcloud compute zones list'
complete -c gcloud_beta_config_list -l location -d 'to this value, if set.  filestore location'
complete -c gcloud_beta_config_list -l realm -d 'fall back to this value which envokes aggregated list from the backend'
complete -c gcloud_beta_config_list -l dataset -d 'to this value, if set.  location'

