# gcloud_alpha_container_backup-restore_backups_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_backup-restore_backups_delete.1.gz
complete -c gcloud_alpha_container_backup-restore_backups_delete -l location -l backup-plan -d 'group can be used to specify the attributes of this resource'
complete -c gcloud_alpha_container_backup-restore_backups_delete -l async
complete -c gcloud_alpha_container_backup-restore_backups_delete -l etag
complete -c gcloud_alpha_container_backup-restore_backups_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_backup-restore_backups_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_backup-restore_backups_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_backup-restore_backups_delete -l verbosity

