# gcloud_compute_networks_peerings_list-routes
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_networks_peerings_list-routes.1.gz
complete -c gcloud_compute_networks_peerings_list-routes -l direction
complete -c gcloud_compute_networks_peerings_list-routes -l network
complete -c gcloud_compute_networks_peerings_list-routes -l region
complete -c gcloud_compute_networks_peerings_list-routes -l filter
complete -c gcloud_compute_networks_peerings_list-routes -l sort-by -l limit
complete -c gcloud_compute_networks_peerings_list-routes -l page-size
complete -c gcloud_compute_networks_peerings_list-routes -l flatten
complete -c gcloud_compute_networks_peerings_list-routes -l uri
complete -c gcloud_compute_networks_peerings_list-routes -l billing-project -l configuration -l flags-file
complete -c gcloud_compute_networks_peerings_list-routes -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_networks_peerings_list-routes -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_networks_peerings_list-routes -l verbosity

