# gcloud_workspace-add-ons_get-authorization
# Autogenerated from man page /usr/share/man/man1/gcloud_workspace-add-ons_get-authorization.1.gz
complete -c gcloud_workspace-add-ons_get-authorization -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_workspace-add-ons_get-authorization -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_workspace-add-ons_get-authorization -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_workspace-add-ons_get-authorization -l verbosity

