# gcloud_beta_compute_org-security-policies_copy-rules
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_org-security-policies_copy-rules.1.gz
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l source-security-policy
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l organization
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_org-security-policies_copy-rules -l verbosity

