# gcloud_bigtable_instances_tables_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_bigtable_instances_tables_describe.1.gz
complete -c gcloud_bigtable_instances_tables_describe -l instance
complete -c gcloud_bigtable_instances_tables_describe -l view
complete -c gcloud_bigtable_instances_tables_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_bigtable_instances_tables_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_bigtable_instances_tables_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_bigtable_instances_tables_describe -l verbosity

