# gcloud_compute_os-config_patch-jobs_execute
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_os-config_patch-jobs_execute.1.gz
complete -c gcloud_compute_os-config_patch-jobs_execute -l display-name -l instance-filter-all -d 'To patch an instance named instance-1 in the us-east1-b zone, run: $ gcloud c…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l instance-filter-names -d 'To patch all instances in the us-central1-b and europe-west1-d zones, run: $ …'
complete -c gcloud_compute_os-config_patch-jobs_execute -l instance-filter-zones -d 'To patch all instances where the env label is test and app label is web, run:…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l instance-filter-group-labels -d 'To patch all instances where the env label is test and app label is web or wh…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l instance-filter-name-prefixes
complete -c gcloud_compute_os-config_patch-jobs_execute -l windows-classifications -d 'To update only KB4339284 on Windows instances with the prefix windows- in the…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l windows-exclusive-patches -d 'To patch all instances in the current project and specify scripts to run pre-…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l pre-patch-linux-executable
complete -c gcloud_compute_os-config_patch-jobs_execute -l pre-patch-linux-success-codes
complete -c gcloud_compute_os-config_patch-jobs_execute -l pre-patch-windows-executable
complete -c gcloud_compute_os-config_patch-jobs_execute -l post-patch-linux-executable
complete -c gcloud_compute_os-config_patch-jobs_execute -l post-patch-windows-executable -d 'To patch all instances zone-by-zone with no more than 50 percent of the insta…'
complete -c gcloud_compute_os-config_patch-jobs_execute -l rollout-mode
complete -c gcloud_compute_os-config_patch-jobs_execute -l rollout-disruption-budget-percent -d 'REQUIRED FLAGS Filters for selecting which instances to patch:'
complete -c gcloud_compute_os-config_patch-jobs_execute -l async
complete -c gcloud_compute_os-config_patch-jobs_execute -l description
complete -c gcloud_compute_os-config_patch-jobs_execute -l dry-run
complete -c gcloud_compute_os-config_patch-jobs_execute -l duration
complete -c gcloud_compute_os-config_patch-jobs_execute -l reboot-config
complete -c gcloud_compute_os-config_patch-jobs_execute -l apt-dist
complete -c gcloud_compute_os-config_patch-jobs_execute -l apt-excludes
complete -c gcloud_compute_os-config_patch-jobs_execute -l apt-exclusive-packages
complete -c gcloud_compute_os-config_patch-jobs_execute -l post-patch-linux-success-codes
complete -c gcloud_compute_os-config_patch-jobs_execute -o NonInteractive -o NoProfile -o ExecutionPolicy
complete -c gcloud_compute_os-config_patch-jobs_execute -l post-patch-windows-success-codes
complete -c gcloud_compute_os-config_patch-jobs_execute -l pre-patch-windows-success-codes
complete -c gcloud_compute_os-config_patch-jobs_execute -l rollout-disruption-budget
complete -c gcloud_compute_os-config_patch-jobs_execute -l windows-excludes
complete -c gcloud_compute_os-config_patch-jobs_execute -l yum-exclusive-packages
complete -c gcloud_compute_os-config_patch-jobs_execute -l yum-excludes
complete -c gcloud_compute_os-config_patch-jobs_execute -l exclude
complete -c gcloud_compute_os-config_patch-jobs_execute -l yum-minimal
complete -c gcloud_compute_os-config_patch-jobs_execute -l yum-security
complete -c gcloud_compute_os-config_patch-jobs_execute -l zypper-exclusive-patches
complete -c gcloud_compute_os-config_patch-jobs_execute -l zypper-categories
complete -c gcloud_compute_os-config_patch-jobs_execute -l zypper-severities
complete -c gcloud_compute_os-config_patch-jobs_execute -l zypper-with-optional
complete -c gcloud_compute_os-config_patch-jobs_execute -l zypper-with-update
complete -c gcloud_compute_os-config_patch-jobs_execute -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_os-config_patch-jobs_execute -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_os-config_patch-jobs_execute -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_os-config_patch-jobs_execute -l verbosity

