# gcloud_privateca_roots_undelete
# Autogenerated from man page /usr/share/man/man1/gcloud_privateca_roots_undelete.1.gz
complete -c gcloud_privateca_roots_undelete -l location
complete -c gcloud_privateca_roots_undelete -l pool
complete -c gcloud_privateca_roots_undelete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_privateca_roots_undelete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_privateca_roots_undelete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_privateca_roots_undelete -l verbosity

