# gcloud_compute_os-login_ssh-keys_add
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_os-login_ssh-keys_add.1.gz
complete -c gcloud_compute_os-login_ssh-keys_add -l key
complete -c gcloud_compute_os-login_ssh-keys_add -l key-file
complete -c gcloud_compute_os-login_ssh-keys_add -l ttl
complete -c gcloud_compute_os-login_ssh-keys_add -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_os-login_ssh-keys_add -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_os-login_ssh-keys_add -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_os-login_ssh-keys_add -l verbosity

