# gcloud_beta_pubsub_lite-topics_list-subscriptions
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_pubsub_lite-topics_list-subscriptions.1.gz
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l location
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l filter
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l sort-by -l limit
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l page-size
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_pubsub_lite-topics_list-subscriptions -l verbosity

