# gcloud_composer_environments_storage_plugins_import
# Autogenerated from man page /usr/share/man/man1/gcloud_composer_environments_storage_plugins_import.1.gz
complete -c gcloud_composer_environments_storage_plugins_import -l source
complete -c gcloud_composer_environments_storage_plugins_import -l environment
complete -c gcloud_composer_environments_storage_plugins_import -l location
complete -c gcloud_composer_environments_storage_plugins_import -l destination
complete -c gcloud_composer_environments_storage_plugins_import -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_composer_environments_storage_plugins_import -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_composer_environments_storage_plugins_import -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_composer_environments_storage_plugins_import -l verbosity

