# gcloud_compute_reset-windows-password
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_reset-windows-password.1.gz
complete -c gcloud_compute_reset-windows-password -l user
complete -c gcloud_compute_reset-windows-password -l zone
complete -c gcloud_compute_reset-windows-password -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_reset-windows-password -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_reset-windows-password -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_reset-windows-password -l verbosity

