# gcloud_alpha_compute_reservations_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_reservations_create.1.gz
complete -c gcloud_alpha_compute_reservations_create -l machine-type
complete -c gcloud_alpha_compute_reservations_create -l vm-count
complete -c gcloud_alpha_compute_reservations_create -l accelerator
complete -c gcloud_alpha_compute_reservations_create -l local-ssd
complete -c gcloud_alpha_compute_reservations_create -l maintenance-freeze-duration
complete -c gcloud_alpha_compute_reservations_create -l maintenance-interval
complete -c gcloud_alpha_compute_reservations_create -l min-cpu-platform
complete -c gcloud_alpha_compute_reservations_create -l require-specific-reservation
complete -c gcloud_alpha_compute_reservations_create -l reservation-affinity -d 'OPTIONAL FLAGS'
complete -c gcloud_alpha_compute_reservations_create -l description
complete -c gcloud_alpha_compute_reservations_create -l zone
complete -c gcloud_alpha_compute_reservations_create -l share-setting
complete -c gcloud_alpha_compute_reservations_create -l share-with
complete -c gcloud_alpha_compute_reservations_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_reservations_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_reservations_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_reservations_create -l verbosity

