# gcloud_ml-engine_versions_update
# Autogenerated from man page /usr/share/man/man1/gcloud_ml-engine_versions_update.1.gz
complete -c gcloud_ml-engine_versions_update -l model
complete -c gcloud_ml-engine_versions_update -l config
complete -c gcloud_ml-engine_versions_update -l description
complete -c gcloud_ml-engine_versions_update -l region
complete -c gcloud_ml-engine_versions_update -l update-labels
complete -c gcloud_ml-engine_versions_update -l clear-labels
complete -c gcloud_ml-engine_versions_update -l remove-labels
complete -c gcloud_ml-engine_versions_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_ml-engine_versions_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_ml-engine_versions_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_ml-engine_versions_update -l verbosity

