# gcloud_beta_data-catalog_entries_lookup
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_data-catalog_entries_lookup.1.gz
complete -c gcloud_beta_data-catalog_entries_lookup -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_data-catalog_entries_lookup -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_data-catalog_entries_lookup -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_data-catalog_entries_lookup -l verbosity

