# gcloud_beta_compute_networks_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_networks_create.1.gz
complete -c gcloud_beta_compute_networks_create -l bgp-routing-mode
complete -c gcloud_beta_compute_networks_create -l description
complete -c gcloud_beta_compute_networks_create -l mtu
complete -c gcloud_beta_compute_networks_create -l range
complete -c gcloud_beta_compute_networks_create -l subnet-mode
complete -c gcloud_beta_compute_networks_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_networks_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_networks_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_networks_create -l verbosity

