# gcloud_alpha_ai_endpoints_predict
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ai_endpoints_predict.1.gz
complete -c gcloud_alpha_ai_endpoints_predict -l json-request -d 'POSITIONAL ARGUMENTS Endpoint resource - The endpoint to do online prediction'
complete -c gcloud_alpha_ai_endpoints_predict -l region
complete -c gcloud_alpha_ai_endpoints_predict -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ai_endpoints_predict -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ai_endpoints_predict -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ai_endpoints_predict -l verbosity

