# gcloud_beta_run_revisions
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_run_revisions.1.gz
complete -c gcloud_beta_run_revisions -l platform
complete -c gcloud_beta_run_revisions -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_run_revisions -l region
complete -c gcloud_beta_run_revisions -l cluster
complete -c gcloud_beta_run_revisions -l context
complete -c gcloud_beta_run_revisions -l kubeconfig

