# gcloud_beta_compute_security-policies_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_security-policies_create.1.gz
complete -c gcloud_beta_compute_security-policies_create -l description
complete -c gcloud_beta_compute_security-policies_create -l file-format
complete -c gcloud_beta_compute_security-policies_create -l file-name -d 'yaml.  Creation options'
complete -c gcloud_beta_compute_security-policies_create -l type
complete -c gcloud_beta_compute_security-policies_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_security-policies_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_security-policies_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_security-policies_create -l verbosity

