# gcloud_pubsub_lite-reservations_list-topics
# Autogenerated from man page /usr/share/man/man1/gcloud_pubsub_lite-reservations_list-topics.1.gz
complete -c gcloud_pubsub_lite-reservations_list-topics -l location
complete -c gcloud_pubsub_lite-reservations_list-topics -l filter
complete -c gcloud_pubsub_lite-reservations_list-topics -l sort-by -l limit
complete -c gcloud_pubsub_lite-reservations_list-topics -l page-size
complete -c gcloud_pubsub_lite-reservations_list-topics -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_pubsub_lite-reservations_list-topics -l billing-project -l configuration -l flags-file
complete -c gcloud_pubsub_lite-reservations_list-topics -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_pubsub_lite-reservations_list-topics -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_pubsub_lite-reservations_list-topics -l verbosity

