# gcloud_tasks_create-http-task
# Autogenerated from man page /usr/share/man/man1/gcloud_tasks_create-http-task.1.gz
complete -c gcloud_tasks_create-http-task -l queue
complete -c gcloud_tasks_create-http-task -l url
complete -c gcloud_tasks_create-http-task -l header
complete -c gcloud_tasks_create-http-task -l location
complete -c gcloud_tasks_create-http-task -l method
complete -c gcloud_tasks_create-http-task -l schedule-time
complete -c gcloud_tasks_create-http-task -l body-content
complete -c gcloud_tasks_create-http-task -l body-file
complete -c gcloud_tasks_create-http-task -l oauth-service-account-email
complete -c gcloud_tasks_create-http-task -l oauth-token-scope
complete -c gcloud_tasks_create-http-task -l oidc-service-account-email
complete -c gcloud_tasks_create-http-task -l oidc-token-audience
complete -c gcloud_tasks_create-http-task -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_tasks_create-http-task -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_tasks_create-http-task -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_tasks_create-http-task -l verbosity

