# gcloud_alpha_compute_scp
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_scp.1.gz
complete -c gcloud_alpha_compute_scp -l plain -l tunnel-through-iap -d 'file names must be prefixed with the remote IP address instead of the instanc…'
complete -c gcloud_alpha_compute_scp -l zone -d '$ gcloud alpha compute scp --recurse example-instance:~/narnia \\     ~/wardro…'
complete -c gcloud_alpha_compute_scp -l compress
complete -c gcloud_alpha_compute_scp -l dry-run
complete -c gcloud_alpha_compute_scp -l force-key-file-overwrite
complete -c gcloud_alpha_compute_scp -l port
complete -c gcloud_alpha_compute_scp -l recurse
complete -c gcloud_alpha_compute_scp -l scp-flag
complete -c gcloud_alpha_compute_scp -l ssh-key-file
complete -c gcloud_alpha_compute_scp -l strict-host-key-checking
complete -c gcloud_alpha_compute_scp -l internal-ip
complete -c gcloud_alpha_compute_scp -l network
complete -c gcloud_alpha_compute_scp -l region
complete -c gcloud_alpha_compute_scp -l ssh-key-expiration
complete -c gcloud_alpha_compute_scp -l ssh-key-expire-after
complete -c gcloud_alpha_compute_scp -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_scp -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_scp -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_scp -l verbosity

