# gcloud_alpha_asset_query
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_asset_query.1.gz
complete -c gcloud_alpha_asset_query -l folder
complete -c gcloud_alpha_asset_query -l organization
complete -c gcloud_alpha_asset_query -l project
complete -c gcloud_alpha_asset_query -l job-reference
complete -c gcloud_alpha_asset_query -l page-size
complete -c gcloud_alpha_asset_query -l page-token
complete -c gcloud_alpha_asset_query -l statement
complete -c gcloud_alpha_asset_query -l job-referrence
complete -c gcloud_alpha_asset_query -l timeout
complete -c gcloud_alpha_asset_query -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_asset_query -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_asset_query -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_asset_query -l verbosity

