# gcloud_compute_network-endpoint-groups_update
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_network-endpoint-groups_update.1.gz
complete -c gcloud_compute_network-endpoint-groups_update -l add-endpoint
complete -c gcloud_compute_network-endpoint-groups_update -l remove-endpoint
complete -c gcloud_compute_network-endpoint-groups_update -l global
complete -c gcloud_compute_network-endpoint-groups_update -l zone
complete -c gcloud_compute_network-endpoint-groups_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_network-endpoint-groups_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_network-endpoint-groups_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_network-endpoint-groups_update -l verbosity

