# gcloud_alpha_compute_instances_os-inventory_list-instances
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_instances_os-inventory_list-instances.1.gz
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l inventory-filter -l uri -d 'To list the URIs of all instances whose OS short name is equal to rhel, run: …'
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l os-shortname -d 'To list all instances with package google-cloud-sdk of version 235. 0'
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l package-name
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l package-version -d 'To list all instances with package name matching a regex ^google-cloud availa…'
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l kernel-version
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l os-version
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l filter
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l sort-by -l limit
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l page-size
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l flatten
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_instances_os-inventory_list-instances -l verbosity

