# gcloud_data-catalog_tags_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_data-catalog_tags_delete.1.gz
complete -c gcloud_data-catalog_tags_delete -l entry
complete -c gcloud_data-catalog_tags_delete -l entry-group
complete -c gcloud_data-catalog_tags_delete -l location
complete -c gcloud_data-catalog_tags_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_data-catalog_tags_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_data-catalog_tags_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_data-catalog_tags_delete -l verbosity

