# gcloud_alpha_data-catalog_tags_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_data-catalog_tags_create.1.gz
complete -c gcloud_alpha_data-catalog_tags_create -l tag-file
complete -c gcloud_alpha_data-catalog_tags_create -l entry
complete -c gcloud_alpha_data-catalog_tags_create -l entry-group
complete -c gcloud_alpha_data-catalog_tags_create -l location
complete -c gcloud_alpha_data-catalog_tags_create -l tag-template
complete -c gcloud_alpha_data-catalog_tags_create -l tag-template-location
complete -c gcloud_alpha_data-catalog_tags_create -l tag-template-project
complete -c gcloud_alpha_data-catalog_tags_create -l scope
complete -c gcloud_alpha_data-catalog_tags_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_data-catalog_tags_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_data-catalog_tags_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_data-catalog_tags_create -l verbosity

