# gcloud_alpha_ml_speech_recognize
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ml_speech_recognize.1.gz
complete -c gcloud_alpha_ml_speech_recognize -l language-code
complete -c gcloud_alpha_ml_speech_recognize -l additional-language-codes
complete -c gcloud_alpha_ml_speech_recognize -l enable-automatic-punctuation
complete -c gcloud_alpha_ml_speech_recognize -l encoding
complete -c gcloud_alpha_ml_speech_recognize -l filter-profanity
complete -c gcloud_alpha_ml_speech_recognize -l hints
complete -c gcloud_alpha_ml_speech_recognize -l include-word-confidence
complete -c gcloud_alpha_ml_speech_recognize -l include-word-time-offsets
complete -c gcloud_alpha_ml_speech_recognize -l max-alternatives
complete -c gcloud_alpha_ml_speech_recognize -l sample-rate
complete -c gcloud_alpha_ml_speech_recognize -l audio-channel-count
complete -c gcloud_alpha_ml_speech_recognize -l separate-channel-recognition
complete -c gcloud_alpha_ml_speech_recognize -l audio-topic
complete -c gcloud_alpha_ml_speech_recognize -l interaction-type
complete -c gcloud_alpha_ml_speech_recognize -l microphone-distance
complete -c gcloud_alpha_ml_speech_recognize -l naics-code
complete -c gcloud_alpha_ml_speech_recognize -l original-media-type
complete -c gcloud_alpha_ml_speech_recognize -l original-mime-type
complete -c gcloud_alpha_ml_speech_recognize -l recording-device-name
complete -c gcloud_alpha_ml_speech_recognize -l recording-device-type
complete -c gcloud_alpha_ml_speech_recognize -l enable-speaker-diarization
complete -c gcloud_alpha_ml_speech_recognize -l diarization-speaker-count
complete -c gcloud_alpha_ml_speech_recognize -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ml_speech_recognize -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ml_speech_recognize -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ml_speech_recognize -l verbosity

