# gcloud_beta_app_services_set-traffic
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_app_services_set-traffic.1.gz
complete -c gcloud_beta_app_services_set-traffic -l splits
complete -c gcloud_beta_app_services_set-traffic -l migrate
complete -c gcloud_beta_app_services_set-traffic -l split-by
complete -c gcloud_beta_app_services_set-traffic -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_app_services_set-traffic -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_app_services_set-traffic -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_app_services_set-traffic -l verbosity

