# gcloud_alpha_ai_tensorboard-time-series_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ai_tensorboard-time-series_update.1.gz
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l region
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l tensorboard-experiment-id
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l tensorboard-id
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l tensorboard-run-id
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l description
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l display-name
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l plugin-data
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l plugin-name
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ai_tensorboard-time-series_update -l verbosity

