# gcloud_compute_security-policies_rules_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_security-policies_rules_create.1.gz
complete -c gcloud_compute_security-policies_rules_create -l action
complete -c gcloud_compute_security-policies_rules_create -l expression
complete -c gcloud_compute_security-policies_rules_create -l src-ip-ranges
complete -c gcloud_compute_security-policies_rules_create -l description
complete -c gcloud_compute_security-policies_rules_create -l preview
complete -c gcloud_compute_security-policies_rules_create -l security-policy
complete -c gcloud_compute_security-policies_rules_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_security-policies_rules_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_security-policies_rules_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_security-policies_rules_create -l verbosity

