# gcloud_beta_builds_triggers_create_github
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_builds_triggers_create_github.1.gz
complete -c gcloud_beta_builds_triggers_create_github -l trigger-config
complete -c gcloud_beta_builds_triggers_create_github -l repo-name
complete -c gcloud_beta_builds_triggers_create_github -l repo-owner
complete -c gcloud_beta_builds_triggers_create_github -l description
complete -c gcloud_beta_builds_triggers_create_github -l ignored-files
complete -c gcloud_beta_builds_triggers_create_github -l included-files
complete -c gcloud_beta_builds_triggers_create_github -l name
complete -c gcloud_beta_builds_triggers_create_github -l require-approval
complete -c gcloud_beta_builds_triggers_create_github -l service-account
complete -c gcloud_beta_builds_triggers_create_github -l substitutions
complete -c gcloud_beta_builds_triggers_create_github -l branch-pattern
complete -c gcloud_beta_builds_triggers_create_github -l tag-pattern
complete -c gcloud_beta_builds_triggers_create_github -l pull-request-pattern
complete -c gcloud_beta_builds_triggers_create_github -l comment-control
complete -c gcloud_beta_builds_triggers_create_github -l build-config
complete -c gcloud_beta_builds_triggers_create_github -l inline-config
complete -c gcloud_beta_builds_triggers_create_github -l dockerfile
complete -c gcloud_beta_builds_triggers_create_github -l dockerfile-dir
complete -c gcloud_beta_builds_triggers_create_github -l dockerfile-image
complete -c gcloud_beta_builds_triggers_create_github -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_builds_triggers_create_github -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_builds_triggers_create_github -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_builds_triggers_create_github -l verbosity

