# gcloud_beta_healthcare_fhir-stores_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_healthcare_fhir-stores_describe.1.gz
complete -c gcloud_beta_healthcare_fhir-stores_describe -l dataset
complete -c gcloud_beta_healthcare_fhir-stores_describe -l location
complete -c gcloud_beta_healthcare_fhir-stores_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_healthcare_fhir-stores_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_healthcare_fhir-stores_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_healthcare_fhir-stores_describe -l verbosity

