# gcloud_beta_sql_ssl-certs_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_sql_ssl-certs_delete.1.gz
complete -c gcloud_beta_sql_ssl-certs_delete -l instance -s i
complete -c gcloud_beta_sql_ssl-certs_delete -l async
complete -c gcloud_beta_sql_ssl-certs_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_sql_ssl-certs_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_sql_ssl-certs_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_sql_ssl-certs_delete -l verbosity

