# gcloud_alpha_access-context-manager_levels_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_access-context-manager_levels_create.1.gz
complete -c gcloud_alpha_access-context-manager_levels_create -l policy
complete -c gcloud_alpha_access-context-manager_levels_create -l title
complete -c gcloud_alpha_access-context-manager_levels_create -l custom-level-spec
complete -c gcloud_alpha_access-context-manager_levels_create -l basic-level-spec
complete -c gcloud_alpha_access-context-manager_levels_create -l combine-function
complete -c gcloud_alpha_access-context-manager_levels_create -l async
complete -c gcloud_alpha_access-context-manager_levels_create -l description
complete -c gcloud_alpha_access-context-manager_levels_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_access-context-manager_levels_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_access-context-manager_levels_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_access-context-manager_levels_create -l verbosity

