# gcloud_alpha_run_revisions_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_run_revisions_describe.1.gz
complete -c gcloud_alpha_run_revisions_describe -l namespace
complete -c gcloud_alpha_run_revisions_describe -l platform
complete -c gcloud_alpha_run_revisions_describe -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_alpha_run_revisions_describe -l region
complete -c gcloud_alpha_run_revisions_describe -l cluster
complete -c gcloud_alpha_run_revisions_describe -l context
complete -c gcloud_alpha_run_revisions_describe -l kubeconfig
complete -c gcloud_alpha_run_revisions_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_run_revisions_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_run_revisions_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_run_revisions_describe -l verbosity

