# gcloud_config_get-value
# Autogenerated from man page /usr/share/man/man1/gcloud_config_get-value.1.gz
complete -c gcloud_config_get-value -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_config_get-value -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_config_get-value -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_config_get-value -l verbosity
complete -c gcloud_config_get-value -l region -d 'to this value, if set.  ai_platform region'
complete -c gcloud_config_get-value -l zone -d 'this value, if set.  To see valid choices, run gcloud compute zones list'
complete -c gcloud_config_get-value -l location -d 'to this value, if set.  filestore location'
complete -c gcloud_config_get-value -l realm -d 'fall back to this value which envokes aggregated list from the backend'
complete -c gcloud_config_get-value -l dataset -d 'to this value, if set.  location'

