# gcloud_beta_workflows_executions_wait-last
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_workflows_executions_wait-last.1.gz
complete -c gcloud_beta_workflows_executions_wait-last -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_workflows_executions_wait-last -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_workflows_executions_wait-last -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_workflows_executions_wait-last -l verbosity

