# gcloud_alpha_trace_sinks_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_trace_sinks_update.1.gz
complete -c gcloud_alpha_trace_sinks_update -l project
complete -c gcloud_alpha_trace_sinks_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_trace_sinks_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_trace_sinks_update -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_trace_sinks_update -l verbosity

