# gcloud_alpha_scc_notifications_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_scc_notifications_update.1.gz
complete -c gcloud_alpha_scc_notifications_update -l description
complete -c gcloud_alpha_scc_notifications_update -l filter
complete -c gcloud_alpha_scc_notifications_update -l organization
complete -c gcloud_alpha_scc_notifications_update -l pubsub-topic
complete -c gcloud_alpha_scc_notifications_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_scc_notifications_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_scc_notifications_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_scc_notifications_update -l verbosity

