# gcloud_alpha_deployment-manager_deployments_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_deployment-manager_deployments_update.1.gz
complete -c gcloud_alpha_deployment-manager_deployments_update -l remove-labels -l description
complete -c gcloud_alpha_deployment-manager_deployments_update -l async
complete -c gcloud_alpha_deployment-manager_deployments_update -l create-policy
complete -c gcloud_alpha_deployment-manager_deployments_update -l credential
complete -c gcloud_alpha_deployment-manager_deployments_update -l delete-policy
complete -c gcloud_alpha_deployment-manager_deployments_update -l fingerprint
complete -c gcloud_alpha_deployment-manager_deployments_update -l preview
complete -c gcloud_alpha_deployment-manager_deployments_update -l properties
complete -c gcloud_alpha_deployment-manager_deployments_update -l update-labels
complete -c gcloud_alpha_deployment-manager_deployments_update -l composite-type
complete -c gcloud_alpha_deployment-manager_deployments_update -l config
complete -c gcloud_alpha_deployment-manager_deployments_update -l manifest-id
complete -c gcloud_alpha_deployment-manager_deployments_update -l template
complete -c gcloud_alpha_deployment-manager_deployments_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_deployment-manager_deployments_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_deployment-manager_deployments_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_deployment-manager_deployments_update -l verbosity

