# gcloud_alpha_asset_export
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_asset_export.1.gz
complete -c gcloud_alpha_asset_export -l folder
complete -c gcloud_alpha_asset_export -l organization
complete -c gcloud_alpha_asset_export -l project
complete -c gcloud_alpha_asset_export -l output-path
complete -c gcloud_alpha_asset_export -l output-path-prefix
complete -c gcloud_alpha_asset_export -l output-bigquery-force
complete -c gcloud_alpha_asset_export -l partition-key
complete -c gcloud_alpha_asset_export -l per-asset-type
complete -c gcloud_alpha_asset_export -l bigquery-table
complete -c gcloud_alpha_asset_export -l bigquery-dataset
complete -c gcloud_alpha_asset_export -l asset-types
complete -c gcloud_alpha_asset_export -l content-type
complete -c gcloud_alpha_asset_export -l relationship-types
complete -c gcloud_alpha_asset_export -l snapshot-time
complete -c gcloud_alpha_asset_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_asset_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_asset_export -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_asset_export -l verbosity

