# gcloud_spanner_databases_execute-sql
# Autogenerated from man page /usr/share/man/man1/gcloud_spanner_databases_execute-sql.1.gz
complete -c gcloud_spanner_databases_execute-sql -l instance
complete -c gcloud_spanner_databases_execute-sql -l sql
complete -c gcloud_spanner_databases_execute-sql -l enable-partitioned-dml
complete -c gcloud_spanner_databases_execute-sql -l query-mode
complete -c gcloud_spanner_databases_execute-sql -l timeout
complete -c gcloud_spanner_databases_execute-sql -l read-timestamp
complete -c gcloud_spanner_databases_execute-sql -l strong
complete -c gcloud_spanner_databases_execute-sql -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_spanner_databases_execute-sql -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_spanner_databases_execute-sql -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_spanner_databases_execute-sql -l verbosity

