# gcloud_compute_routers_add-interface
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_routers_add-interface.1.gz
complete -c gcloud_compute_routers_add-interface -l interface-name
complete -c gcloud_compute_routers_add-interface -l interconnect-attachment
complete -c gcloud_compute_routers_add-interface -l interconnect-attachment-region
complete -c gcloud_compute_routers_add-interface -l subnetwork
complete -c gcloud_compute_routers_add-interface -l subnetwork-region
complete -c gcloud_compute_routers_add-interface -l vpn-tunnel
complete -c gcloud_compute_routers_add-interface -l vpn-tunnel-region
complete -c gcloud_compute_routers_add-interface -l ip-address
complete -c gcloud_compute_routers_add-interface -l mask-length
complete -c gcloud_compute_routers_add-interface -l redundant-interface
complete -c gcloud_compute_routers_add-interface -l region
complete -c gcloud_compute_routers_add-interface -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_routers_add-interface -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_routers_add-interface -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_routers_add-interface -l verbosity

