# gcloud_alpha_database-migration_connection-profiles_create_cloudsql
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_database-migration_connection-profiles_create_cloudsql.1.gz
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l region
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l database-version
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l source-id
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l tier
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l activation-policy
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l authorized-networks
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l auto-storage-increase
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l data-disk-size
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l data-disk-type
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l database-flags
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l display-name
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l enable-ip-v4
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l labels
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l private-network
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l provider
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l require-ssl
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l storage-auto-resize-limit
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l user-labels
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l zone
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_database-migration_connection-profiles_create_cloudsql -l verbosity

