# gcloud_alpha_data-catalog_tag-templates_fields_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_data-catalog_tag-templates_fields_create.1.gz
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l location
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l tag-template
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l type
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l display-name
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_data-catalog_tag-templates_fields_create -l verbosity

