# gcloud_survey
# Autogenerated from man page /usr/share/man/man1/gcloud_survey.1.gz
complete -c gcloud_survey -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_survey -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_survey -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_survey -l verbosity

