# gcloud_beta_datastream_private-connections_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_datastream_private-connections_list.1.gz
complete -c gcloud_beta_datastream_private-connections_list -l location
complete -c gcloud_beta_datastream_private-connections_list -l filter
complete -c gcloud_beta_datastream_private-connections_list -l sort-by -l limit
complete -c gcloud_beta_datastream_private-connections_list -l page-size
complete -c gcloud_beta_datastream_private-connections_list -l flatten
complete -c gcloud_beta_datastream_private-connections_list -l uri
complete -c gcloud_beta_datastream_private-connections_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_datastream_private-connections_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_datastream_private-connections_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_datastream_private-connections_list -l verbosity

