# gcloud_beta_ml_vision_detect-product
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_ml_vision_detect-product.1.gz
complete -c gcloud_beta_ml_vision_detect-product -l category
complete -c gcloud_beta_ml_vision_detect-product -l product-set
complete -c gcloud_beta_ml_vision_detect-product -l product-set-location
complete -c gcloud_beta_ml_vision_detect-product -l bounding-polygon
complete -c gcloud_beta_ml_vision_detect-product -l filter
complete -c gcloud_beta_ml_vision_detect-product -l max-results
complete -c gcloud_beta_ml_vision_detect-product -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_ml_vision_detect-product -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_ml_vision_detect-product -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_ml_vision_detect-product -l verbosity

