# gcloud_run_services_list
# Autogenerated from man page /usr/share/man/man1/gcloud_run_services_list.1.gz
complete -c gcloud_run_services_list -l platform -d 'Namespace resource - Namespace to list services in'
complete -c gcloud_run_services_list -l namespace
complete -c gcloud_run_services_list -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_run_services_list -l region
complete -c gcloud_run_services_list -l cluster
complete -c gcloud_run_services_list -l context
complete -c gcloud_run_services_list -l kubeconfig
complete -c gcloud_run_services_list -l filter
complete -c gcloud_run_services_list -l sort-by -l limit
complete -c gcloud_run_services_list -l page-size
complete -c gcloud_run_services_list -l flatten
complete -c gcloud_run_services_list -l uri
complete -c gcloud_run_services_list -l billing-project -l configuration -l flags-file
complete -c gcloud_run_services_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_run_services_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_run_services_list -l verbosity

