# gcloud_compute_url-maps_add-host-rule
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_url-maps_add-host-rule.1.gz
complete -c gcloud_compute_url-maps_add-host-rule -l hosts
complete -c gcloud_compute_url-maps_add-host-rule -l path-matcher-name
complete -c gcloud_compute_url-maps_add-host-rule -l description
complete -c gcloud_compute_url-maps_add-host-rule -l global
complete -c gcloud_compute_url-maps_add-host-rule -l region
complete -c gcloud_compute_url-maps_add-host-rule -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_url-maps_add-host-rule -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_url-maps_add-host-rule -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_url-maps_add-host-rule -l verbosity

