# gcloud_compute_interconnects_attachments_dedicated_update
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_interconnects_attachments_dedicated_update.1.gz
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l bandwidth
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l description
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l enable-admin
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l mtu
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l region
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_interconnects_attachments_dedicated_update -l verbosity

