# gcloud_container_node-pools_create
# Autogenerated from man page /usr/share/man/man1/gcloud_container_node-pools_create.1.gz
complete -c gcloud_container_node-pools_create -l accelerator
complete -c gcloud_container_node-pools_create -l boot-disk-kms-key
complete -c gcloud_container_node-pools_create -l cluster
complete -c gcloud_container_node-pools_create -l disk-size
complete -c gcloud_container_node-pools_create -l disk-type
complete -c gcloud_container_node-pools_create -l enable-autoprovisioning
complete -c gcloud_container_node-pools_create -l enable-autorepair
complete -c gcloud_container_node-pools_create -l enable-autoupgrade
complete -c gcloud_container_node-pools_create -l enable-gvnic
complete -c gcloud_container_node-pools_create -l enable-image-streaming
complete -c gcloud_container_node-pools_create -l image-type
complete -c gcloud_container_node-pools_create -l local-ssd-count
complete -c gcloud_container_node-pools_create -l machine-type -s m
complete -c gcloud_container_node-pools_create -l max-pods-per-node
complete -c gcloud_container_node-pools_create -l max-surge-upgrade
complete -c gcloud_container_node-pools_create -l max-unavailable-upgrade
complete -c gcloud_container_node-pools_create -l metadata
complete -c gcloud_container_node-pools_create -l metadata-from-file
complete -c gcloud_container_node-pools_create -l min-cpu-platform
complete -c gcloud_container_node-pools_create -l node-group
complete -c gcloud_container_node-pools_create -l node-labels
complete -c gcloud_container_node-pools_create -l node-locations
complete -c gcloud_container_node-pools_create -l node-taints
complete -c gcloud_container_node-pools_create -l node-version
complete -c gcloud_container_node-pools_create -l num-nodes
complete -c gcloud_container_node-pools_create -l preemptible
complete -c gcloud_container_node-pools_create -l sandbox
complete -c gcloud_container_node-pools_create -l shielded-integrity-monitoring
complete -c gcloud_container_node-pools_create -l shielded-secure-boot
complete -c gcloud_container_node-pools_create -l system-config-from-file
complete -c gcloud_container_node-pools_create -l tags
complete -c gcloud_container_node-pools_create -l threads-per-core
complete -c gcloud_container_node-pools_create -l workload-metadata
complete -c gcloud_container_node-pools_create -l create-pod-ipv4-range
complete -c gcloud_container_node-pools_create -l pod-ipv4-range
complete -c gcloud_container_node-pools_create -l create-ipv4-pod-range
complete -c gcloud_container_node-pools_create -l enable-autoscaling
complete -c gcloud_container_node-pools_create -l max-nodes
complete -c gcloud_container_node-pools_create -l node-pool
complete -c gcloud_container_node-pools_create -l min-nodes
complete -c gcloud_container_node-pools_create -l region
complete -c gcloud_container_node-pools_create -l zone -s z
complete -c gcloud_container_node-pools_create -l reservation
complete -c gcloud_container_node-pools_create -l reservation-affinity
complete -c gcloud_container_node-pools_create -l scopes
complete -c gcloud_container_node-pools_create -l enable-cloud-monitoring -d 'the full URI of the scope or an alias'
complete -c gcloud_container_node-pools_create -l service-account
complete -c gcloud_container_node-pools_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_container_node-pools_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_container_node-pools_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_container_node-pools_create -l verbosity

