# gcloud_alpha_emulators_pubsub_start
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_emulators_pubsub_start.1.gz
complete -c gcloud_alpha_emulators_pubsub_start -l data-dir
complete -c gcloud_alpha_emulators_pubsub_start -l host-port
complete -c gcloud_alpha_emulators_pubsub_start -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_emulators_pubsub_start -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_emulators_pubsub_start -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_emulators_pubsub_start -l verbosity

