# gcloud_database-migration_connection-profiles_create_postgresql
# Autogenerated from man page /usr/share/man/man1/gcloud_database-migration_connection-profiles_create_postgresql.1.gz
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l region
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l host
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l port
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l username
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l password
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l prompt-for-password
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l cloudsql-instance
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l display-name
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l labels
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l ca-certificate
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l client-certificate
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l private-key
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_database-migration_connection-profiles_create_postgresql -l verbosity

