# gcloud_domains_registrations_configure_dns
# Autogenerated from man page /usr/share/man/man1/gcloud_domains_registrations_configure_dns.1.gz
complete -c gcloud_domains_registrations_configure_dns -l validate-only
complete -c gcloud_domains_registrations_configure_dns -l disable-dnssec -d 'name servers.  Otherwise your domain may stop serving'
complete -c gcloud_domains_registrations_configure_dns -l cloud-dns-zone
complete -c gcloud_domains_registrations_configure_dns -l dns-settings-from-file
complete -c gcloud_domains_registrations_configure_dns -l name-servers
complete -c gcloud_domains_registrations_configure_dns -l use-google-domains-dns
complete -c gcloud_domains_registrations_configure_dns -l async
complete -c gcloud_domains_registrations_configure_dns -l unsafe-dns-update
complete -c gcloud_domains_registrations_configure_dns -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_domains_registrations_configure_dns -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_domains_registrations_configure_dns -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_domains_registrations_configure_dns -l verbosity

