# gcloud_alpha_compute_future-reservations_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_future-reservations_update.1.gz
complete -c gcloud_alpha_compute_future-reservations_update -l end-time -l zone -d 'POSITIONAL ARGUMENTS FUTURE_RESERVATION'
complete -c gcloud_alpha_compute_future-reservations_update -l start-time
complete -c gcloud_alpha_compute_future-reservations_update -l total-count
complete -c gcloud_alpha_compute_future-reservations_update -l duration
complete -c gcloud_alpha_compute_future-reservations_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_future-reservations_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_future-reservations_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_future-reservations_update -l verbosity

