# gcloud_beta_game_servers_deployments_describe-rollout
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_game_servers_deployments_describe-rollout.1.gz
complete -c gcloud_beta_game_servers_deployments_describe-rollout -l location
complete -c gcloud_beta_game_servers_deployments_describe-rollout -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_game_servers_deployments_describe-rollout -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_game_servers_deployments_describe-rollout -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_game_servers_deployments_describe-rollout -l verbosity

