# gcloud_logging_buckets_update
# Autogenerated from man page /usr/share/man/man1/gcloud_logging_buckets_update.1.gz
complete -c gcloud_logging_buckets_update -l location
complete -c gcloud_logging_buckets_update -l description
complete -c gcloud_logging_buckets_update -l locked
complete -c gcloud_logging_buckets_update -l restricted-fields
complete -c gcloud_logging_buckets_update -l retention-days
complete -c gcloud_logging_buckets_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_logging_buckets_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_logging_buckets_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_logging_buckets_update -l verbosity

