# gcloud_alpha_compute_project-info_remove-metadata
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_project-info_remove-metadata.1.gz
complete -c gcloud_alpha_compute_project-info_remove-metadata -l all
complete -c gcloud_alpha_compute_project-info_remove-metadata -l keys
complete -c gcloud_alpha_compute_project-info_remove-metadata -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_project-info_remove-metadata -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_project-info_remove-metadata -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_project-info_remove-metadata -l verbosity

