# gcloud_beta_compute_connect-to-serial-port
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_connect-to-serial-port.1.gz
complete -c gcloud_beta_compute_connect-to-serial-port -l dry-run
complete -c gcloud_beta_compute_connect-to-serial-port -l extra-args
complete -c gcloud_beta_compute_connect-to-serial-port -l force-key-file-overwrite
complete -c gcloud_beta_compute_connect-to-serial-port -l port
complete -c gcloud_beta_compute_connect-to-serial-port -l ssh-key-file
complete -c gcloud_beta_compute_connect-to-serial-port -l zone
complete -c gcloud_beta_compute_connect-to-serial-port -l ssh-key-expiration
complete -c gcloud_beta_compute_connect-to-serial-port -l ssh-key-expire-after
complete -c gcloud_beta_compute_connect-to-serial-port -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_connect-to-serial-port -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_connect-to-serial-port -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_connect-to-serial-port -l verbosity

