# gcloud_alpha_compute_backend-services_add-service-bindings
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_backend-services_add-service-bindings.1.gz
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l service-bindings
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l global
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l region
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_backend-services_add-service-bindings -l verbosity

