# gcloud_compute_forwarding-rules_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_forwarding-rules_create.1.gz
complete -c gcloud_compute_forwarding-rules_create -l global -l region -d 'information about the scope of a forwarding rule, refer to https://cloud'
complete -c gcloud_compute_forwarding-rules_create -l load-balancing-scheme -d flag
complete -c gcloud_compute_forwarding-rules_create -l address -d 'flag is unspecified, an ephemeral IP address is automatically assigned (globa…'
complete -c gcloud_compute_forwarding-rules_create -l subnet -d 'self-managed forwarding rule'
complete -c gcloud_compute_forwarding-rules_create -l target-instance -l target-pool
complete -c gcloud_compute_forwarding-rules_create -l target-http-proxy -l target-https-proxy
complete -c gcloud_compute_forwarding-rules_create -l target-grpc-proxy -l target-ssl-proxy
complete -c gcloud_compute_forwarding-rules_create -l target-tcp-proxy -l target-vpn-gateway
complete -c gcloud_compute_forwarding-rules_create -l backend-service -l target-google-apis-bundle -d 'must be specified.  EXAMPLES'
complete -c gcloud_compute_forwarding-rules_create -l target-service-attachment
complete -c gcloud_compute_forwarding-rules_create -l ports -d '1883, 5222'
complete -c gcloud_compute_forwarding-rules_create -l allow-global-access
complete -c gcloud_compute_forwarding-rules_create -l description
complete -c gcloud_compute_forwarding-rules_create -l ip-protocol
complete -c gcloud_compute_forwarding-rules_create -l is-mirroring-collector
complete -c gcloud_compute_forwarding-rules_create -l network
complete -c gcloud_compute_forwarding-rules_create -l network-tier
complete -c gcloud_compute_forwarding-rules_create -l service-directory-registration
complete -c gcloud_compute_forwarding-rules_create -l service-label
complete -c gcloud_compute_forwarding-rules_create -l purpose
complete -c gcloud_compute_forwarding-rules_create -l subnet-region
complete -c gcloud_compute_forwarding-rules_create -l target-instance-zone
complete -c gcloud_compute_forwarding-rules_create -l target-pool-region
complete -c gcloud_compute_forwarding-rules_create -l target-service-attachment-region
complete -c gcloud_compute_forwarding-rules_create -l target-vpn-gateway-region
complete -c gcloud_compute_forwarding-rules_create -l ip-version
complete -c gcloud_compute_forwarding-rules_create -l address-region
complete -c gcloud_compute_forwarding-rules_create -l global-address
complete -c gcloud_compute_forwarding-rules_create -l backend-service-region
complete -c gcloud_compute_forwarding-rules_create -l global-backend-service
complete -c gcloud_compute_forwarding-rules_create -l global-target-http-proxy
complete -c gcloud_compute_forwarding-rules_create -l target-http-proxy-region
complete -c gcloud_compute_forwarding-rules_create -l global-target-https-proxy
complete -c gcloud_compute_forwarding-rules_create -l target-https-proxy-region
complete -c gcloud_compute_forwarding-rules_create -l port-range
complete -c gcloud_compute_forwarding-rules_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_forwarding-rules_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_forwarding-rules_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_forwarding-rules_create -l verbosity

