# gcloud_components_reinstall
# Autogenerated from man page /usr/share/man/man1/gcloud_components_reinstall.1.gz
complete -c gcloud_components_reinstall -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_components_reinstall -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_components_reinstall -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_components_reinstall -l verbosity

