# gcloud_cloud-shell_scp
# Autogenerated from man page /usr/share/man/man1/gcloud_cloud-shell_scp.1.gz
complete -c gcloud_cloud-shell_scp -l dry-run
complete -c gcloud_cloud-shell_scp -l force-key-file-overwrite
complete -c gcloud_cloud-shell_scp -l recurse
complete -c gcloud_cloud-shell_scp -l scp-flag
complete -c gcloud_cloud-shell_scp -l ssh-key-file
complete -c gcloud_cloud-shell_scp -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_cloud-shell_scp -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_cloud-shell_scp -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_cloud-shell_scp -l verbosity

