# gcloud_alpha_container_aws_get-server-config
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_aws_get-server-config.1.gz
complete -c gcloud_alpha_container_aws_get-server-config -l location
complete -c gcloud_alpha_container_aws_get-server-config -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_aws_get-server-config -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_aws_get-server-config -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_aws_get-server-config -l verbosity

