# gcloud_cheat-sheet
# Autogenerated from man page /usr/share/man/man1/gcloud_cheat-sheet.1.gz
complete -c gcloud_cheat-sheet -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_cheat-sheet -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_cheat-sheet -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_cheat-sheet -l verbosity

