# gcloud_alpha_bq_tables_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_bq_tables_create.1.gz
complete -c gcloud_alpha_bq_tables_create -l dataset
complete -c gcloud_alpha_bq_tables_create -l description
complete -c gcloud_alpha_bq_tables_create -l expiration
complete -c gcloud_alpha_bq_tables_create -l overwrite
complete -c gcloud_alpha_bq_tables_create -l schema
complete -c gcloud_alpha_bq_tables_create -l schema-file
complete -c gcloud_alpha_bq_tables_create -l view
complete -c gcloud_alpha_bq_tables_create -l use-legacy-sql
complete -c gcloud_alpha_bq_tables_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_bq_tables_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_bq_tables_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_bq_tables_create -l verbosity

