# gcloud_config_configurations_activate
# Autogenerated from man page /usr/share/man/man1/gcloud_config_configurations_activate.1.gz
complete -c gcloud_config_configurations_activate -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_config_configurations_activate -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_config_configurations_activate -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_config_configurations_activate -l verbosity

