# gcloud_compute_instance-groups_managed_instance-configs_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_instance-groups_managed_instance-configs_delete.1.gz
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l no-update-instance -d EXAMPLES
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l instances
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l instance-update-minimal-action
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l update-instance -d 'INSTANCE_UPDATE_MINIMAL_ACTION must be one of: none No action'
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l region
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l zone
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_instance-groups_managed_instance-configs_delete -l verbosity

