# gcloud_privateca_roots_list
# Autogenerated from man page /usr/share/man/man1/gcloud_privateca_roots_list.1.gz
complete -c gcloud_privateca_roots_list -l location
complete -c gcloud_privateca_roots_list -l pool
complete -c gcloud_privateca_roots_list -l limit
complete -c gcloud_privateca_roots_list -l sort-by -l filter
complete -c gcloud_privateca_roots_list -l page-size
complete -c gcloud_privateca_roots_list -l flatten
complete -c gcloud_privateca_roots_list -l uri
complete -c gcloud_privateca_roots_list -l billing-project -l configuration -l flags-file
complete -c gcloud_privateca_roots_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_privateca_roots_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_privateca_roots_list -l verbosity

