# gcloud_compute_disks_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_disks_create.1.gz
complete -c gcloud_compute_disks_create -l image
complete -c gcloud_compute_disks_create -l csek-key-file
complete -c gcloud_compute_disks_create -l description
complete -c gcloud_compute_disks_create -l guest-os-features
complete -c gcloud_compute_disks_create -l labels
complete -c gcloud_compute_disks_create -l licenses
complete -c gcloud_compute_disks_create -l provisioned-iops
complete -c gcloud_compute_disks_create -l replica-zones
complete -c gcloud_compute_disks_create -l require-csek-key-create
complete -c gcloud_compute_disks_create -l resource-policies
complete -c gcloud_compute_disks_create -l size
complete -c gcloud_compute_disks_create -l type
complete -c gcloud_compute_disks_create -l image-family-scope
complete -c gcloud_compute_disks_create -l image-project
complete -c gcloud_compute_disks_create -l image-family
complete -c gcloud_compute_disks_create -l source-disk
complete -c gcloud_compute_disks_create -l source-snapshot
complete -c gcloud_compute_disks_create -l kms-key
complete -c gcloud_compute_disks_create -l kms-keyring
complete -c gcloud_compute_disks_create -l kms-location
complete -c gcloud_compute_disks_create -l kms-project
complete -c gcloud_compute_disks_create -l region
complete -c gcloud_compute_disks_create -l zone
complete -c gcloud_compute_disks_create -l source-disk-region
complete -c gcloud_compute_disks_create -l source-disk-zone
complete -c gcloud_compute_disks_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_disks_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_disks_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_disks_create -l verbosity

