# gcloud_alpha_active-directory_domains_trusts_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_active-directory_domains_trusts_update.1.gz
complete -c gcloud_alpha_active-directory_domains_trusts_update -l target-dns-ip-addresses -d 'POSITIONAL ARGUMENTS Domain resource - Name of the Managed Microsoft AD trust…'
complete -c gcloud_alpha_active-directory_domains_trusts_update -l target-domain-name
complete -c gcloud_alpha_active-directory_domains_trusts_update -l async
complete -c gcloud_alpha_active-directory_domains_trusts_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_active-directory_domains_trusts_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_active-directory_domains_trusts_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_active-directory_domains_trusts_update -l verbosity

