# gcloud_logging_views_update
# Autogenerated from man page /usr/share/man/man1/gcloud_logging_views_update.1.gz
complete -c gcloud_logging_views_update -l description -d 'POSITIONAL ARGUMENTS VIEW_ID'
complete -c gcloud_logging_views_update -l bucket
complete -c gcloud_logging_views_update -l location
complete -c gcloud_logging_views_update -l log-filter
complete -c gcloud_logging_views_update -l billing-account
complete -c gcloud_logging_views_update -l folder
complete -c gcloud_logging_views_update -l organization
complete -c gcloud_logging_views_update -l project
complete -c gcloud_logging_views_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_logging_views_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_logging_views_update -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_logging_views_update -l verbosity

