# gcloud_beta_identity_groups_memberships_check-transitive-membership
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_identity_groups_memberships_check-transitive-membership.1.gz
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l group-email
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l member-email
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_identity_groups_memberships_check-transitive-membership -l verbosity

