# gcloud_dataflow_jobs_show
# Autogenerated from man page /usr/share/man/man1/gcloud_dataflow_jobs_show.1.gz
complete -c gcloud_dataflow_jobs_show -l environment
complete -c gcloud_dataflow_jobs_show -l region
complete -c gcloud_dataflow_jobs_show -l steps
complete -c gcloud_dataflow_jobs_show -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dataflow_jobs_show -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dataflow_jobs_show -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dataflow_jobs_show -l verbosity

