# gcloud_beta_source_repos_clone
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_source_repos_clone.1.gz
complete -c gcloud_beta_source_repos_clone -l dry-run
complete -c gcloud_beta_source_repos_clone -l use-full-gcloud-path
complete -c gcloud_beta_source_repos_clone -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_source_repos_clone -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_source_repos_clone -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_source_repos_clone -l verbosity

