# gcloud_alpha_pubsub_lite-topics_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_pubsub_lite-topics_create.1.gz
complete -c gcloud_alpha_pubsub_lite-topics_create -l partitions
complete -c gcloud_alpha_pubsub_lite-topics_create -l per-partition-bytes
complete -c gcloud_alpha_pubsub_lite-topics_create -l location
complete -c gcloud_alpha_pubsub_lite-topics_create -l message-retention-period
complete -c gcloud_alpha_pubsub_lite-topics_create -l per-partition-publish-mib
complete -c gcloud_alpha_pubsub_lite-topics_create -l per-partition-subscribe-mib
complete -c gcloud_alpha_pubsub_lite-topics_create -l throughput-reservation
complete -c gcloud_alpha_pubsub_lite-topics_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_pubsub_lite-topics_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_pubsub_lite-topics_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_pubsub_lite-topics_create -l verbosity

