# gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update.1.gz
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l region
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l zone
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_instance-groups_managed_rolling-action_stop-proactive-update -l verbosity

