# gcloud_compute_security-policies_export
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_security-policies_export.1.gz
complete -c gcloud_compute_security-policies_export -l file-name
complete -c gcloud_compute_security-policies_export -l file-format
complete -c gcloud_compute_security-policies_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_security-policies_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_security-policies_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_security-policies_export -l verbosity

