# gcloud_iam_service-accounts_disable
# Autogenerated from man page /usr/share/man/man1/gcloud_iam_service-accounts_disable.1.gz
complete -c gcloud_iam_service-accounts_disable -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_iam_service-accounts_disable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_iam_service-accounts_disable -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_iam_service-accounts_disable -l verbosity

