# gcloud_resource-manager_org-policies_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_resource-manager_org-policies_delete.1.gz
complete -c gcloud_resource-manager_org-policies_delete -l folder
complete -c gcloud_resource-manager_org-policies_delete -l organization
complete -c gcloud_resource-manager_org-policies_delete -l project
complete -c gcloud_resource-manager_org-policies_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_resource-manager_org-policies_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_resource-manager_org-policies_delete -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_resource-manager_org-policies_delete -l verbosity

