# gcloud_recaptcha_keys_create
# Autogenerated from man page /usr/share/man/man1/gcloud_recaptcha_keys_create.1.gz
complete -c gcloud_recaptcha_keys_create -l display-name
complete -c gcloud_recaptcha_keys_create -l android
complete -c gcloud_recaptcha_keys_create -l allow-all-package-names
complete -c gcloud_recaptcha_keys_create -l package-names
complete -c gcloud_recaptcha_keys_create -l ios
complete -c gcloud_recaptcha_keys_create -l allow-all-bundle-ids
complete -c gcloud_recaptcha_keys_create -l bundle-ids
complete -c gcloud_recaptcha_keys_create -l web
complete -c gcloud_recaptcha_keys_create -l allow-amp-traffic
complete -c gcloud_recaptcha_keys_create -l integration-type
complete -c gcloud_recaptcha_keys_create -l security-preference
complete -c gcloud_recaptcha_keys_create -l testing-challenge
complete -c gcloud_recaptcha_keys_create -l allow-all-domains
complete -c gcloud_recaptcha_keys_create -l domains
complete -c gcloud_recaptcha_keys_create -l labels
complete -c gcloud_recaptcha_keys_create -l testing-score
complete -c gcloud_recaptcha_keys_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_recaptcha_keys_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_recaptcha_keys_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_recaptcha_keys_create -l verbosity

