# gcloud_beta_scc_assets_group
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_scc_assets_group.1.gz
complete -c gcloud_beta_scc_assets_group -l group-by -d 'Group assets that were updated on or after 2019-01-01T01:00:00 GMT by their t…'
complete -c gcloud_beta_scc_assets_group -l compare-duration
complete -c gcloud_beta_scc_assets_group -l filter
complete -c gcloud_beta_scc_assets_group -l page-size
complete -c gcloud_beta_scc_assets_group -l page-token
complete -c gcloud_beta_scc_assets_group -l read-time
complete -c gcloud_beta_scc_assets_group -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_scc_assets_group -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_scc_assets_group -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_scc_assets_group -l verbosity

