# gcloud_alpha_compute_instance-groups_managed_wait-until-stable
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_instance-groups_managed_wait-until-stable.1.gz
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l timeout
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l region
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l zone
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_instance-groups_managed_wait-until-stable -l verbosity

