# gcloud_topic_projections
# Autogenerated from man page /usr/share/man/man1/gcloud_topic_projections.1.gz
complete -c gcloud_topic_projections -l format
complete -c gcloud_topic_projections -l filter -d 'format and change the default output to a more meaningful result'

