# gcloud_alpha_logging_views_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_logging_views_describe.1.gz
complete -c gcloud_alpha_logging_views_describe -l bucket
complete -c gcloud_alpha_logging_views_describe -l location
complete -c gcloud_alpha_logging_views_describe -l billing-account
complete -c gcloud_alpha_logging_views_describe -l folder
complete -c gcloud_alpha_logging_views_describe -l organization
complete -c gcloud_alpha_logging_views_describe -l project
complete -c gcloud_alpha_logging_views_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_logging_views_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_logging_views_describe -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_logging_views_describe -l verbosity

