# gcloud_beta_tasks_queues_create-app-engine-queue
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_tasks_queues_create-app-engine-queue.1.gz
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l location
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l log-sampling-ratio
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-attempts
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-backoff
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-concurrent-dispatches
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-dispatches-per-second
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-doublings
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l max-retry-duration
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l min-backoff
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l routing-override
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_tasks_queues_create-app-engine-queue -l verbosity

