# gcloud_alpha_compute_ssl-policies_import
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_ssl-policies_import.1.gz
complete -c gcloud_alpha_compute_ssl-policies_import -l source
complete -c gcloud_alpha_compute_ssl-policies_import -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_ssl-policies_import -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_ssl-policies_import -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_ssl-policies_import -l verbosity

