# gcloud_beta_debug_logpoints_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_debug_logpoints_create.1.gz
complete -c gcloud_beta_debug_logpoints_create -l condition
complete -c gcloud_beta_debug_logpoints_create -l log-level
complete -c gcloud_beta_debug_logpoints_create -l target
complete -c gcloud_beta_debug_logpoints_create -l wait
complete -c gcloud_beta_debug_logpoints_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_debug_logpoints_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_debug_logpoints_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_debug_logpoints_create -l verbosity

