# gcloud_alpha_ai-platform_jobs_submit_training
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ai-platform_jobs_submit_training.1.gz
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l config
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l enable-web-access
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l job-dir
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l labels
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l master-accelerator
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l master-image-uri
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l runtime-version
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l master-machine-type
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l module-name
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l network
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l package-path
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l packages
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l parameter-server-accelerator
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l parameter-server-image-uri
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l python-version
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l region
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l scale-tier
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l service-account
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l staging-bucket
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l tpu-tf-version
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l use-chief-in-tf-config
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l worker-accelerator
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l worker-image-uri
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l async
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l stream-logs
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l kms-key
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l kms-keyring
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l kms-location
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l kms-project
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l parameter-server-count
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l parameter-server-machine-type
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l worker-count
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l worker-machine-type
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ai-platform_jobs_submit_training -l verbosity

