# gcloud_alpha_dataproc_jobs_submit
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dataproc_jobs_submit.1.gz
complete -c gcloud_alpha_dataproc_jobs_submit -l async
complete -c gcloud_alpha_dataproc_jobs_submit -l bucket
complete -c gcloud_alpha_dataproc_jobs_submit -l region

