# gcloud_resource-manager_org-policies_enable-enforce
# Autogenerated from man page /usr/share/man/man1/gcloud_resource-manager_org-policies_enable-enforce.1.gz
complete -c gcloud_resource-manager_org-policies_enable-enforce -l folder
complete -c gcloud_resource-manager_org-policies_enable-enforce -l organization
complete -c gcloud_resource-manager_org-policies_enable-enforce -l project
complete -c gcloud_resource-manager_org-policies_enable-enforce -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_resource-manager_org-policies_enable-enforce -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_resource-manager_org-policies_enable-enforce -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_resource-manager_org-policies_enable-enforce -l verbosity

