# gcloud_alpha_ids_endpoints_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ids_endpoints_create.1.gz
complete -c gcloud_alpha_ids_endpoints_create -l zone
complete -c gcloud_alpha_ids_endpoints_create -l network
complete -c gcloud_alpha_ids_endpoints_create -l severity
complete -c gcloud_alpha_ids_endpoints_create -l async
complete -c gcloud_alpha_ids_endpoints_create -l description
complete -c gcloud_alpha_ids_endpoints_create -l enable-traffic-logs
complete -c gcloud_alpha_ids_endpoints_create -l labels
complete -c gcloud_alpha_ids_endpoints_create -l max-wait
complete -c gcloud_alpha_ids_endpoints_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ids_endpoints_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ids_endpoints_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ids_endpoints_create -l verbosity

