# gcloud_alpha_recommender_recommender-configs_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_recommender_recommender-configs_describe.1.gz
complete -c gcloud_alpha_recommender_recommender-configs_describe -l location
complete -c gcloud_alpha_recommender_recommender-configs_describe -l project
complete -c gcloud_alpha_recommender_recommender-configs_describe -l recommender
complete -c gcloud_alpha_recommender_recommender-configs_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_recommender_recommender-configs_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_recommender_recommender-configs_describe -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_recommender_recommender-configs_describe -l verbosity

