# gcloud_beta_dns_managed-zones_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_dns_managed-zones_update.1.gz
complete -c gcloud_beta_dns_managed-zones_update -l async
complete -c gcloud_beta_dns_managed-zones_update -l denial-of-existence
complete -c gcloud_beta_dns_managed-zones_update -l description
complete -c gcloud_beta_dns_managed-zones_update -l dnssec-state
complete -c gcloud_beta_dns_managed-zones_update -l forwarding-targets
complete -c gcloud_beta_dns_managed-zones_update -l gkeclusters
complete -c gcloud_beta_dns_managed-zones_update -l ksk-algorithm
complete -c gcloud_beta_dns_managed-zones_update -l ksk-key-length
complete -c gcloud_beta_dns_managed-zones_update -l log-dns-queries
complete -c gcloud_beta_dns_managed-zones_update -l no-log-dns-queries -d disable
complete -c gcloud_beta_dns_managed-zones_update -l managed-reverse-lookup
complete -c gcloud_beta_dns_managed-zones_update -l networks
complete -c gcloud_beta_dns_managed-zones_update -l private-forwarding-targets
complete -c gcloud_beta_dns_managed-zones_update -l update-labels
complete -c gcloud_beta_dns_managed-zones_update -l zsk-algorithm
complete -c gcloud_beta_dns_managed-zones_update -l zsk-key-length
complete -c gcloud_beta_dns_managed-zones_update -l clear-labels
complete -c gcloud_beta_dns_managed-zones_update -l remove-labels
complete -c gcloud_beta_dns_managed-zones_update -l target-network
complete -c gcloud_beta_dns_managed-zones_update -l target-project
complete -c gcloud_beta_dns_managed-zones_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_dns_managed-zones_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_dns_managed-zones_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_dns_managed-zones_update -l verbosity

