# gcloud_beta_data-catalog_taxonomies_export
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_data-catalog_taxonomies_export.1.gz
complete -c gcloud_beta_data-catalog_taxonomies_export -l location
complete -c gcloud_beta_data-catalog_taxonomies_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_data-catalog_taxonomies_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_data-catalog_taxonomies_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_data-catalog_taxonomies_export -l verbosity

