# gcloud_beta_datastream_connection-profiles_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_datastream_connection-profiles_update.1.gz
complete -c gcloud_beta_datastream_connection-profiles_update -l location
complete -c gcloud_beta_datastream_connection-profiles_update -l type
complete -c gcloud_beta_datastream_connection-profiles_update -l display-name
complete -c gcloud_beta_datastream_connection-profiles_update -l update-labels
complete -c gcloud_beta_datastream_connection-profiles_update -l bucket-name
complete -c gcloud_beta_datastream_connection-profiles_update -l root-path
complete -c gcloud_beta_datastream_connection-profiles_update -l database-service
complete -c gcloud_beta_datastream_connection-profiles_update -l oracle-hostname
complete -c gcloud_beta_datastream_connection-profiles_update -l oracle-port
complete -c gcloud_beta_datastream_connection-profiles_update -l oracle-username
complete -c gcloud_beta_datastream_connection-profiles_update -l oracle-password
complete -c gcloud_beta_datastream_connection-profiles_update -l oracle-prompt-for-password
complete -c gcloud_beta_datastream_connection-profiles_update -l mysql-hostname
complete -c gcloud_beta_datastream_connection-profiles_update -l mysql-port
complete -c gcloud_beta_datastream_connection-profiles_update -l mysql-username
complete -c gcloud_beta_datastream_connection-profiles_update -l ca-certificate
complete -c gcloud_beta_datastream_connection-profiles_update -l client-certificate
complete -c gcloud_beta_datastream_connection-profiles_update -l client-key
complete -c gcloud_beta_datastream_connection-profiles_update -l mysql-password
complete -c gcloud_beta_datastream_connection-profiles_update -l mysql-prompt-for-password
complete -c gcloud_beta_datastream_connection-profiles_update -l clear-labels
complete -c gcloud_beta_datastream_connection-profiles_update -l remove-labels
complete -c gcloud_beta_datastream_connection-profiles_update -l private-connection-name
complete -c gcloud_beta_datastream_connection-profiles_update -l no-connectivity
complete -c gcloud_beta_datastream_connection-profiles_update -l static-ip-connectivity
complete -c gcloud_beta_datastream_connection-profiles_update -l forward-ssh-hostname
complete -c gcloud_beta_datastream_connection-profiles_update -l forward-ssh-port
complete -c gcloud_beta_datastream_connection-profiles_update -l forward-ssh-username
complete -c gcloud_beta_datastream_connection-profiles_update -l forward-ssh-password
complete -c gcloud_beta_datastream_connection-profiles_update -l forward-ssh-private-key
complete -c gcloud_beta_datastream_connection-profiles_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_datastream_connection-profiles_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_datastream_connection-profiles_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_datastream_connection-profiles_update -l verbosity

