# gcloud_beta_compute_instance-groups_managed_abandon-instances
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instance-groups_managed_abandon-instances.1.gz
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l instances
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l region
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l zone
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instance-groups_managed_abandon-instances -l verbosity

