# gcloud_alpha_compute_interconnects_macsec_add-key
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_interconnects_macsec_add-key.1.gz
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l key-name
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l start-time
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_interconnects_macsec_add-key -l verbosity

