# gcloud_alpha_iap_oauth-clients_reset-secret
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_iap_oauth-clients_reset-secret.1.gz
complete -c gcloud_alpha_iap_oauth-clients_reset-secret -l brand
complete -c gcloud_alpha_iap_oauth-clients_reset-secret -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_iap_oauth-clients_reset-secret -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_iap_oauth-clients_reset-secret -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_iap_oauth-clients_reset-secret -l verbosity

