# gcloud_beta_kms_keys_remove-rotation-schedule
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_kms_keys_remove-rotation-schedule.1.gz
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l keyring
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l location
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_kms_keys_remove-rotation-schedule -l verbosity

