# gcloud_beta_active-directory_peerings_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_active-directory_peerings_create.1.gz
complete -c gcloud_beta_active-directory_peerings_create -l authorized-network
complete -c gcloud_beta_active-directory_peerings_create -l domain
complete -c gcloud_beta_active-directory_peerings_create -l async
complete -c gcloud_beta_active-directory_peerings_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_active-directory_peerings_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_active-directory_peerings_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_active-directory_peerings_create -l verbosity

