# gcloud_beta_datastream_connection-profiles_discover
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_datastream_connection-profiles_discover.1.gz
complete -c gcloud_beta_datastream_connection-profiles_discover -l location
complete -c gcloud_beta_datastream_connection-profiles_discover -l connection-profile-name
complete -c gcloud_beta_datastream_connection-profiles_discover -l connection-profile-object-file
complete -c gcloud_beta_datastream_connection-profiles_discover -l mysql-rdbms-file
complete -c gcloud_beta_datastream_connection-profiles_discover -l oracle-rdbms-file
complete -c gcloud_beta_datastream_connection-profiles_discover -l recursive
complete -c gcloud_beta_datastream_connection-profiles_discover -l recursive-depth
complete -c gcloud_beta_datastream_connection-profiles_discover -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_datastream_connection-profiles_discover -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_datastream_connection-profiles_discover -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_datastream_connection-profiles_discover -l verbosity

