# gcloud_essential-contacts_compute
# Autogenerated from man page /usr/share/man/man1/gcloud_essential-contacts_compute.1.gz
complete -c gcloud_essential-contacts_compute -l notification-categories -d 'To compute contacts subscribed to the product-updates or billing categories f…'
complete -c gcloud_essential-contacts_compute -l folder -d 'To compute contacts subscribed to the legal category for the organization wit…'
complete -c gcloud_essential-contacts_compute -l organization -d 'REQUIRED FLAGS'
complete -c gcloud_essential-contacts_compute -l project
complete -c gcloud_essential-contacts_compute -l filter
complete -c gcloud_essential-contacts_compute -l sort-by -l limit
complete -c gcloud_essential-contacts_compute -l page-size
complete -c gcloud_essential-contacts_compute -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_essential-contacts_compute -l billing-project -l configuration -l flags-file
complete -c gcloud_essential-contacts_compute -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_essential-contacts_compute -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_essential-contacts_compute -l verbosity

