# gcloud_beta_data-fusion_instances_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_data-fusion_instances_create.1.gz
complete -c gcloud_beta_data-fusion_instances_create -l location
complete -c gcloud_beta_data-fusion_instances_create -l async
complete -c gcloud_beta_data-fusion_instances_create -l edition
complete -c gcloud_beta_data-fusion_instances_create -l enable_rbac
complete -c gcloud_beta_data-fusion_instances_create -l enable_stackdriver_logging
complete -c gcloud_beta_data-fusion_instances_create -l enable_stackdriver_monitoring
complete -c gcloud_beta_data-fusion_instances_create -l labels
complete -c gcloud_beta_data-fusion_instances_create -l options
complete -c gcloud_beta_data-fusion_instances_create -l version
complete -c gcloud_beta_data-fusion_instances_create -l zone
complete -c gcloud_beta_data-fusion_instances_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_data-fusion_instances_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_data-fusion_instances_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_data-fusion_instances_create -l verbosity

