# gcloud_alpha_api-gateway_gateways_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_api-gateway_gateways_create.1.gz
complete -c gcloud_alpha_api-gateway_gateways_create -l location
complete -c gcloud_alpha_api-gateway_gateways_create -l api-config
complete -c gcloud_alpha_api-gateway_gateways_create -l api
complete -c gcloud_alpha_api-gateway_gateways_create -l async
complete -c gcloud_alpha_api-gateway_gateways_create -l display-name
complete -c gcloud_alpha_api-gateway_gateways_create -l labels
complete -c gcloud_alpha_api-gateway_gateways_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_api-gateway_gateways_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_api-gateway_gateways_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_api-gateway_gateways_create -l verbosity

