# gcloud_container_azure_clusters_create
# Autogenerated from man page /usr/share/man/man1/gcloud_container_azure_clusters_create.1.gz
complete -c gcloud_container_azure_clusters_create -l location
complete -c gcloud_container_azure_clusters_create -l azure-region
complete -c gcloud_container_azure_clusters_create -l client
complete -c gcloud_container_azure_clusters_create -l cluster-version
complete -c gcloud_container_azure_clusters_create -l pod-address-cidr-blocks
complete -c gcloud_container_azure_clusters_create -l resource-group-id
complete -c gcloud_container_azure_clusters_create -l service-address-cidr-blocks
complete -c gcloud_container_azure_clusters_create -l ssh-public-key
complete -c gcloud_container_azure_clusters_create -l vnet-id
complete -c gcloud_container_azure_clusters_create -l async
complete -c gcloud_container_azure_clusters_create -l config-encryption-key-id
complete -c gcloud_container_azure_clusters_create -l config-encryption-public-key
complete -c gcloud_container_azure_clusters_create -l database-encryption-key-id
complete -c gcloud_container_azure_clusters_create -l endpoint-subnet-id
complete -c gcloud_container_azure_clusters_create -l fleet-project
complete -c gcloud_container_azure_clusters_create -l main-volume-size
complete -c gcloud_container_azure_clusters_create -l replica-placements
complete -c gcloud_container_azure_clusters_create -l root-volume-size
complete -c gcloud_container_azure_clusters_create -l service-load-balancer-subnet-id
complete -c gcloud_container_azure_clusters_create -l subnet-id
complete -c gcloud_container_azure_clusters_create -l tags
complete -c gcloud_container_azure_clusters_create -l validate-only
complete -c gcloud_container_azure_clusters_create -l vm-size
complete -c gcloud_container_azure_clusters_create -l proxy-resource-group-id
complete -c gcloud_container_azure_clusters_create -l proxy-secret-id
complete -c gcloud_container_azure_clusters_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_container_azure_clusters_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_container_azure_clusters_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_container_azure_clusters_create -l verbosity

