# gcloud_alpha_services_quota_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_services_quota_update.1.gz
complete -c gcloud_alpha_services_quota_update -l consumer
complete -c gcloud_alpha_services_quota_update -l metric
complete -c gcloud_alpha_services_quota_update -l service
complete -c gcloud_alpha_services_quota_update -l unit
complete -c gcloud_alpha_services_quota_update -l value
complete -c gcloud_alpha_services_quota_update -l dimensions
complete -c gcloud_alpha_services_quota_update -l force
complete -c gcloud_alpha_services_quota_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_services_quota_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_services_quota_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_services_quota_update -l verbosity

