# gcloud_sql_instances_import
# Autogenerated from man page /usr/share/man/man1/gcloud_sql_instances_import.1.gz
complete -c gcloud_sql_instances_import -l async
complete -c gcloud_sql_instances_import -l database -s d
complete -c gcloud_sql_instances_import -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_sql_instances_import -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_sql_instances_import -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_sql_instances_import -l verbosity

