# gcloud_container_aws_clusters_create
# Autogenerated from man page /usr/share/man/man1/gcloud_container_aws_clusters_create.1.gz
complete -c gcloud_container_aws_clusters_create -l location
complete -c gcloud_container_aws_clusters_create -l aws-region
complete -c gcloud_container_aws_clusters_create -l cluster-version
complete -c gcloud_container_aws_clusters_create -l database-encryption-kms-key-arn
complete -c gcloud_container_aws_clusters_create -l iam-instance-profile
complete -c gcloud_container_aws_clusters_create -l pod-address-cidr-blocks
complete -c gcloud_container_aws_clusters_create -l role-arn
complete -c gcloud_container_aws_clusters_create -l service-address-cidr-blocks
complete -c gcloud_container_aws_clusters_create -l subnet-ids
complete -c gcloud_container_aws_clusters_create -l vpc-id
complete -c gcloud_container_aws_clusters_create -l async
complete -c gcloud_container_aws_clusters_create -l config-encryption-kms-key-arn
complete -c gcloud_container_aws_clusters_create -l fleet-project
complete -c gcloud_container_aws_clusters_create -l instance-type
complete -c gcloud_container_aws_clusters_create -l main-volume-iops
complete -c gcloud_container_aws_clusters_create -l main-volume-kms-key-arn
complete -c gcloud_container_aws_clusters_create -l main-volume-size
complete -c gcloud_container_aws_clusters_create -l main-volume-type
complete -c gcloud_container_aws_clusters_create -l role-session-name
complete -c gcloud_container_aws_clusters_create -l root-volume-iops
complete -c gcloud_container_aws_clusters_create -l root-volume-kms-key-arn
complete -c gcloud_container_aws_clusters_create -l root-volume-size
complete -c gcloud_container_aws_clusters_create -l root-volume-type
complete -c gcloud_container_aws_clusters_create -l security-group-ids
complete -c gcloud_container_aws_clusters_create -l service-load-balancer-subnet-ids
complete -c gcloud_container_aws_clusters_create -l ssh-ec2-key-pair
complete -c gcloud_container_aws_clusters_create -l tags
complete -c gcloud_container_aws_clusters_create -l validate-only
complete -c gcloud_container_aws_clusters_create -l proxy-secret-arn
complete -c gcloud_container_aws_clusters_create -l proxy-secret-version-id
complete -c gcloud_container_aws_clusters_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_container_aws_clusters_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_container_aws_clusters_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_container_aws_clusters_create -l verbosity

