# gcloud_alpha_resource-manager_org-policies_allow
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_resource-manager_org-policies_allow.1.gz
complete -c gcloud_alpha_resource-manager_org-policies_allow -l folder
complete -c gcloud_alpha_resource-manager_org-policies_allow -l organization
complete -c gcloud_alpha_resource-manager_org-policies_allow -l project
complete -c gcloud_alpha_resource-manager_org-policies_allow -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_resource-manager_org-policies_allow -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_resource-manager_org-policies_allow -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_resource-manager_org-policies_allow -l verbosity

