# gcloud_beta_compute_instances_set-name
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instances_set-name.1.gz
complete -c gcloud_beta_compute_instances_set-name -l new-name
complete -c gcloud_beta_compute_instances_set-name -l zone
complete -c gcloud_beta_compute_instances_set-name -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instances_set-name -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instances_set-name -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instances_set-name -l verbosity

