# gcloud_alpha_artifacts_print-settings_gradle
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_artifacts_print-settings_gradle.1.gz
complete -c gcloud_alpha_artifacts_print-settings_gradle -l json-key
complete -c gcloud_alpha_artifacts_print-settings_gradle -l repository
complete -c gcloud_alpha_artifacts_print-settings_gradle -l location
complete -c gcloud_alpha_artifacts_print-settings_gradle -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_artifacts_print-settings_gradle -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_artifacts_print-settings_gradle -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_artifacts_print-settings_gradle -l verbosity

