# gcloud_alpha_compute_instance-groups_managed_stop-autoscaling
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_instance-groups_managed_stop-autoscaling.1.gz
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l region
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l zone
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_instance-groups_managed_stop-autoscaling -l verbosity

