# gcloud_alpha_dataproc_clusters_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dataproc_clusters_create.1.gz
complete -c gcloud_alpha_dataproc_clusters_create -l region
complete -c gcloud_alpha_dataproc_clusters_create -l autoscaling-policy
complete -c gcloud_alpha_dataproc_clusters_create -l no-address
complete -c gcloud_alpha_dataproc_clusters_create -l async
complete -c gcloud_alpha_dataproc_clusters_create -l bucket
complete -c gcloud_alpha_dataproc_clusters_create -l dataproc-metastore
complete -c gcloud_alpha_dataproc_clusters_create -l enable-component-gateway
complete -c gcloud_alpha_dataproc_clusters_create -l initialization-action-timeout
complete -c gcloud_alpha_dataproc_clusters_create -l initialization-actions
complete -c gcloud_alpha_dataproc_clusters_create -l labels
complete -c gcloud_alpha_dataproc_clusters_create -l master-accelerator
complete -c gcloud_alpha_dataproc_clusters_create -l master-boot-disk-size
complete -c gcloud_alpha_dataproc_clusters_create -l master-boot-disk-type
complete -c gcloud_alpha_dataproc_clusters_create -l master-machine-type
complete -c gcloud_alpha_dataproc_clusters_create -l master-min-cpu-platform
complete -c gcloud_alpha_dataproc_clusters_create -l max-idle
complete -c gcloud_alpha_dataproc_clusters_create -l node-group
complete -c gcloud_alpha_dataproc_clusters_create -l num-master-local-ssds
complete -c gcloud_alpha_dataproc_clusters_create -l num-masters
complete -c gcloud_alpha_dataproc_clusters_create -l num-secondary-worker-local-ssds
complete -c gcloud_alpha_dataproc_clusters_create -l num-worker-local-ssds
complete -c gcloud_alpha_dataproc_clusters_create -l optional-components
complete -c gcloud_alpha_dataproc_clusters_create -l private-ipv6-google-access-type
complete -c gcloud_alpha_dataproc_clusters_create -l properties
complete -c gcloud_alpha_dataproc_clusters_create -l secondary-worker-accelerator
complete -c gcloud_alpha_dataproc_clusters_create -l secondary-worker-boot-disk-size
complete -c gcloud_alpha_dataproc_clusters_create -l secondary-worker-boot-disk-type
complete -c gcloud_alpha_dataproc_clusters_create -l shielded-integrity-monitoring
complete -c gcloud_alpha_dataproc_clusters_create -l shielded-secure-boot
complete -c gcloud_alpha_dataproc_clusters_create -l shielded-vtpm
complete -c gcloud_alpha_dataproc_clusters_create -l temp-bucket
complete -c gcloud_alpha_dataproc_clusters_create -l worker-accelerator
complete -c gcloud_alpha_dataproc_clusters_create -l worker-boot-disk-size
complete -c gcloud_alpha_dataproc_clusters_create -l worker-boot-disk-type
complete -c gcloud_alpha_dataproc_clusters_create -l worker-machine-type
complete -c gcloud_alpha_dataproc_clusters_create -l worker-min-cpu-platform
complete -c gcloud_alpha_dataproc_clusters_create -l zone -s z
complete -c gcloud_alpha_dataproc_clusters_create -l expiration-time
complete -c gcloud_alpha_dataproc_clusters_create -l max-age
complete -c gcloud_alpha_dataproc_clusters_create -l gce-pd-kms-key
complete -c gcloud_alpha_dataproc_clusters_create -l gce-pd-kms-key-keyring
complete -c gcloud_alpha_dataproc_clusters_create -l gce-pd-kms-key-location
complete -c gcloud_alpha_dataproc_clusters_create -l gce-pd-kms-key-project
complete -c gcloud_alpha_dataproc_clusters_create -l metadata
complete -c gcloud_alpha_dataproc_clusters_create -l scopes
complete -c gcloud_alpha_dataproc_clusters_create -l service-account
complete -c gcloud_alpha_dataproc_clusters_create -l tags
complete -c gcloud_alpha_dataproc_clusters_create -l network
complete -c gcloud_alpha_dataproc_clusters_create -l subnet
complete -c gcloud_alpha_dataproc_clusters_create -l reservation
complete -c gcloud_alpha_dataproc_clusters_create -l reservation-affinity
complete -c gcloud_alpha_dataproc_clusters_create -l image
complete -c gcloud_alpha_dataproc_clusters_create -l image-version
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-config-file
complete -c gcloud_alpha_dataproc_clusters_create -l enable-kerberos
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-root-principal-password-uri
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-kms-key
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-kms-key-keyring
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-kms-key-location
complete -c gcloud_alpha_dataproc_clusters_create -l kerberos-kms-key-project
complete -c gcloud_alpha_dataproc_clusters_create -l single-node
complete -c gcloud_alpha_dataproc_clusters_create -l num-secondary-workers
complete -c gcloud_alpha_dataproc_clusters_create -l num-workers
complete -c gcloud_alpha_dataproc_clusters_create -l secondary-worker-type
complete -c gcloud_alpha_dataproc_clusters_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dataproc_clusters_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dataproc_clusters_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dataproc_clusters_create -l verbosity

