# gcloud_beta_compute_backend-services_remove-backend
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_backend-services_remove-backend.1.gz
complete -c gcloud_beta_compute_backend-services_remove-backend -l instance-group
complete -c gcloud_beta_compute_backend-services_remove-backend -l instance-group-region
complete -c gcloud_beta_compute_backend-services_remove-backend -l instance-group-zone
complete -c gcloud_beta_compute_backend-services_remove-backend -l network-endpoint-group
complete -c gcloud_beta_compute_backend-services_remove-backend -l global-network-endpoint-group
complete -c gcloud_beta_compute_backend-services_remove-backend -l network-endpoint-group-region
complete -c gcloud_beta_compute_backend-services_remove-backend -l network-endpoint-group-zone
complete -c gcloud_beta_compute_backend-services_remove-backend -l global
complete -c gcloud_beta_compute_backend-services_remove-backend -l region
complete -c gcloud_beta_compute_backend-services_remove-backend -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_backend-services_remove-backend -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_backend-services_remove-backend -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_backend-services_remove-backend -l verbosity

