# gcloud_alpha_anthos_config_sync_repo_list
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_anthos_config_sync_repo_list.1.gz
complete -c gcloud_alpha_anthos_config_sync_repo_list -l membership
complete -c gcloud_alpha_anthos_config_sync_repo_list -l namespace
complete -c gcloud_alpha_anthos_config_sync_repo_list -l selector
complete -c gcloud_alpha_anthos_config_sync_repo_list -l status
complete -c gcloud_alpha_anthos_config_sync_repo_list -l targets
complete -c gcloud_alpha_anthos_config_sync_repo_list -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_anthos_config_sync_repo_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_anthos_config_sync_repo_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_anthos_config_sync_repo_list -l verbosity

