# gcloud_ml_vision_detect-document
# Autogenerated from man page /usr/share/man/man1/gcloud_ml_vision_detect-document.1.gz
complete -c gcloud_ml_vision_detect-document -l language-hints
complete -c gcloud_ml_vision_detect-document -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_ml_vision_detect-document -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_ml_vision_detect-document -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_ml_vision_detect-document -l verbosity

