# gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout.1.gz
complete -c gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout -l region
complete -c gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dataproc_workflow-templates_remove-dag-timeout -l verbosity

