# gcloud_secrets_versions_enable
# Autogenerated from man page /usr/share/man/man1/gcloud_secrets_versions_enable.1.gz
complete -c gcloud_secrets_versions_enable -l secret
complete -c gcloud_secrets_versions_enable -l etag
complete -c gcloud_secrets_versions_enable -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_secrets_versions_enable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_secrets_versions_enable -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_secrets_versions_enable -l verbosity

