# gcloud_alpha_endpoints_operations_list
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_endpoints_operations_list.1.gz
complete -c gcloud_alpha_endpoints_operations_list -l filter -d '$ gcloud alpha endpoints operations list \\     --service=api. endpoints. proj'
complete -c gcloud_alpha_endpoints_operations_list -l service
complete -c gcloud_alpha_endpoints_operations_list -l limit
complete -c gcloud_alpha_endpoints_operations_list -l sort-by
complete -c gcloud_alpha_endpoints_operations_list -l page-size
complete -c gcloud_alpha_endpoints_operations_list -l flatten
complete -c gcloud_alpha_endpoints_operations_list -l uri
complete -c gcloud_alpha_endpoints_operations_list -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_endpoints_operations_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_endpoints_operations_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_endpoints_operations_list -l verbosity

