# gcloud_container_binauthz_policy_export
# Autogenerated from man page /usr/share/man/man1/gcloud_container_binauthz_policy_export.1.gz
complete -c gcloud_container_binauthz_policy_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_container_binauthz_policy_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_container_binauthz_policy_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_container_binauthz_policy_export -l verbosity

