# gcloud_beta_compute_instance-templates_remove-iam-policy-binding
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instance-templates_remove-iam-policy-binding.1.gz
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l member
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l role
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l all
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l condition
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l condition-from-file
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instance-templates_remove-iam-policy-binding -l verbosity

