# gcloud_alpha_active-directory_domains_sql-integrations_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_active-directory_domains_sql-integrations_describe.1.gz
complete -c gcloud_alpha_active-directory_domains_sql-integrations_describe -l domain
complete -c gcloud_alpha_active-directory_domains_sql-integrations_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_active-directory_domains_sql-integrations_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_active-directory_domains_sql-integrations_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_active-directory_domains_sql-integrations_describe -l verbosity

