# gcloud_alpha_recommender_recommendations_mark-dismissed
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_recommender_recommendations_mark-dismissed.1.gz
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l recommender -l etag -d 'POSITIONAL ARGUMENTS RECOMMENDATION'
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l location
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l organization
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l billing-account
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l folder
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l project
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l verbosity

