# gcloud_alpha_compute_health-checks_create_grpc
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_health-checks_create_grpc.1.gz
complete -c gcloud_alpha_compute_health-checks_create_grpc -l check-interval
complete -c gcloud_alpha_compute_health-checks_create_grpc -l description
complete -c gcloud_alpha_compute_health-checks_create_grpc -l enable-logging
complete -c gcloud_alpha_compute_health-checks_create_grpc -l grpc-service-name
complete -c gcloud_alpha_compute_health-checks_create_grpc -l healthy-threshold
complete -c gcloud_alpha_compute_health-checks_create_grpc -l timeout
complete -c gcloud_alpha_compute_health-checks_create_grpc -l unhealthy-threshold
complete -c gcloud_alpha_compute_health-checks_create_grpc -l global
complete -c gcloud_alpha_compute_health-checks_create_grpc -l region
complete -c gcloud_alpha_compute_health-checks_create_grpc -l port
complete -c gcloud_alpha_compute_health-checks_create_grpc -l use-serving-port
complete -c gcloud_alpha_compute_health-checks_create_grpc -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_health-checks_create_grpc -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_health-checks_create_grpc -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_health-checks_create_grpc -l verbosity

