# gcloud_alpha_compute_images_vulnerabilities_describe-note
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_images_vulnerabilities_describe-note.1.gz
complete -c gcloud_alpha_compute_images_vulnerabilities_describe-note -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_images_vulnerabilities_describe-note -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_images_vulnerabilities_describe-note -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_images_vulnerabilities_describe-note -l verbosity

