# gcloud_beta_iot_devices_states_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_iot_devices_states_list.1.gz
complete -c gcloud_beta_iot_devices_states_list -l limit -d EXAMPLES
complete -c gcloud_beta_iot_devices_states_list -l device
complete -c gcloud_beta_iot_devices_states_list -l region
complete -c gcloud_beta_iot_devices_states_list -l registry
complete -c gcloud_beta_iot_devices_states_list -l filter
complete -c gcloud_beta_iot_devices_states_list -l sort-by
complete -c gcloud_beta_iot_devices_states_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_iot_devices_states_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_iot_devices_states_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_iot_devices_states_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_iot_devices_states_list -l verbosity

