# gcloud_beta_iap_web_enable
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_iap_web_enable.1.gz
complete -c gcloud_beta_iap_web_enable -l oauth2-client-id
complete -c gcloud_beta_iap_web_enable -l oauth2-client-secret
complete -c gcloud_beta_iap_web_enable -l resource-type
complete -c gcloud_beta_iap_web_enable -l service
complete -c gcloud_beta_iap_web_enable -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_iap_web_enable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_iap_web_enable -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_iap_web_enable -l verbosity

