# gcloud_alpha_firestore_export
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_firestore_export.1.gz
complete -c gcloud_alpha_firestore_export -l async
complete -c gcloud_alpha_firestore_export -l collection-ids
complete -c gcloud_alpha_firestore_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_firestore_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_firestore_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_firestore_export -l verbosity

