# gcloud_alpha_cloud-shell_ssh
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_cloud-shell_ssh.1.gz
complete -c gcloud_alpha_cloud-shell_ssh -l authorize-session
complete -c gcloud_alpha_cloud-shell_ssh -l command
complete -c gcloud_alpha_cloud-shell_ssh -l dry-run
complete -c gcloud_alpha_cloud-shell_ssh -l force-key-file-overwrite
complete -c gcloud_alpha_cloud-shell_ssh -l ssh-flag
complete -c gcloud_alpha_cloud-shell_ssh -l ssh-key-file
complete -c gcloud_alpha_cloud-shell_ssh -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_cloud-shell_ssh -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_cloud-shell_ssh -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_cloud-shell_ssh -l verbosity

