# gcloud_iam_service-accounts_keys_enable
# Autogenerated from man page /usr/share/man/man1/gcloud_iam_service-accounts_keys_enable.1.gz
complete -c gcloud_iam_service-accounts_keys_enable -l iam-account
complete -c gcloud_iam_service-accounts_keys_enable -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_iam_service-accounts_keys_enable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_iam_service-accounts_keys_enable -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_iam_service-accounts_keys_enable -l verbosity

