# gcloud_beta_apigee_apis_undeploy
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_apigee_apis_undeploy.1.gz
complete -c gcloud_beta_apigee_apis_undeploy -l api
complete -c gcloud_beta_apigee_apis_undeploy -l environment
complete -c gcloud_beta_apigee_apis_undeploy -l organization
complete -c gcloud_beta_apigee_apis_undeploy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_apigee_apis_undeploy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_apigee_apis_undeploy -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_apigee_apis_undeploy -l verbosity

