# gcloud_dataproc_jobs_kill
# Autogenerated from man page /usr/share/man/man1/gcloud_dataproc_jobs_kill.1.gz
complete -c gcloud_dataproc_jobs_kill -l region
complete -c gcloud_dataproc_jobs_kill -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dataproc_jobs_kill -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dataproc_jobs_kill -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dataproc_jobs_kill -l verbosity

