# gcloud_ml_vision_detect-labels
# Autogenerated from man page /usr/share/man/man1/gcloud_ml_vision_detect-labels.1.gz
complete -c gcloud_ml_vision_detect-labels -l max-results
complete -c gcloud_ml_vision_detect-labels -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_ml_vision_detect-labels -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_ml_vision_detect-labels -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_ml_vision_detect-labels -l verbosity

