# gcloud_ai_custom-jobs_create
# Autogenerated from man page /usr/share/man/man1/gcloud_ai_custom-jobs_create.1.gz
complete -c gcloud_ai_custom-jobs_create -l worker-pool-spec
complete -c gcloud_ai_custom-jobs_create -l display-name -d 'REQUIRED FLAGS'
complete -c gcloud_ai_custom-jobs_create -l config
complete -c gcloud_ai_custom-jobs_create -l args
complete -c gcloud_ai_custom-jobs_create -l command
complete -c gcloud_ai_custom-jobs_create -l enable-web-access
complete -c gcloud_ai_custom-jobs_create -l network
complete -c gcloud_ai_custom-jobs_create -l python-package-uris
complete -c gcloud_ai_custom-jobs_create -l region
complete -c gcloud_ai_custom-jobs_create -l service-account
complete -c gcloud_ai_custom-jobs_create -l kms-key
complete -c gcloud_ai_custom-jobs_create -l kms-keyring
complete -c gcloud_ai_custom-jobs_create -l kms-location
complete -c gcloud_ai_custom-jobs_create -l kms-project
complete -c gcloud_ai_custom-jobs_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_ai_custom-jobs_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_ai_custom-jobs_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_ai_custom-jobs_create -l verbosity

