# gcloud_beta_compute_instances_send-diagnostic-interrupt
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instances_send-diagnostic-interrupt.1.gz
complete -c gcloud_beta_compute_instances_send-diagnostic-interrupt -l zone
complete -c gcloud_beta_compute_instances_send-diagnostic-interrupt -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instances_send-diagnostic-interrupt -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instances_send-diagnostic-interrupt -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instances_send-diagnostic-interrupt -l verbosity

