# gcloud_beta_iot_devices_gateways_bind
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_iot_devices_gateways_bind.1.gz
complete -c gcloud_beta_iot_devices_gateways_bind -l device
complete -c gcloud_beta_iot_devices_gateways_bind -l device-region
complete -c gcloud_beta_iot_devices_gateways_bind -l device-registry
complete -c gcloud_beta_iot_devices_gateways_bind -l gateway
complete -c gcloud_beta_iot_devices_gateways_bind -l gateway-region
complete -c gcloud_beta_iot_devices_gateways_bind -l gateway-registry
complete -c gcloud_beta_iot_devices_gateways_bind -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_iot_devices_gateways_bind -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_iot_devices_gateways_bind -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_iot_devices_gateways_bind -l verbosity

