# gcloud_beta_kms_keys_versions_get-public-key
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_kms_keys_versions_get-public-key.1.gz
complete -c gcloud_beta_kms_keys_versions_get-public-key -l key
complete -c gcloud_beta_kms_keys_versions_get-public-key -l keyring
complete -c gcloud_beta_kms_keys_versions_get-public-key -l location
complete -c gcloud_beta_kms_keys_versions_get-public-key -l output-file -d 'POSITIONAL ARGUMENTS VERSION'
complete -c gcloud_beta_kms_keys_versions_get-public-key -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_kms_keys_versions_get-public-key -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_kms_keys_versions_get-public-key -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_kms_keys_versions_get-public-key -l verbosity

