# gcloud_alpha_recommender_recommendations_mark-claimed
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_recommender_recommendations_mark-claimed.1.gz
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l recommender -l etag
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l state-metadata -d 'POSITIONAL ARGUMENTS RECOMMENDATION'
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l location
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l organization
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l billing-account
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l folder
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l project
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l verbosity

