# gcloud_alpha_compute_os-login_ssh-keys_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_os-login_ssh-keys_update.1.gz
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l ttl
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l key
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l key-file
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_os-login_ssh-keys_update -l verbosity

