# gcloud_alpha_dataflow_jobs_resume-unsupported-sdk
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dataflow_jobs_resume-unsupported-sdk.1.gz
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l token
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l region
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dataflow_jobs_resume-unsupported-sdk -l verbosity

