# gcloud_alpha_compute_interconnects_attachments_partner_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_interconnects_attachments_partner_create.1.gz
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l edge-availability-domain
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l router
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l description
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l dry-run
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l enable-admin
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l mtu
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l region
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_interconnects_attachments_partner_create -l verbosity

