# gcloud_pubsub_subscriptions_modify-push-config
# Autogenerated from man page /usr/share/man/man1/gcloud_pubsub_subscriptions_modify-push-config.1.gz
complete -c gcloud_pubsub_subscriptions_modify-push-config -l push-endpoint
complete -c gcloud_pubsub_subscriptions_modify-push-config -l push-auth-service-account
complete -c gcloud_pubsub_subscriptions_modify-push-config -l push-auth-token-audience
complete -c gcloud_pubsub_subscriptions_modify-push-config -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_pubsub_subscriptions_modify-push-config -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_pubsub_subscriptions_modify-push-config -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_pubsub_subscriptions_modify-push-config -l verbosity

