# gcloud_beta_datastream_streams_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_datastream_streams_update.1.gz
complete -c gcloud_beta_datastream_streams_update -l location
complete -c gcloud_beta_datastream_streams_update -l display-name
complete -c gcloud_beta_datastream_streams_update -l force
complete -c gcloud_beta_datastream_streams_update -l state
complete -c gcloud_beta_datastream_streams_update -l update-labels
complete -c gcloud_beta_datastream_streams_update -l update-mask
complete -c gcloud_beta_datastream_streams_update -l validate-only
complete -c gcloud_beta_datastream_streams_update -l backfill-none
complete -c gcloud_beta_datastream_streams_update -l backfill-all
complete -c gcloud_beta_datastream_streams_update -l mysql-excluded-objects
complete -c gcloud_beta_datastream_streams_update -l oracle-excluded-objects
complete -c gcloud_beta_datastream_streams_update -l clear-labels
complete -c gcloud_beta_datastream_streams_update -l remove-labels
complete -c gcloud_beta_datastream_streams_update -l destination-name
complete -c gcloud_beta_datastream_streams_update -l gcs-destination-config
complete -c gcloud_beta_datastream_streams_update -l source-name
complete -c gcloud_beta_datastream_streams_update -l mysql-source-config
complete -c gcloud_beta_datastream_streams_update -l oracle-source-config
complete -c gcloud_beta_datastream_streams_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_datastream_streams_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_datastream_streams_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_datastream_streams_update -l verbosity

