# gcloud_ai-platform_versions_create
# Autogenerated from man page /usr/share/man/man1/gcloud_ai-platform_versions_create.1.gz
complete -c gcloud_ai-platform_versions_create -l model
complete -c gcloud_ai-platform_versions_create -l accelerator
complete -c gcloud_ai-platform_versions_create -l async
complete -c gcloud_ai-platform_versions_create -l config
complete -c gcloud_ai-platform_versions_create -l description
complete -c gcloud_ai-platform_versions_create -l framework
complete -c gcloud_ai-platform_versions_create -l labels
complete -c gcloud_ai-platform_versions_create -l machine-type
complete -c gcloud_ai-platform_versions_create -l origin
complete -c gcloud_ai-platform_versions_create -l staging-bucket
complete -c gcloud_ai-platform_versions_create -l python-version
complete -c gcloud_ai-platform_versions_create -l region
complete -c gcloud_ai-platform_versions_create -l runtime-version
complete -c gcloud_ai-platform_versions_create -l master-image-uri -d 'along with the list of supported versions: https://cloud. google'
complete -c gcloud_ai-platform_versions_create -l max-nodes
complete -c gcloud_ai-platform_versions_create -l metric-targets
complete -c gcloud_ai-platform_versions_create -l min-nodes
complete -c gcloud_ai-platform_versions_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_ai-platform_versions_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_ai-platform_versions_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_ai-platform_versions_create -l verbosity

