# gcloud_alpha_compute_os-config_os-policy-assignments_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_os-config_os-policy-assignments_update.1.gz
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l location
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l file
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l async
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_os-config_os-policy-assignments_update -l verbosity

