# gcloud_alpha_compute_sign-url
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_sign-url.1.gz
complete -c gcloud_alpha_compute_sign-url -l expires-in
complete -c gcloud_alpha_compute_sign-url -l key-file
complete -c gcloud_alpha_compute_sign-url -l key-name
complete -c gcloud_alpha_compute_sign-url -l validate
complete -c gcloud_alpha_compute_sign-url -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_sign-url -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_sign-url -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_sign-url -l verbosity

