# gcloud_beta_builds_worker-pools_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_builds_worker-pools_create.1.gz
complete -c gcloud_beta_builds_worker-pools_create -l region
complete -c gcloud_beta_builds_worker-pools_create -l config-from-file
complete -c gcloud_beta_builds_worker-pools_create -l peered-network
complete -c gcloud_beta_builds_worker-pools_create -l no-external-ip
complete -c gcloud_beta_builds_worker-pools_create -l worker-disk-size
complete -c gcloud_beta_builds_worker-pools_create -l worker-machine-type
complete -c gcloud_beta_builds_worker-pools_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_builds_worker-pools_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_builds_worker-pools_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_builds_worker-pools_create -l verbosity

