# gcloud_alpha_tasks_acknowledge
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_tasks_acknowledge.1.gz
complete -c gcloud_alpha_tasks_acknowledge -l schedule-time
complete -c gcloud_alpha_tasks_acknowledge -l location
complete -c gcloud_alpha_tasks_acknowledge -l queue
complete -c gcloud_alpha_tasks_acknowledge -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_tasks_acknowledge -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_tasks_acknowledge -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_tasks_acknowledge -l verbosity

