# gcloud_debug_source_gen-repo-info-file
# Autogenerated from man page /usr/share/man/man1/gcloud_debug_source_gen-repo-info-file.1.gz
complete -c gcloud_debug_source_gen-repo-info-file -l output-directory
complete -c gcloud_debug_source_gen-repo-info-file -l source-directory
complete -c gcloud_debug_source_gen-repo-info-file -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_debug_source_gen-repo-info-file -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_debug_source_gen-repo-info-file -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_debug_source_gen-repo-info-file -l verbosity

