# gcloud_beta_compute_instance-groups_managed_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instance-groups_managed_create.1.gz
complete -c gcloud_beta_compute_instance-groups_managed_create -l template -l size -d 'will create one managed instance group called \'example-managed-instance-group…'
complete -c gcloud_beta_compute_instance-groups_managed_create -l base-instance-name
complete -c gcloud_beta_compute_instance-groups_managed_create -l description
complete -c gcloud_beta_compute_instance-groups_managed_create -l initial-delay
complete -c gcloud_beta_compute_instance-groups_managed_create -l instance-redistribution-type
complete -c gcloud_beta_compute_instance-groups_managed_create -l stateful-disk
complete -c gcloud_beta_compute_instance-groups_managed_create -l target-distribution-shape
complete -c gcloud_beta_compute_instance-groups_managed_create -l target-pool
complete -c gcloud_beta_compute_instance-groups_managed_create -l zones
complete -c gcloud_beta_compute_instance-groups_managed_create -l zone -d 'At most one of these may be specified:'
complete -c gcloud_beta_compute_instance-groups_managed_create -l health-check
complete -c gcloud_beta_compute_instance-groups_managed_create -l http-health-check
complete -c gcloud_beta_compute_instance-groups_managed_create -l https-health-check
complete -c gcloud_beta_compute_instance-groups_managed_create -l region
complete -c gcloud_beta_compute_instance-groups_managed_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instance-groups_managed_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instance-groups_managed_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instance-groups_managed_create -l verbosity

