# gcloud_iot_devices_create
# Autogenerated from man page /usr/share/man/man1/gcloud_iot_devices_create.1.gz
complete -c gcloud_iot_devices_create -l region
complete -c gcloud_iot_devices_create -l registry
complete -c gcloud_iot_devices_create -l auth-method
complete -c gcloud_iot_devices_create -l blocked
complete -c gcloud_iot_devices_create -l device-type
complete -c gcloud_iot_devices_create -l log-level
complete -c gcloud_iot_devices_create -l metadata
complete -c gcloud_iot_devices_create -l metadata-from-file
complete -c gcloud_iot_devices_create -l public-key
complete -c gcloud_iot_devices_create -l ---BEGIN -l ---END -d CERTIFICATE-----
complete -c gcloud_iot_devices_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_iot_devices_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_iot_devices_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_iot_devices_create -l verbosity

