# gcloud_alpha_ml_translate_batch-translate-text
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ml_translate_batch-translate-text.1.gz
complete -c gcloud_alpha_ml_translate_batch-translate-text -l destination
complete -c gcloud_alpha_ml_translate_batch-translate-text -l source
complete -c gcloud_alpha_ml_translate_batch-translate-text -l source-language
complete -c gcloud_alpha_ml_translate_batch-translate-text -l target-language-codes
complete -c gcloud_alpha_ml_translate_batch-translate-text -l glossaries
complete -c gcloud_alpha_ml_translate_batch-translate-text -l models
complete -c gcloud_alpha_ml_translate_batch-translate-text -l zone
complete -c gcloud_alpha_ml_translate_batch-translate-text -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ml_translate_batch-translate-text -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ml_translate_batch-translate-text -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ml_translate_batch-translate-text -l verbosity

