# gcloud_beta_iap_settings_set
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_iap_settings_set.1.gz
complete -c gcloud_beta_iap_settings_set -l folder
complete -c gcloud_beta_iap_settings_set -l organization
complete -c gcloud_beta_iap_settings_set -l project
complete -c gcloud_beta_iap_settings_set -l resource-type
complete -c gcloud_beta_iap_settings_set -l service
complete -c gcloud_beta_iap_settings_set -l version
complete -c gcloud_beta_iap_settings_set -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_iap_settings_set -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_iap_settings_set -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_iap_settings_set -l verbosity

