# gcloud_alpha_active-directory_domains_restore
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_active-directory_domains_restore.1.gz
complete -c gcloud_alpha_active-directory_domains_restore -l backup
complete -c gcloud_alpha_active-directory_domains_restore -l async
complete -c gcloud_alpha_active-directory_domains_restore -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_active-directory_domains_restore -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_active-directory_domains_restore -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_active-directory_domains_restore -l verbosity

