# gcloud_alpha_api-gateway_operations_wait
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_api-gateway_operations_wait.1.gz
complete -c gcloud_alpha_api-gateway_operations_wait -l location
complete -c gcloud_alpha_api-gateway_operations_wait -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_api-gateway_operations_wait -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_api-gateway_operations_wait -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_api-gateway_operations_wait -l verbosity

