# gcloud_beta_container_clusters_get-credentials
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_container_clusters_get-credentials.1.gz
complete -c gcloud_beta_container_clusters_get-credentials -l internal-ip
complete -c gcloud_beta_container_clusters_get-credentials -l region
complete -c gcloud_beta_container_clusters_get-credentials -l zone -s z
complete -c gcloud_beta_container_clusters_get-credentials -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_container_clusters_get-credentials -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_container_clusters_get-credentials -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_container_clusters_get-credentials -l verbosity

