# gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls.1.gz
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l scan-run
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l scan-config
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l filter
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l sort-by -l limit
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l page-size
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l verbosity

