# gcloud_alpha_ml_language_analyze-sentiment
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ml_language_analyze-sentiment.1.gz
complete -c gcloud_alpha_ml_language_analyze-sentiment -l content
complete -c gcloud_alpha_ml_language_analyze-sentiment -l content-file
complete -c gcloud_alpha_ml_language_analyze-sentiment -l content-type
complete -c gcloud_alpha_ml_language_analyze-sentiment -l encoding-type
complete -c gcloud_alpha_ml_language_analyze-sentiment -l language
complete -c gcloud_alpha_ml_language_analyze-sentiment -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ml_language_analyze-sentiment -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ml_language_analyze-sentiment -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ml_language_analyze-sentiment -l verbosity

