# gcloud_alpha_scc_settings_services_describe-explicit
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_scc_settings_services_describe-explicit.1.gz
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l service
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l folder
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l organization
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l project
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_scc_settings_services_describe-explicit -l verbosity

