# gcloud_scheduler_jobs_update_http
# Autogenerated from man page /usr/share/man/man1/gcloud_scheduler_jobs_update_http.1.gz
complete -c gcloud_scheduler_jobs_update_http -l location
complete -c gcloud_scheduler_jobs_update_http -l attempt-deadline
complete -c gcloud_scheduler_jobs_update_http -l description
complete -c gcloud_scheduler_jobs_update_http -l http-method
complete -c gcloud_scheduler_jobs_update_http -l schedule
complete -c gcloud_scheduler_jobs_update_http -l uri
complete -c gcloud_scheduler_jobs_update_http -l clear-auth-token
complete -c gcloud_scheduler_jobs_update_http -l oidc-token-audience -l oauth-service-account-email
complete -c gcloud_scheduler_jobs_update_http -l oauth-token-scope -d OAuth2
complete -c gcloud_scheduler_jobs_update_http -l oidc-service-account-email
complete -c gcloud_scheduler_jobs_update_http -l clear-headers
complete -c gcloud_scheduler_jobs_update_http -l remove-headers
complete -c gcloud_scheduler_jobs_update_http -l update-headers
complete -c gcloud_scheduler_jobs_update_http -l clear-max-backoff
complete -c gcloud_scheduler_jobs_update_http -l max-backoff
complete -c gcloud_scheduler_jobs_update_http -l clear-max-doublings
complete -c gcloud_scheduler_jobs_update_http -l max-doublings
complete -c gcloud_scheduler_jobs_update_http -l clear-max-retry-attempts
complete -c gcloud_scheduler_jobs_update_http -l max-retry-attempts
complete -c gcloud_scheduler_jobs_update_http -l clear-max-retry-duration
complete -c gcloud_scheduler_jobs_update_http -l max-retry-duration
complete -c gcloud_scheduler_jobs_update_http -l clear-message-body
complete -c gcloud_scheduler_jobs_update_http -l message-body-from-file
complete -c gcloud_scheduler_jobs_update_http -l message-body
complete -c gcloud_scheduler_jobs_update_http -l clear-min-backoff
complete -c gcloud_scheduler_jobs_update_http -l min-backoff
complete -c gcloud_scheduler_jobs_update_http -l clear-time-zone
complete -c gcloud_scheduler_jobs_update_http -l time-zone
complete -c gcloud_scheduler_jobs_update_http -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_scheduler_jobs_update_http -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_scheduler_jobs_update_http -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_scheduler_jobs_update_http -l verbosity

