# gcloud_alpha_compute_tpus_tpu-vm_ssh
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_tpus_tpu-vm_ssh.1.gz
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l zone -o vvv -s L -d FLAGS
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l dry-run
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l force-key-file-overwrite
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l internal-ip
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l plain
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l ssh-flag
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l ssh-key-file
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l strict-host-key-checking
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l worker
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l command
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l output-directory
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l ssh-key-expiration
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l ssh-key-expire-after
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_tpus_tpu-vm_ssh -l verbosity

