# gcloud_alpha_ids_endpoints_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_ids_endpoints_delete.1.gz
complete -c gcloud_alpha_ids_endpoints_delete -l zone
complete -c gcloud_alpha_ids_endpoints_delete -l async
complete -c gcloud_alpha_ids_endpoints_delete -l max-wait
complete -c gcloud_alpha_ids_endpoints_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_ids_endpoints_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_ids_endpoints_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_ids_endpoints_delete -l verbosity

