# gcloud_alpha_network-connectivity_policy-based-routes_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_network-connectivity_policy-based-routes_create.1.gz
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l network
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l next-hop-ilb-ip
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l async
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l description
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l destination-range
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l interconnect-attachment-region
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l tags -d 'based route will be installed in all network endpoints, including VMs, VPNs, …'
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l ip-protocol
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l labels
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l priority
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l protocol-version
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l source-range
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_network-connectivity_policy-based-routes_create -l verbosity

