# gcloud_alpha_resource-settings_list-values
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_resource-settings_list-values.1.gz
complete -c gcloud_alpha_resource-settings_list-values -l folder
complete -c gcloud_alpha_resource-settings_list-values -l organization
complete -c gcloud_alpha_resource-settings_list-values -l project
complete -c gcloud_alpha_resource-settings_list-values -l filter
complete -c gcloud_alpha_resource-settings_list-values -l sort-by -l limit
complete -c gcloud_alpha_resource-settings_list-values -l page-size
complete -c gcloud_alpha_resource-settings_list-values -l flatten
complete -c gcloud_alpha_resource-settings_list-values -l uri
complete -c gcloud_alpha_resource-settings_list-values -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_resource-settings_list-values -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_resource-settings_list-values -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_resource-settings_list-values -l verbosity

