# gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create.1.gz
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l public-delegated-prefix
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l create-addresses
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l delegatee-project
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l description
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l range
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l global-public-delegated-prefix
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l public-delegated-prefix-region
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_public-delegated-prefixes_delegated-sub-prefixes_create -l verbosity

