# gcloud_alpha_filestore_instances_restore
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_filestore_instances_restore.1.gz
complete -c gcloud_alpha_filestore_instances_restore -l zone
complete -c gcloud_alpha_filestore_instances_restore -l file-share
complete -c gcloud_alpha_filestore_instances_restore -l source-backup
complete -c gcloud_alpha_filestore_instances_restore -l source-backup-region
complete -c gcloud_alpha_filestore_instances_restore -l source-snapshot
complete -c gcloud_alpha_filestore_instances_restore -l source-snapshot-region
complete -c gcloud_alpha_filestore_instances_restore -l async
complete -c gcloud_alpha_filestore_instances_restore -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_filestore_instances_restore -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_filestore_instances_restore -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_filestore_instances_restore -l verbosity

