# gcloud_beta_iot_devices_configs_get-value
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_iot_devices_configs_get-value.1.gz
complete -c gcloud_beta_iot_devices_configs_get-value -l device
complete -c gcloud_beta_iot_devices_configs_get-value -l region
complete -c gcloud_beta_iot_devices_configs_get-value -l registry
complete -c gcloud_beta_iot_devices_configs_get-value -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_iot_devices_configs_get-value -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_iot_devices_configs_get-value -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_iot_devices_configs_get-value -l verbosity

