# gcloud_alpha_run_revisions_logs_read
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_run_revisions_logs_read.1.gz
complete -c gcloud_alpha_run_revisions_logs_read -l freshness
complete -c gcloud_alpha_run_revisions_logs_read -l log-filter
complete -c gcloud_alpha_run_revisions_logs_read -l order
complete -c gcloud_alpha_run_revisions_logs_read -l platform
complete -c gcloud_alpha_run_revisions_logs_read -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_alpha_run_revisions_logs_read -l region
complete -c gcloud_alpha_run_revisions_logs_read -l cluster
complete -c gcloud_alpha_run_revisions_logs_read -l context
complete -c gcloud_alpha_run_revisions_logs_read -l kubeconfig
complete -c gcloud_alpha_run_revisions_logs_read -l limit
complete -c gcloud_alpha_run_revisions_logs_read -l sort-by -l filter -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_run_revisions_logs_read -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_run_revisions_logs_read -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_run_revisions_logs_read -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_run_revisions_logs_read -l verbosity

