# gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete.1.gz
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l public-delegated-prefix
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l global-public-delegated-prefix
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l public-delegated-prefix-region
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_public-delegated-prefixes_delegated-sub-prefixes_delete -l verbosity

