# gcloud_beta_privateca_subordinates_restore
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_privateca_subordinates_restore.1.gz
complete -c gcloud_beta_privateca_subordinates_restore -l location
complete -c gcloud_beta_privateca_subordinates_restore -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_privateca_subordinates_restore -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_privateca_subordinates_restore -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_privateca_subordinates_restore -l verbosity

