# gcloud_alpha_init
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_init.1.gz
complete -c gcloud_alpha_init -l console-only -l no-launch-browser
complete -c gcloud_alpha_init -l skip-diagnostics
complete -c gcloud_alpha_init -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_init -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_init -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_init -l verbosity

