# gcloud_beta_firebase_test_ip-blocks_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_firebase_test_ip-blocks_list.1.gz
complete -c gcloud_beta_firebase_test_ip-blocks_list -l filter
complete -c gcloud_beta_firebase_test_ip-blocks_list -l sort-by -l limit
complete -c gcloud_beta_firebase_test_ip-blocks_list -l page-size
complete -c gcloud_beta_firebase_test_ip-blocks_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_firebase_test_ip-blocks_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_firebase_test_ip-blocks_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_firebase_test_ip-blocks_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_firebase_test_ip-blocks_list -l verbosity

