# gcloud_alpha_compute_instances_update-access-config
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_instances_update-access-config.1.gz
complete -c gcloud_alpha_compute_instances_update-access-config -l network-interface
complete -c gcloud_alpha_compute_instances_update-access-config -l network-tier
complete -c gcloud_alpha_compute_instances_update-access-config -l zone
complete -c gcloud_alpha_compute_instances_update-access-config -l no-ipv6-public-ptr
complete -c gcloud_alpha_compute_instances_update-access-config -l ipv6-public-ptr-domain
complete -c gcloud_alpha_compute_instances_update-access-config -l public-dns
complete -c gcloud_alpha_compute_instances_update-access-config -l no-public-dns
complete -c gcloud_alpha_compute_instances_update-access-config -l public-ptr
complete -c gcloud_alpha_compute_instances_update-access-config -l no-public-ptr
complete -c gcloud_alpha_compute_instances_update-access-config -l public-ptr-domain
complete -c gcloud_alpha_compute_instances_update-access-config -l no-public-ptr-domain
complete -c gcloud_alpha_compute_instances_update-access-config -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_instances_update-access-config -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_instances_update-access-config -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_instances_update-access-config -l verbosity

