# gcloud_compute_os-config_os-policy-assignments_create
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_os-config_os-policy-assignments_create.1.gz
complete -c gcloud_compute_os-config_os-policy-assignments_create -l location
complete -c gcloud_compute_os-config_os-policy-assignments_create -l file
complete -c gcloud_compute_os-config_os-policy-assignments_create -l async
complete -c gcloud_compute_os-config_os-policy-assignments_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_os-config_os-policy-assignments_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_os-config_os-policy-assignments_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_os-config_os-policy-assignments_create -l verbosity

