# gcloud_beta_ml_language_classify-text
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_ml_language_classify-text.1.gz
complete -c gcloud_beta_ml_language_classify-text -l content
complete -c gcloud_beta_ml_language_classify-text -l content-file
complete -c gcloud_beta_ml_language_classify-text -l content-type
complete -c gcloud_beta_ml_language_classify-text -l language
complete -c gcloud_beta_ml_language_classify-text -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_ml_language_classify-text -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_ml_language_classify-text -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_ml_language_classify-text -l verbosity

