# gcloud_beta_dataproc_workflow-templates_set-managed-cluster
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_dataproc_workflow-templates_set-managed-cluster.1.gz
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l region
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l autoscaling-policy
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l no-address
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l bucket
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l cluster-name
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l dataproc-metastore
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l enable-component-gateway
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l initialization-action-timeout
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l initialization-actions
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l labels
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l master-accelerator
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l master-boot-disk-size
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l master-boot-disk-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l master-machine-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l master-min-cpu-platform
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l node-group
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-master-local-ssds
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-masters
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-secondary-worker-local-ssds
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-worker-local-ssds
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l optional-components
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l private-ipv6-google-access-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l properties
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l secondary-worker-accelerator
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l secondary-worker-boot-disk-size
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l secondary-worker-boot-disk-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l shielded-integrity-monitoring
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l shielded-secure-boot
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l shielded-vtpm
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l temp-bucket
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l worker-accelerator
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l worker-boot-disk-size
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l worker-boot-disk-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l worker-machine-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l worker-min-cpu-platform
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l zone -s z
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l image
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l image-version
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-config-file
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l enable-kerberos
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-root-principal-password-uri
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-kms-key
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-kms-key-keyring
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-kms-key-location
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l kerberos-kms-key-project
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l metadata
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l scopes
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l service-account
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l tags
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l network
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l subnet
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l reservation
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l reservation-affinity
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l single-node
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-secondary-workers
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l num-workers
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l secondary-worker-type
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_dataproc_workflow-templates_set-managed-cluster -l verbosity

