# gcloud_beta_pubsub_schemas_validate-schema
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_pubsub_schemas_validate-schema.1.gz
complete -c gcloud_beta_pubsub_schemas_validate-schema -l type
complete -c gcloud_beta_pubsub_schemas_validate-schema -l definition
complete -c gcloud_beta_pubsub_schemas_validate-schema -l definition-file
complete -c gcloud_beta_pubsub_schemas_validate-schema -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_pubsub_schemas_validate-schema -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_pubsub_schemas_validate-schema -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_pubsub_schemas_validate-schema -l verbosity

