# gcloud_beta_dataflow_flex-template_build
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_dataflow_flex-template_build.1.gz
complete -c gcloud_beta_dataflow_flex-template_build -l sdk-language
complete -c gcloud_beta_dataflow_flex-template_build -l image
complete -c gcloud_beta_dataflow_flex-template_build -l env
complete -c gcloud_beta_dataflow_flex-template_build -l flex-template-base-image
complete -c gcloud_beta_dataflow_flex-template_build -l image-gcr-path
complete -c gcloud_beta_dataflow_flex-template_build -l jar
complete -c gcloud_beta_dataflow_flex-template_build -l py-path
complete -c gcloud_beta_dataflow_flex-template_build -l additional-experiments
complete -c gcloud_beta_dataflow_flex-template_build -l additional-user-labels
complete -c gcloud_beta_dataflow_flex-template_build -l dataflow-kms-key
complete -c gcloud_beta_dataflow_flex-template_build -l disable-public-ips
complete -c gcloud_beta_dataflow_flex-template_build -l enable-streaming-engine
complete -c gcloud_beta_dataflow_flex-template_build -l gcs-log-dir
complete -c gcloud_beta_dataflow_flex-template_build -l max-workers
complete -c gcloud_beta_dataflow_flex-template_build -l metadata-file
complete -c gcloud_beta_dataflow_flex-template_build -l network
complete -c gcloud_beta_dataflow_flex-template_build -l num-workers
complete -c gcloud_beta_dataflow_flex-template_build -l print-only
complete -c gcloud_beta_dataflow_flex-template_build -l service-account-email
complete -c gcloud_beta_dataflow_flex-template_build -l staging-location
complete -c gcloud_beta_dataflow_flex-template_build -l subnetwork
complete -c gcloud_beta_dataflow_flex-template_build -l temp-location
complete -c gcloud_beta_dataflow_flex-template_build -l worker-machine-type
complete -c gcloud_beta_dataflow_flex-template_build -l worker-region
complete -c gcloud_beta_dataflow_flex-template_build -l worker-zone
complete -c gcloud_beta_dataflow_flex-template_build -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_dataflow_flex-template_build -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_dataflow_flex-template_build -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_dataflow_flex-template_build -l verbosity

