# gcloud_alpha_resource-manager_org-policies_deny
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_resource-manager_org-policies_deny.1.gz
complete -c gcloud_alpha_resource-manager_org-policies_deny -l folder
complete -c gcloud_alpha_resource-manager_org-policies_deny -l organization
complete -c gcloud_alpha_resource-manager_org-policies_deny -l project
complete -c gcloud_alpha_resource-manager_org-policies_deny -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_resource-manager_org-policies_deny -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_resource-manager_org-policies_deny -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_resource-manager_org-policies_deny -l verbosity

