# gcloud_secrets_replication_update
# Autogenerated from man page /usr/share/man/man1/gcloud_secrets_replication_update.1.gz
complete -c gcloud_secrets_replication_update -l set-kms-key -d 'To set the CMEK key on a secret called my-secret to a specified KMS key in a …'
complete -c gcloud_secrets_replication_update -l location -d 'POSITIONAL ARGUMENTS Secret resource - The secret to update'
complete -c gcloud_secrets_replication_update -l remove-cmek
complete -c gcloud_secrets_replication_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_secrets_replication_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_secrets_replication_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_secrets_replication_update -l verbosity

