# gcloud_beta_healthcare_hl7v2-stores_export_gcs
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_healthcare_hl7v2-stores_export_gcs.1.gz
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l dataset
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l location
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l gcs-uri
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l async
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l end-time
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l message-view
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l start-time
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_healthcare_hl7v2-stores_export_gcs -l verbosity

