# gcloud_alpha_filestore_backups_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_filestore_backups_create.1.gz
complete -c gcloud_alpha_filestore_backups_create -l file-share
complete -c gcloud_alpha_filestore_backups_create -l instance
complete -c gcloud_alpha_filestore_backups_create -l instance-zone
complete -c gcloud_alpha_filestore_backups_create -l region
complete -c gcloud_alpha_filestore_backups_create -l async
complete -c gcloud_alpha_filestore_backups_create -l description
complete -c gcloud_alpha_filestore_backups_create -l labels
complete -c gcloud_alpha_filestore_backups_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_filestore_backups_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_filestore_backups_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_filestore_backups_create -l verbosity

