# gcloud_alpha_spanner_databases_ddl_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_spanner_databases_ddl_update.1.gz
complete -c gcloud_alpha_spanner_databases_ddl_update -l instance
complete -c gcloud_alpha_spanner_databases_ddl_update -l async
complete -c gcloud_alpha_spanner_databases_ddl_update -l ddl
complete -c gcloud_alpha_spanner_databases_ddl_update -l ddl-file
complete -c gcloud_alpha_spanner_databases_ddl_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_spanner_databases_ddl_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_spanner_databases_ddl_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_spanner_databases_ddl_update -l verbosity

