# gcloud_alpha_compute_org-security-policies_associations_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_org-security-policies_associations_delete.1.gz
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l security-policy
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l organization
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_org-security-policies_associations_delete -l verbosity

