# gcloud_alpha_artifacts_print-settings_npm
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_artifacts_print-settings_npm.1.gz
complete -c gcloud_alpha_artifacts_print-settings_npm -l json-key
complete -c gcloud_alpha_artifacts_print-settings_npm -l scope
complete -c gcloud_alpha_artifacts_print-settings_npm -l repository
complete -c gcloud_alpha_artifacts_print-settings_npm -l location
complete -c gcloud_alpha_artifacts_print-settings_npm -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_artifacts_print-settings_npm -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_artifacts_print-settings_npm -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_artifacts_print-settings_npm -l verbosity

