# gcloud_beta_tasks_queues_pause
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_tasks_queues_pause.1.gz
complete -c gcloud_beta_tasks_queues_pause -l location
complete -c gcloud_beta_tasks_queues_pause -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_tasks_queues_pause -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_tasks_queues_pause -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_tasks_queues_pause -l verbosity

