# gcloud_dns_record-sets_transaction_remove
# Autogenerated from man page /usr/share/man/man1/gcloud_dns_record-sets_transaction_remove.1.gz
complete -c gcloud_dns_record-sets_transaction_remove -l name
complete -c gcloud_dns_record-sets_transaction_remove -l ttl
complete -c gcloud_dns_record-sets_transaction_remove -l type
complete -c gcloud_dns_record-sets_transaction_remove -l zone -s z
complete -c gcloud_dns_record-sets_transaction_remove -l transaction-file
complete -c gcloud_dns_record-sets_transaction_remove -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dns_record-sets_transaction_remove -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dns_record-sets_transaction_remove -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dns_record-sets_transaction_remove -l verbosity

