# gcloud_alpha_container_backup-restore_restores_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_backup-restore_restores_create.1.gz
complete -c gcloud_alpha_container_backup-restore_restores_create -l location
complete -c gcloud_alpha_container_backup-restore_restores_create -l backup
complete -c gcloud_alpha_container_backup-restore_restores_create -l cluster
complete -c gcloud_alpha_container_backup-restore_restores_create -l cluster-resource-conflict-policy
complete -c gcloud_alpha_container_backup-restore_restores_create -l namespaced-resource-restore-mode
complete -c gcloud_alpha_container_backup-restore_restores_create -l all-namespaces
complete -c gcloud_alpha_container_backup-restore_restores_create -l selected-applications
complete -c gcloud_alpha_container_backup-restore_restores_create -l selected-namespaces
complete -c gcloud_alpha_container_backup-restore_restores_create -l cluster-resource-restore-scope
complete -c gcloud_alpha_container_backup-restore_restores_create -l description
complete -c gcloud_alpha_container_backup-restore_restores_create -l labels
complete -c gcloud_alpha_container_backup-restore_restores_create -l substitution-rules-file
complete -c gcloud_alpha_container_backup-restore_restores_create -l volume-data-restore-policy
complete -c gcloud_alpha_container_backup-restore_restores_create -l async
complete -c gcloud_alpha_container_backup-restore_restores_create -l wait-for-completion
complete -c gcloud_alpha_container_backup-restore_restores_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_backup-restore_restores_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_backup-restore_restores_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_backup-restore_restores_create -l verbosity

