# gcloud_beta_network-management_connectivity-tests_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_network-management_connectivity-tests_update.1.gz
complete -c gcloud_beta_network-management_connectivity-tests_update -l async
complete -c gcloud_beta_network-management_connectivity-tests_update -l description
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-network
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-port
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-project
complete -c gcloud_beta_network-management_connectivity-tests_update -l labels
complete -c gcloud_beta_network-management_connectivity-tests_update -l other-projects
complete -c gcloud_beta_network-management_connectivity-tests_update -l protocol
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-network
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-network-type
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-project
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-destination-cloud-sql-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-cloud-sql-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-destination-gke-master-cluster
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-gke-master-cluster
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-destination-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-destination-ip-address
complete -c gcloud_beta_network-management_connectivity-tests_update -l destination-ip-address
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-source-cloud-sql-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-cloud-sql-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-source-gke-master-cluster
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-gke-master-cluster
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-source-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-instance
complete -c gcloud_beta_network-management_connectivity-tests_update -l clear-source-ip-address
complete -c gcloud_beta_network-management_connectivity-tests_update -l source-ip-address
complete -c gcloud_beta_network-management_connectivity-tests_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_network-management_connectivity-tests_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_network-management_connectivity-tests_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_network-management_connectivity-tests_update -l verbosity

