# gcloud_alpha_container_backup-restore_backup-plans_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_backup-restore_backup-plans_create.1.gz
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l location -d 'the attributes of this resource'
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l cluster
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l all-namespaces
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l selected-applications
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l selected-namespaces
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l async
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l deactivated
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l description
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l labels
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l backup-delete-lock-days
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l backup-retain-days
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l locked
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l cron-schedule
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l paused
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l encryption-key
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l include-secrets
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l include-volume-data
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_backup-restore_backup-plans_create -l verbosity

