# gcloud_alpha_dns_policies_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dns_policies_update.1.gz
complete -c gcloud_alpha_dns_policies_update -l alternative-name-servers
complete -c gcloud_alpha_dns_policies_update -l description
complete -c gcloud_alpha_dns_policies_update -l enable-inbound-forwarding
complete -c gcloud_alpha_dns_policies_update -l enable-logging
complete -c gcloud_alpha_dns_policies_update -l networks
complete -c gcloud_alpha_dns_policies_update -l private-alternative-name-servers
complete -c gcloud_alpha_dns_policies_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dns_policies_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dns_policies_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dns_policies_update -l verbosity

