# gcloud_notebooks_instances_upgrade
# Autogenerated from man page /usr/share/man/man1/gcloud_notebooks_instances_upgrade.1.gz
complete -c gcloud_notebooks_instances_upgrade -l location
complete -c gcloud_notebooks_instances_upgrade -l async
complete -c gcloud_notebooks_instances_upgrade -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_notebooks_instances_upgrade -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_notebooks_instances_upgrade -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_notebooks_instances_upgrade -l verbosity

