# gcloud_beta_compute_https-health-checks_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_https-health-checks_update.1.gz
complete -c gcloud_beta_compute_https-health-checks_update -l check-interval
complete -c gcloud_beta_compute_https-health-checks_update -l description
complete -c gcloud_beta_compute_https-health-checks_update -l healthy-threshold
complete -c gcloud_beta_compute_https-health-checks_update -l host
complete -c gcloud_beta_compute_https-health-checks_update -l port
complete -c gcloud_beta_compute_https-health-checks_update -l request-path
complete -c gcloud_beta_compute_https-health-checks_update -l timeout
complete -c gcloud_beta_compute_https-health-checks_update -l unhealthy-threshold
complete -c gcloud_beta_compute_https-health-checks_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_https-health-checks_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_https-health-checks_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_https-health-checks_update -l verbosity

