# gcloud_beta_scheduler_jobs_create_app-engine
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_scheduler_jobs_create_app-engine.1.gz
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l location
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l schedule
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l attempt-deadline
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l description
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l headers
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l http-method
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l max-backoff
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l max-doublings
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l max-retry-attempts
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l max-retry-duration
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l min-backoff
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l relative-url
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l service
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l time-zone
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l version
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l message-body
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l message-body-from-file
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_scheduler_jobs_create_app-engine -l verbosity

