# gcloud_alpha_source_repos_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_source_repos_delete.1.gz
complete -c gcloud_alpha_source_repos_delete -l force
complete -c gcloud_alpha_source_repos_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_source_repos_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_source_repos_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_source_repos_delete -l verbosity

