# gcloud_beta_compute_config-ssh
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_config-ssh.1.gz
complete -c gcloud_beta_compute_config-ssh -l dry-run
complete -c gcloud_beta_compute_config-ssh -l force-key-file-overwrite
complete -c gcloud_beta_compute_config-ssh -l remove
complete -c gcloud_beta_compute_config-ssh -l ssh-config-file
complete -c gcloud_beta_compute_config-ssh -l ssh-key-file
complete -c gcloud_beta_compute_config-ssh -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_config-ssh -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_config-ssh -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_config-ssh -l verbosity

