# gcloud_alpha_compute_backend-services_get-health
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_backend-services_get-health.1.gz
complete -c gcloud_alpha_compute_backend-services_get-health -l global
complete -c gcloud_alpha_compute_backend-services_get-health -l region
complete -c gcloud_alpha_compute_backend-services_get-health -l filter
complete -c gcloud_alpha_compute_backend-services_get-health -l sort-by -l limit
complete -c gcloud_alpha_compute_backend-services_get-health -l page-size
complete -c gcloud_alpha_compute_backend-services_get-health -l flatten
complete -c gcloud_alpha_compute_backend-services_get-health -l uri
complete -c gcloud_alpha_compute_backend-services_get-health -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_compute_backend-services_get-health -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_backend-services_get-health -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_backend-services_get-health -l verbosity

