# gcloud_beta_compute_instances_update-from-file
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instances_update-from-file.1.gz
complete -c gcloud_beta_compute_instances_update-from-file -l minimal-action
complete -c gcloud_beta_compute_instances_update-from-file -l most-disruptive-allowed-action
complete -c gcloud_beta_compute_instances_update-from-file -l source
complete -c gcloud_beta_compute_instances_update-from-file -l zone
complete -c gcloud_beta_compute_instances_update-from-file -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instances_update-from-file -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instances_update-from-file -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instances_update-from-file -l verbosity

