# gcloud_beta_api-gateway_apis_create
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_api-gateway_apis_create.1.gz
complete -c gcloud_beta_api-gateway_apis_create -l async
complete -c gcloud_beta_api-gateway_apis_create -l display-name
complete -c gcloud_beta_api-gateway_apis_create -l labels
complete -c gcloud_beta_api-gateway_apis_create -l managed-service
complete -c gcloud_beta_api-gateway_apis_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_api-gateway_apis_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_api-gateway_apis_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_api-gateway_apis_create -l verbosity

