# gcloud_beta_pubsub_lite-subscriptions_subscribe
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_pubsub_lite-subscriptions_subscribe.1.gz
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l location
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l auto-ack
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l num-messages
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l partitions
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l verbosity

