# gcloud_alpha_compute_project-info_set-usage-bucket
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_project-info_set-usage-bucket.1.gz
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l bucket
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l no-bucket
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l prefix
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_project-info_set-usage-bucket -l verbosity

