# gcloud_dataproc_clusters_diagnose
# Autogenerated from man page /usr/share/man/man1/gcloud_dataproc_clusters_diagnose.1.gz
complete -c gcloud_dataproc_clusters_diagnose -l region
complete -c gcloud_dataproc_clusters_diagnose -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_dataproc_clusters_diagnose -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dataproc_clusters_diagnose -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dataproc_clusters_diagnose -l verbosity

