# gcloud_alpha_deployment-manager_resources
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_deployment-manager_resources.1.gz
complete -c gcloud_alpha_deployment-manager_resources -l deployment

