# gcloud_alpha_access-context-manager_perimeters_dry-run_list
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_access-context-manager_perimeters_dry-run_list.1.gz
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l - -d 'name: perimeter_2 spec:   resources:   - projects/789   restrictedServices:  …'
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l policy
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l filter
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l sort-by -l limit
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l page-size
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_access-context-manager_perimeters_dry-run_list -l verbosity

