# gcloud_alpha_container_images_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_images_describe.1.gz
complete -c gcloud_alpha_container_images_describe -l metadata-filter
complete -c gcloud_alpha_container_images_describe -l show-all-metadata
complete -c gcloud_alpha_container_images_describe -l show-build-details
complete -c gcloud_alpha_container_images_describe -l show-deployment
complete -c gcloud_alpha_container_images_describe -l show-image-basis
complete -c gcloud_alpha_container_images_describe -l show-package-vulnerability
complete -c gcloud_alpha_container_images_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_container_images_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_images_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_images_describe -l verbosity

