# gcloud_scc_assets_list
# Autogenerated from man page /usr/share/man/man1/gcloud_scc_assets_list.1.gz
complete -c gcloud_scc_assets_list -l compare-duration
complete -c gcloud_scc_assets_list -l field-mask
complete -c gcloud_scc_assets_list -l order-by
complete -c gcloud_scc_assets_list -l page-token
complete -c gcloud_scc_assets_list -l read-time
complete -c gcloud_scc_assets_list -l filter
complete -c gcloud_scc_assets_list -l sort-by -l limit
complete -c gcloud_scc_assets_list -l page-size
complete -c gcloud_scc_assets_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_scc_assets_list -l billing-project -l configuration -l flags-file
complete -c gcloud_scc_assets_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_scc_assets_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_scc_assets_list -l verbosity

