# gcloud_kms_keys_versions_create
# Autogenerated from man page /usr/share/man/man1/gcloud_kms_keys_versions_create.1.gz
complete -c gcloud_kms_keys_versions_create -l external-key-uri
complete -c gcloud_kms_keys_versions_create -l key
complete -c gcloud_kms_keys_versions_create -l keyring
complete -c gcloud_kms_keys_versions_create -l location
complete -c gcloud_kms_keys_versions_create -l primary
complete -c gcloud_kms_keys_versions_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_kms_keys_versions_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_kms_keys_versions_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_kms_keys_versions_create -l verbosity

