# gcloud_notebooks_instances_rollback
# Autogenerated from man page /usr/share/man/man1/gcloud_notebooks_instances_rollback.1.gz
complete -c gcloud_notebooks_instances_rollback -l location
complete -c gcloud_notebooks_instances_rollback -l target-snapshot
complete -c gcloud_notebooks_instances_rollback -l async
complete -c gcloud_notebooks_instances_rollback -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_notebooks_instances_rollback -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_notebooks_instances_rollback -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_notebooks_instances_rollback -l verbosity

