# gcloud_kms_import-jobs_describe
# Autogenerated from man page /usr/share/man/man1/gcloud_kms_import-jobs_describe.1.gz
complete -c gcloud_kms_import-jobs_describe -l attestation-file -d '$ gcloud kms import-jobs describe strider --keyring=fellowship \\     --locati…'
complete -c gcloud_kms_import-jobs_describe -l keyring
complete -c gcloud_kms_import-jobs_describe -l location
complete -c gcloud_kms_import-jobs_describe -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_kms_import-jobs_describe -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_kms_import-jobs_describe -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_kms_import-jobs_describe -l verbosity

