# gcloud_spanner_databases_create
# Autogenerated from man page /usr/share/man/man1/gcloud_spanner_databases_create.1.gz
complete -c gcloud_spanner_databases_create -l instance
complete -c gcloud_spanner_databases_create -l async
complete -c gcloud_spanner_databases_create -l ddl
complete -c gcloud_spanner_databases_create -l ddl-file
complete -c gcloud_spanner_databases_create -l ddl_file -d 'Key resource - Cloud KMS key to be used to create the Cloud Spanner database'
complete -c gcloud_spanner_databases_create -l kms-key
complete -c gcloud_spanner_databases_create -l kms-keyring
complete -c gcloud_spanner_databases_create -l kms-location
complete -c gcloud_spanner_databases_create -l kms-project
complete -c gcloud_spanner_databases_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_spanner_databases_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_spanner_databases_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_spanner_databases_create -l verbosity

