# gcloud_network-management_connectivity-tests_delete
# Autogenerated from man page /usr/share/man/man1/gcloud_network-management_connectivity-tests_delete.1.gz
complete -c gcloud_network-management_connectivity-tests_delete -l async
complete -c gcloud_network-management_connectivity-tests_delete -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_network-management_connectivity-tests_delete -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_network-management_connectivity-tests_delete -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_network-management_connectivity-tests_delete -l verbosity

