# gcloud_compute_instances_update
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_instances_update.1.gz
complete -c gcloud_compute_instances_update -l deletion-protection
complete -c gcloud_compute_instances_update -l enable-display-device
complete -c gcloud_compute_instances_update -l min-cpu-platform
complete -c gcloud_compute_instances_update -l shielded-integrity-monitoring
complete -c gcloud_compute_instances_update -l shielded-learn-integrity-policy
complete -c gcloud_compute_instances_update -l shielded-secure-boot
complete -c gcloud_compute_instances_update -l no-shielded-secure-boot
complete -c gcloud_compute_instances_update -l shielded-vtpm
complete -c gcloud_compute_instances_update -l no-shielded-vtpm
complete -c gcloud_compute_instances_update -l update-labels
complete -c gcloud_compute_instances_update -l zone
complete -c gcloud_compute_instances_update -l clear-labels
complete -c gcloud_compute_instances_update -l remove-labels
complete -c gcloud_compute_instances_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_instances_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_instances_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_instances_update -l verbosity

