# gcloud_alpha_apigee_products_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_apigee_products_create.1.gz
complete -c gcloud_alpha_apigee_products_create -l organization
complete -c gcloud_alpha_apigee_products_create -l attributes
complete -c gcloud_alpha_apigee_products_create -l description
complete -c gcloud_alpha_apigee_products_create -l display-name
complete -c gcloud_alpha_apigee_products_create -l manual-approval
complete -c gcloud_alpha_apigee_products_create -l oauth-scopes
complete -c gcloud_alpha_apigee_products_create -l all-environments
complete -c gcloud_alpha_apigee_products_create -l environments
complete -c gcloud_alpha_apigee_products_create -l all-proxies
complete -c gcloud_alpha_apigee_products_create -l apis
complete -c gcloud_alpha_apigee_products_create -l resources
complete -c gcloud_alpha_apigee_products_create -l internal-access
complete -c gcloud_alpha_apigee_products_create -l private-access
complete -c gcloud_alpha_apigee_products_create -l public-access
complete -c gcloud_alpha_apigee_products_create -l quota
complete -c gcloud_alpha_apigee_products_create -l quota-interval
complete -c gcloud_alpha_apigee_products_create -l quota-unit
complete -c gcloud_alpha_apigee_products_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_apigee_products_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_apigee_products_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_apigee_products_create -l verbosity

