# gcloud_compute_os-login_ssh-keys_list
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_os-login_ssh-keys_list.1.gz
complete -c gcloud_compute_os-login_ssh-keys_list -l format -d EXAMPLES
complete -c gcloud_compute_os-login_ssh-keys_list -l filter
complete -c gcloud_compute_os-login_ssh-keys_list -l sort-by -l limit
complete -c gcloud_compute_os-login_ssh-keys_list -l page-size
complete -c gcloud_compute_os-login_ssh-keys_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_compute_os-login_ssh-keys_list -l billing-project -l configuration -l flags-file
complete -c gcloud_compute_os-login_ssh-keys_list -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_os-login_ssh-keys_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_os-login_ssh-keys_list -l verbosity

