# gcloud_alpha_iam_policies_lint-condition
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_iam_policies_lint-condition.1.gz
complete -c gcloud_alpha_iam_policies_lint-condition -l condition-from-file
complete -c gcloud_alpha_iam_policies_lint-condition -l expression
complete -c gcloud_alpha_iam_policies_lint-condition -l title
complete -c gcloud_alpha_iam_policies_lint-condition -l description
complete -c gcloud_alpha_iam_policies_lint-condition -l resource-name
complete -c gcloud_alpha_iam_policies_lint-condition -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_iam_policies_lint-condition -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_iam_policies_lint-condition -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_iam_policies_lint-condition -l verbosity

