# gcloud_alpha_compute_networks_subnets_list-usable
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_networks_subnets_list-usable.1.gz
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l project -l account -d EXAMPLES
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l service-project
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l filter
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l sort-by -l limit
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l page-size
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l flatten
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l uri
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_networks_subnets_list-usable -l verbosity

