# gcloud_beta_access-context-manager_perimeters_replace-all
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_access-context-manager_perimeters_replace-all.1.gz
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l source-file
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l etag
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_access-context-manager_perimeters_replace-all -l verbosity

