# gcloud_tasks_run
# Autogenerated from man page /usr/share/man/man1/gcloud_tasks_run.1.gz
complete -c gcloud_tasks_run -l location
complete -c gcloud_tasks_run -l queue
complete -c gcloud_tasks_run -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_tasks_run -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_tasks_run -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_tasks_run -l verbosity

