# gcloud_alpha_network-services_service-bindings_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_network-services_service-bindings_create.1.gz
complete -c gcloud_alpha_network-services_service-bindings_create -l location
complete -c gcloud_alpha_network-services_service-bindings_create -l service-directory-namespace
complete -c gcloud_alpha_network-services_service-bindings_create -l service-directory-region
complete -c gcloud_alpha_network-services_service-bindings_create -l service-directory-service
complete -c gcloud_alpha_network-services_service-bindings_create -l async
complete -c gcloud_alpha_network-services_service-bindings_create -l description
complete -c gcloud_alpha_network-services_service-bindings_create -l service-directory-filter
complete -c gcloud_alpha_network-services_service-bindings_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_network-services_service-bindings_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_network-services_service-bindings_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_network-services_service-bindings_create -l verbosity

