# gcloud_sql_backups_restore
# Autogenerated from man page /usr/share/man/man1/gcloud_sql_backups_restore.1.gz
complete -c gcloud_sql_backups_restore -l restore-instance
complete -c gcloud_sql_backups_restore -l async
complete -c gcloud_sql_backups_restore -l backup-instance
complete -c gcloud_sql_backups_restore -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_sql_backups_restore -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_sql_backups_restore -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_sql_backups_restore -l verbosity

