# gcloud_scheduler_jobs_update_pubsub
# Autogenerated from man page /usr/share/man/man1/gcloud_scheduler_jobs_update_pubsub.1.gz
complete -c gcloud_scheduler_jobs_update_pubsub -l location
complete -c gcloud_scheduler_jobs_update_pubsub -l description
complete -c gcloud_scheduler_jobs_update_pubsub -l schedule
complete -c gcloud_scheduler_jobs_update_pubsub -l topic
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-attributes
complete -c gcloud_scheduler_jobs_update_pubsub -l remove-attributes
complete -c gcloud_scheduler_jobs_update_pubsub -l update-attributes
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-max-backoff
complete -c gcloud_scheduler_jobs_update_pubsub -l max-backoff
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-max-doublings
complete -c gcloud_scheduler_jobs_update_pubsub -l max-doublings
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-max-retry-attempts
complete -c gcloud_scheduler_jobs_update_pubsub -l max-retry-attempts
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-max-retry-duration
complete -c gcloud_scheduler_jobs_update_pubsub -l max-retry-duration
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-min-backoff
complete -c gcloud_scheduler_jobs_update_pubsub -l min-backoff
complete -c gcloud_scheduler_jobs_update_pubsub -l clear-time-zone
complete -c gcloud_scheduler_jobs_update_pubsub -l time-zone
complete -c gcloud_scheduler_jobs_update_pubsub -l message-body
complete -c gcloud_scheduler_jobs_update_pubsub -l message-body-from-file
complete -c gcloud_scheduler_jobs_update_pubsub -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_scheduler_jobs_update_pubsub -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_scheduler_jobs_update_pubsub -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_scheduler_jobs_update_pubsub -l verbosity

