# gcloud_alpha_monitoring_policies_conditions_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_monitoring_policies_conditions_update.1.gz
complete -c gcloud_alpha_monitoring_policies_conditions_update -l policy
complete -c gcloud_alpha_monitoring_policies_conditions_update -l display-name
complete -c gcloud_alpha_monitoring_policies_conditions_update -l if
complete -c gcloud_alpha_monitoring_policies_conditions_update -l trigger-count
complete -c gcloud_alpha_monitoring_policies_conditions_update -l trigger-percent
complete -c gcloud_alpha_monitoring_policies_conditions_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_monitoring_policies_conditions_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_monitoring_policies_conditions_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_monitoring_policies_conditions_update -l verbosity

