# gcloud_alpha_network-connectivity_spokes_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_network-connectivity_spokes_create.1.gz
complete -c gcloud_alpha_network-connectivity_spokes_create -l region
complete -c gcloud_alpha_network-connectivity_spokes_create -l hub
complete -c gcloud_alpha_network-connectivity_spokes_create -l interconnect-attachment
complete -c gcloud_alpha_network-connectivity_spokes_create -l router-appliance
complete -c gcloud_alpha_network-connectivity_spokes_create -l vpn-tunnel
complete -c gcloud_alpha_network-connectivity_spokes_create -l async
complete -c gcloud_alpha_network-connectivity_spokes_create -l description
complete -c gcloud_alpha_network-connectivity_spokes_create -l labels
complete -c gcloud_alpha_network-connectivity_spokes_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_network-connectivity_spokes_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_network-connectivity_spokes_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_network-connectivity_spokes_create -l verbosity

