# gcloud_beta_compute_forwarding-rules_export
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_forwarding-rules_export.1.gz
complete -c gcloud_beta_compute_forwarding-rules_export -l destination
complete -c gcloud_beta_compute_forwarding-rules_export -l global
complete -c gcloud_beta_compute_forwarding-rules_export -l region
complete -c gcloud_beta_compute_forwarding-rules_export -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_forwarding-rules_export -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_forwarding-rules_export -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_forwarding-rules_export -l verbosity

