# gcloud_alpha_container_backup-restore_backup-plans_list
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_container_backup-restore_backup-plans_list.1.gz
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l location -d 'attributes are not given arguments in this group but can be set in other ways'
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l filter
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l sort-by -l limit
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l page-size
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l flatten
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l uri
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_container_backup-restore_backup-plans_list -l verbosity

