# gcloud_app_open-console
# Autogenerated from man page /usr/share/man/man1/gcloud_app_open-console.1.gz
complete -c gcloud_app_open-console -l logs -s l
complete -c gcloud_app_open-console -l service -s s
complete -c gcloud_app_open-console -l version -s v
complete -c gcloud_app_open-console -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_app_open-console -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_app_open-console -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_app_open-console -l verbosity

