# gcloud_alpha_builds_enterprise-config_bitbucketserver_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_builds_enterprise-config_bitbucketserver_update.1.gz
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l admin-access-token-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l api-key
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l host-uri
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l read-access-token-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l user-name
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l webhook-secret-secret-version
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_builds_enterprise-config_bitbucketserver_update -l verbosity

