# gcloud_beta_compute_disks_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_disks_update.1.gz
complete -c gcloud_beta_compute_disks_update -l update-labels
complete -c gcloud_beta_compute_disks_update -l clear-labels
complete -c gcloud_beta_compute_disks_update -l remove-labels
complete -c gcloud_beta_compute_disks_update -l clear-user-licenses
complete -c gcloud_beta_compute_disks_update -l update-user-licenses
complete -c gcloud_beta_compute_disks_update -l region
complete -c gcloud_beta_compute_disks_update -l zone
complete -c gcloud_beta_compute_disks_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_disks_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_disks_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_disks_update -l verbosity

