# gcloud_alpha_resource-manager_org-policies_set-policy
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_resource-manager_org-policies_set-policy.1.gz
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l folder
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l organization
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l project
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_resource-manager_org-policies_set-policy -l verbosity

