# gcloud_beta_artifacts_docker_tags_add
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_artifacts_docker_tags_add.1.gz
complete -c gcloud_beta_artifacts_docker_tags_add -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_artifacts_docker_tags_add -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_artifacts_docker_tags_add -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_artifacts_docker_tags_add -l verbosity

