# gcloud_alpha_dlp_text_inspect
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_dlp_text_inspect.1.gz
complete -c gcloud_alpha_dlp_text_inspect -l content
complete -c gcloud_alpha_dlp_text_inspect -l content-file
complete -c gcloud_alpha_dlp_text_inspect -l exclude-info-types
complete -c gcloud_alpha_dlp_text_inspect -l include-quote
complete -c gcloud_alpha_dlp_text_inspect -l info-types
complete -c gcloud_alpha_dlp_text_inspect -l max-findings
complete -c gcloud_alpha_dlp_text_inspect -l min-likelihood
complete -c gcloud_alpha_dlp_text_inspect -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_dlp_text_inspect -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_dlp_text_inspect -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_dlp_text_inspect -l verbosity

