# gcloud_beta_events_types_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_events_types_list.1.gz
complete -c gcloud_beta_events_types_list -l platform
complete -c gcloud_beta_events_types_list -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_types_list -l source
complete -c gcloud_beta_events_types_list -l cluster
complete -c gcloud_beta_events_types_list -l context
complete -c gcloud_beta_events_types_list -l kubeconfig
complete -c gcloud_beta_events_types_list -l filter
complete -c gcloud_beta_events_types_list -l sort-by -l limit
complete -c gcloud_beta_events_types_list -l page-size
complete -c gcloud_beta_events_types_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_events_types_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_events_types_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_events_types_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_events_types_list -l verbosity

