# gcloud_beta_compute_instance-groups_managed_rolling-action_restart
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instance-groups_managed_rolling-action_restart.1.gz
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l max-unavailable
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l min-ready
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l region
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l zone
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instance-groups_managed_rolling-action_restart -l verbosity

