# gcloud_beta_eventarc_attributes_method-names_list
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_eventarc_attributes_method-names_list.1.gz
complete -c gcloud_beta_eventarc_attributes_method-names_list -l service-name
complete -c gcloud_beta_eventarc_attributes_method-names_list -l type
complete -c gcloud_beta_eventarc_attributes_method-names_list -l filter
complete -c gcloud_beta_eventarc_attributes_method-names_list -l sort-by -l limit
complete -c gcloud_beta_eventarc_attributes_method-names_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_eventarc_attributes_method-names_list -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_eventarc_attributes_method-names_list -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_eventarc_attributes_method-names_list -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_eventarc_attributes_method-names_list -l verbosity

