# gcloud_alpha_game_servers_realms_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_game_servers_realms_update.1.gz
complete -c gcloud_alpha_game_servers_realms_update -l location
complete -c gcloud_alpha_game_servers_realms_update -l dry-run
complete -c gcloud_alpha_game_servers_realms_update -l description
complete -c gcloud_alpha_game_servers_realms_update -l preview-time
complete -c gcloud_alpha_game_servers_realms_update -l time-zone
complete -c gcloud_alpha_game_servers_realms_update -l update-labels
complete -c gcloud_alpha_game_servers_realms_update -l clear-labels
complete -c gcloud_alpha_game_servers_realms_update -l remove-labels
complete -c gcloud_alpha_game_servers_realms_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_game_servers_realms_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_game_servers_realms_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_game_servers_realms_update -l verbosity

