# gcloud_beta_events_types_sources
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_events_types_sources.1.gz
complete -c gcloud_beta_events_types_sources -l platform
complete -c gcloud_beta_events_types_sources -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_types_sources -l cluster
complete -c gcloud_beta_events_types_sources -l context
complete -c gcloud_beta_events_types_sources -l kubeconfig

