# gcloud_beta_compute_instance-groups_managed_list-errors
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_compute_instance-groups_managed_list-errors.1.gz
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l region
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l zone
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l filter
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l sort-by -l limit
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l page-size
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l flatten
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l uri
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l billing-project -l configuration -l flags-file
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_compute_instance-groups_managed_list-errors -l verbosity

