# gcloud_alpha_builds_worker-pools_update
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_builds_worker-pools_update.1.gz
complete -c gcloud_alpha_builds_worker-pools_update -l region
complete -c gcloud_alpha_builds_worker-pools_update -l config-from-file
complete -c gcloud_alpha_builds_worker-pools_update -l no-external-ip
complete -c gcloud_alpha_builds_worker-pools_update -l worker-disk-size
complete -c gcloud_alpha_builds_worker-pools_update -l worker-machine-type
complete -c gcloud_alpha_builds_worker-pools_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_builds_worker-pools_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_builds_worker-pools_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_builds_worker-pools_update -l verbosity

