# gcloud_beta_app_firewall-rules_update
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_app_firewall-rules_update.1.gz
complete -c gcloud_beta_app_firewall-rules_update -l action
complete -c gcloud_beta_app_firewall-rules_update -l description
complete -c gcloud_beta_app_firewall-rules_update -l source-range
complete -c gcloud_beta_app_firewall-rules_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_app_firewall-rules_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_app_firewall-rules_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_app_firewall-rules_update -l verbosity

