# gcloud_alpha_compute_instances_get-guest-attributes
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_instances_get-guest-attributes.1.gz
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l zone
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l query-path
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_instances_get-guest-attributes -l verbosity

