# gcloud_alpha_iam_service-accounts_keys_upload
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_iam_service-accounts_keys_upload.1.gz
complete -c gcloud_alpha_iam_service-accounts_keys_upload -l iam-account
complete -c gcloud_alpha_iam_service-accounts_keys_upload -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_iam_service-accounts_keys_upload -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_iam_service-accounts_keys_upload -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_iam_service-accounts_keys_upload -l verbosity

