# gcloud_dns_record-sets_transaction_execute
# Autogenerated from man page /usr/share/man/man1/gcloud_dns_record-sets_transaction_execute.1.gz
complete -c gcloud_dns_record-sets_transaction_execute -l zone -s z
complete -c gcloud_dns_record-sets_transaction_execute -l transaction-file
complete -c gcloud_dns_record-sets_transaction_execute -l filter
complete -c gcloud_dns_record-sets_transaction_execute -l sort-by -l limit
complete -c gcloud_dns_record-sets_transaction_execute -l page-size
complete -c gcloud_dns_record-sets_transaction_execute -l flatten
complete -c gcloud_dns_record-sets_transaction_execute -l uri
complete -c gcloud_dns_record-sets_transaction_execute -l billing-project -l configuration -l flags-file
complete -c gcloud_dns_record-sets_transaction_execute -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_dns_record-sets_transaction_execute -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_dns_record-sets_transaction_execute -l verbosity

