# gcloud_compute_routers_remove-bgp-peer
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_routers_remove-bgp-peer.1.gz
complete -c gcloud_compute_routers_remove-bgp-peer -l peer-name
complete -c gcloud_compute_routers_remove-bgp-peer -l peer-names
complete -c gcloud_compute_routers_remove-bgp-peer -l region
complete -c gcloud_compute_routers_remove-bgp-peer -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_compute_routers_remove-bgp-peer -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_routers_remove-bgp-peer -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_routers_remove-bgp-peer -l verbosity

