# gcloud_alpha_iam_service-accounts_keys_get-public-key
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_iam_service-accounts_keys_get-public-key.1.gz
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l iam-account
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l output-file
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l type
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_iam_service-accounts_keys_get-public-key -l verbosity

