# gcloud_alpha_compute_url-maps_create
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_url-maps_create.1.gz
complete -c gcloud_alpha_compute_url-maps_create -l default-backend-bucket
complete -c gcloud_alpha_compute_url-maps_create -l default-service
complete -c gcloud_alpha_compute_url-maps_create -l description
complete -c gcloud_alpha_compute_url-maps_create -l global
complete -c gcloud_alpha_compute_url-maps_create -l region
complete -c gcloud_alpha_compute_url-maps_create -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_alpha_compute_url-maps_create -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_url-maps_create -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_url-maps_create -l verbosity

