# gcloud_identity_groups_update
# Autogenerated from man page /usr/share/man/man1/gcloud_identity_groups_update.1.gz
complete -c gcloud_identity_groups_update -l dynamic-user-query
complete -c gcloud_identity_groups_update -l labels
complete -c gcloud_identity_groups_update -l clear-description
complete -c gcloud_identity_groups_update -l description
complete -c gcloud_identity_groups_update -l clear-display-name
complete -c gcloud_identity_groups_update -l display-name
complete -c gcloud_identity_groups_update -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_identity_groups_update -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_identity_groups_update -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_identity_groups_update -l verbosity

