# gcloud_alpha_compute_routers_get-nat-mapping-info
# Autogenerated from man page /usr/share/man/man1/gcloud_alpha_compute_routers_get-nat-mapping-info.1.gz
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l nat-name
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l region
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l filter
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l sort-by -l limit
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l page-size
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l billing-project -l configuration -l flags-file
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_alpha_compute_routers_get-nat-mapping-info -l verbosity

