# gcloud_beta_privateca_subordinates_get-csr
# Autogenerated from man page /usr/share/man/man1/gcloud_beta_privateca_subordinates_get-csr.1.gz
complete -c gcloud_beta_privateca_subordinates_get-csr -l location
complete -c gcloud_beta_privateca_subordinates_get-csr -l billing-project -l configuration -l flags-file -l flatten
complete -c gcloud_beta_privateca_subordinates_get-csr -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_beta_privateca_subordinates_get-csr -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_beta_privateca_subordinates_get-csr -l verbosity

