# gcloud_compute_network-endpoint-groups_list-network-endpoints
# Autogenerated from man page /usr/share/man/man1/gcloud_compute_network-endpoint-groups_list-network-endpoints.1.gz
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l global
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l zone
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l filter
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l sort-by -l limit
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l page-size
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l billing-project -l configuration -l flags-file
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l format -l help -l impersonate-service-account -l log-http
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l project -l quiet -l trace-token -l user-output-enabled
complete -c gcloud_compute_network-endpoint-groups_list-network-endpoints -l verbosity

