# growisofs
# Autogenerated from man page /usr/share/man/man1/growisofs.1.gz
complete -c growisofs -o Z/dev/dvd -d 'Burn an initial session to the selected device'
complete -c growisofs -o M/dev/dvd -d 'Merge a new session to an existing one'
complete -c growisofs -o version -d 'Print version information and invoke genisoimage, also with -version option'
complete -c growisofs -o dvd-compat -d 'Provide maximum media compatibility with DVD-ROM/-Video'
complete -c growisofs -o dry-run -d 'At dry-run growisofs performs all the steps till, but not including the first…'
complete -c growisofs -o overburn -d 'Normally single layer DVD media can accommodate up to approximately 4. 700'
complete -c growisofs -o speed -d 'An option to control recording velocity'
complete -c growisofs -s Z -d 'Burn an initial session to the selected device'
complete -c growisofs -s M -d 'Merge a new session to an existing one'
complete -c growisofs -o use-the-force-luke -d purposes
complete -c growisofs -s o -d 'option for an output file.  growisofs dumps the image directly to the media;'
complete -c growisofs -s C -d 'option to create a higher level session on a multisession disk, growisofs  wi…'

