# gyp
# Autogenerated from man page /usr/share/man/man1/gyp.1.gz
complete -c gyp -o 'D<variable>' -d 'Provide a default value for the given variable'
complete -c gyp -o 'f<format>' -l format -d 'Generate output in the formats listed'
complete -c gyp -o 'I<path>' -l include -d 'Implicitly include the contents of the <path> file in all loaded . gyp files'
complete -c gyp -l depth -d 'For Chromium, the gyp "depth" variable should always be a relative path to Ch…'
complete -c gyp -o 'd<debug' -l debug -d 'Turn on debugging output'
complete -c gyp -o 'S<suffix>' -l suffix -d 'Insert the specified string in the names of generated files before the standa…'
complete -c gyp -o 'G<flag>' -d 'Set a "generator flag", which is an option specific to the particular output …'
complete -c gyp -l generator-output -d 'Write the generated build files under the <dir> directory and adjust paths ac…'
complete -c gyp -l ignore-environment -d 'Do not read options from environment variables'
complete -c gyp -l check -d 'Take extra time to verify the syntax of each build_file'
complete -c gyp -l parallel -d 'Use multiprocessing for speed (experimental)'
complete -c gyp -l toplevel-dir -d 'Directory to use as the root of the source tree'
complete -c gyp -l build -d 'Configuration for build after project generation'
complete -c gyp -l no-circular-check -d 'Disable the check for circular relationships between . gyp files'
complete -c gyp -s D
complete -c gyp -s G

