# i386
# Autogenerated from man page /usr/share/man/man8/i386.8.gz
complete -c i386 -l list -d 'List the architectures that setarch knows about'
complete -c i386 -l 'uname-2.6' -d 'Causes the program to see a kernel version number beginning with 2. 6'
complete -c i386 -s v -l verbose -d 'Be verbose'
complete -c i386 -s 3 -l 3gb -d 'Specifies  program should use a maximum of 3GB of address space'
complete -c i386 -l 4gb -d 'This option has no effect'
complete -c i386 -s B -l 32bit -d 'Limit the address space to 32 bits to emulate hardware'
complete -c i386 -s F -l fdpic-funcptrs -d 'Treat user-space function pointers to signal handlers as pointers to address …'
complete -c i386 -s I -l short-inode -d 'Obsolete bug emulation flag.   Turns on SHORT_INODE'
complete -c i386 -s L -l addr-compat-layout -d 'Provide legacy virtual address space layout'
complete -c i386 -s R -l addr-no-randomize -d 'Disables randomization of the virtual address space'
complete -c i386 -s S -l whole-seconds -d 'Obsolete bug emulation flag.   Turns on WHOLE_SECONDS'
complete -c i386 -s T -l sticky-timeouts -d 'This makes  select (2),  pselect (2), and  ppoll (2) system calls preserve th…'
complete -c i386 -s X -l read-implies-exec -d 'If this is set then  mmap (3) PROT_READ will also add the PROT_EXEC bit - as …'
complete -c i386 -s Z -l mmap-page-zero -d 'SVr4 bug emulation that will set  mmap (3) page zero as read-only'
complete -c i386 -s V -l version -d 'Display version information and exit'
complete -c i386 -s h -l help -d 'Display help text and exit.  EXAMPLES setarch --addr-no-randomize mytestprog'

