# icuinfo
# Autogenerated from man page /usr/share/man/man1/icuinfo.1.gz
complete -c icuinfo -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c icuinfo -s V -l version -d 'Print the version of  icuinfo and exit'
complete -c icuinfo -s c -l copyright -d 'Embeds the standard ICU copyright into the R output-file '
complete -c icuinfo -s v -l verbose -d 'Display extra informative messages during execution'
complete -c icuinfo -s i -l icudatadir -d 'Look for any necessary ICU data files in R directory '
complete -c icuinfo -s L -l list-plugins -d 'If specified, list and diagnose issues with ICU plugins'
complete -c icuinfo -s K -l cleanup -d 'Attempt to unload plugins before exiting'
complete -c icuinfo -s m -l milisecond-time -d 'Print the current UTC time in milliseconds'

