# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1.gz
complete -c ipcrm -s a -l all -d 'Remove all resources'
complete -c ipcrm -s M -l shmem-key -d 'Remove the shared memory segment created with  shmkey after the last detach i…'
complete -c ipcrm -s m -l shmem-id -d 'Remove the shared memory segment identified by  shmid after the last detach i…'
complete -c ipcrm -s Q -l queue-key -d 'Remove the message queue created with R msgkey '
complete -c ipcrm -s q -l queue-id -d 'Remove the message queue identified by R msgid '
complete -c ipcrm -s S -l semaphore-key -d 'Remove the semaphore created with R semkey '
complete -c ipcrm -s s -l semaphore-id -d 'Remove the semaphore identified by R semid '
complete -c ipcrm -s V -l version -d 'Display version information and exit'
complete -c ipcrm -s h -l help -d 'Display help text and exit'

