# kbuildsycoca5
# Autogenerated from man page /usr/share/man/man8/kbuildsycoca5.8.gz
complete -c kbuildsycoca5 -l global -d 'Ignores any user-set files (in XDG_DATA_HOME)'
complete -c kbuildsycoca5 -l noincremental -d 'Rather than using the existing cache and only updating the information that h…'
complete -c kbuildsycoca5 -l nosignal -d 'Ordinarily, kbuildsyscoca5 sends a signal over D-Bus once the cache is update…'
complete -c kbuildsycoca5 -l menutest -d 'Test the generation of the application menu database'
complete -c kbuildsycoca5 -l testmode -d 'Use the QStandardPaths "test mode" to avoid interfering with user data'
complete -c kbuildsycoca5 -l track -d 'Track a menu ID for debugging'
complete -c kbuildsycoca5 -l author -d 'Show author information'
complete -c kbuildsycoca5 -l license -d 'Show license information'
complete -c kbuildsycoca5 -s h -l help -d 'Show a brief help text'
complete -c kbuildsycoca5 -s v -l version -d 'Show version information'

