# kpackagetool5
# Autogenerated from man page /usr/share/man/man1/kpackagetool5.1.gz
complete -c kpackagetool5 -s v -l version -d 'Displays version information'
complete -c kpackagetool5 -s h -l help -d 'Displays this help'
complete -c kpackagetool5 -l hash -d 'Generate a SHA1 hash for the package at \\(lqpath\\(rq'
complete -c kpackagetool5 -s g -l global -d 'For install or remove, operates on packages installed for all users'
complete -c kpackagetool5 -s t -l type -d 'The type of package, corresponding to the service type of the package plugin,…'
complete -c kpackagetool5 -s i -l install -d 'Install the package at \\(lqpath\\(rq'
complete -c kpackagetool5 -s s -l show -d 'Show information of package \\(lqname\\(rq'
complete -c kpackagetool5 -s u -l upgrade -d 'Upgrade the package at \\(lqpath\\(rq'
complete -c kpackagetool5 -s l -l list -d 'List installed packages'
complete -c kpackagetool5 -l list-types -d 'Lists all known Package types that can be installed'
complete -c kpackagetool5 -s r -l remove -d 'Remove the package named \\(lqname\\(rq'
complete -c kpackagetool5 -s p -l packageroot -d 'Absolute path to the package root'
complete -c kpackagetool5 -l generate-index -d 'Recreate the plugin index'

