# mountpoint
# Autogenerated from man page /usr/share/man/man1/mountpoint.1.gz
complete -c mountpoint -s d -l fs-devno -d 'Show the major/minor numbers of the device that is mounted on the given direc…'
complete -c mountpoint -s q -l quiet -d 'Be quiet - don\'t print anything'
complete -c mountpoint -s x -l devno -d 'Show the major/minor numbers of the given blockdevice on standard output'
complete -c mountpoint -s V -l version -d 'Display version information and exit'
complete -c mountpoint -s h -l help -d 'Display help text and exit'

