# mpeg2desc
# Autogenerated from man page /usr/share/man/man1/mpeg2desc.1.gz
complete -c mpeg2desc -s a -d 'Output audio stream (0 .  31) to stdout'
complete -c mpeg2desc -s v -d 'Output video stream (0 .  15) to stdout'
complete -c mpeg2desc -s o -d 'output the previous stream to FILE instead of stdout'
complete -c mpeg2desc -s s -d 'skip to first valid header -- ensures mplex can handle output'
complete -c mpeg2desc -s m -d 'output mplex offset to stdout'
complete -c mpeg2desc -s u -d 'do not output messages about unrecognized headers'

