# namei
# Autogenerated from man page /usr/share/man/man1/namei.1.gz
complete -c namei -s l -l long -d 'Use the long listing format (same as -m -o -v)'
complete -c namei -s m -l modes -d 'Show the mode bits of each file type in the style of ls(1), for example \'rwxr…'
complete -c namei -s n -l nosymlinks -d 'Don\'t follow symlinks'
complete -c namei -s o -l owners -d 'Show owner and group name of each file'
complete -c namei -s v -l vertical -d 'Vertically align the modes and owners'
complete -c namei -s x -l mountpoints -d 'Show mountpoint directories with a \'D\' rather than a \'d\''
complete -c namei -s V -l version -d 'Display version information and exit'
complete -c namei -s h -l help -d 'Display help text and exit'

