# netkit-ftp
# Autogenerated from man page /usr/share/man/man1/netkit-ftp.1.gz
complete -c netkit-ftp -s 4 -d 'Use only IPv4 to contact any host'
complete -c netkit-ftp -s 6 -d 'Use IPv6 only'
complete -c netkit-ftp -s p -d 'Use passive mode for data transfers'
complete -c netkit-ftp -s i -d 'Turns off interactive prompting during multiple file transfers'
complete -c netkit-ftp -s n -d 'Restrains netkit-ftp ftp from attempting \\*(Lqauto-login\\*(Rq upon initial co…'
complete -c netkit-ftp -s e -d 'Disables command editing and history support, if it was compiled into the net…'
complete -c netkit-ftp -s g -d 'Disables file name globbing'
complete -c netkit-ftp -s v -d 'Verbose option forces netkit-ftp ftp to show all responses from the remote se…'
complete -c netkit-ftp -s d -d 'Enables debugging'

