# pg_test_timing
# Autogenerated from man page /usr/share/man/man1/pg_test_timing.1.gz
complete -c pg_test_timing -s d -d 'Specifies the test duration, in seconds'
complete -c pg_test_timing -o 'V
.br
--version' -d 'Print the pg_test_timing version and exit'
complete -c pg_test_timing -o '?
.br
--help' -d 'Show help about pg_test_timing command line arguments, and exit'
complete -c pg_test_timing -l duration
complete -c pg_test_timing -s V
complete -c pg_test_timing -l version
complete -c pg_test_timing -s '?'
complete -c pg_test_timing -l help

