# pg_virtualenv
# Autogenerated from man page /usr/share/man/man1/pg_virtualenv.1.gz
complete -c pg_virtualenv -s a -d 'Use all PostgreSQL server versions installed'
complete -c pg_virtualenv -s v -d 'Use these versions (space-separated list)'
complete -c pg_virtualenv -s c -d 'Extra options to pass to pg_createcluster'
complete -c pg_virtualenv -s i -d 'Extra initdb options to pass to pg_createcluster'
complete -c pg_virtualenv -s o -d 'Configuration option to set in the \\f(CW\\*(C`postgresql'
complete -c pg_virtualenv -s s -d 'Launch a shell inside the virtual environment when command fails'
complete -c pg_virtualenv -s t -d 'Install clusters in a temporary directory, even when running as root'

