# postgres
# Autogenerated from man page /usr/share/man/man1/postgres.1.gz
complete -c postgres -s B -d 'Sets the number of shared buffers for use by the server processes'
complete -c postgres -s c -d 'Sets a named run-time parameter'
complete -c postgres -s C -d 'Prints the value of the named run-time parameter, and exits'
complete -c postgres -s d -d 'Sets the debug level'
complete -c postgres -s D -d 'Specifies the file system location of the database configuration files'
complete -c postgres -s e -d 'Sets the default date style to \\(lqEuropean\\(rq, that is DMY ordering of inpu…'
complete -c postgres -s F -d 'Disables fsync calls for improved performance, at the risk of data corruption…'
complete -c postgres -s h -d 'Specifies the IP host name or address on which postgres is to listen for TCP/…'
complete -c postgres -s i -d 'Allows remote clients to connect via TCP/IP (Internet domain) connections'
complete -c postgres -s k -d 'Specifies the directory of the Unix-domain socket on which postgres is to lis…'
complete -c postgres -s l -d 'Enables secure connections using SSL'
complete -c postgres -s N -d 'Sets the maximum number of client connections that this server will accept'
complete -c postgres -s o -d 'The command-line-style arguments specified in extra-options are passed to all…'
complete -c postgres -s p -d 'Specifies the TCP/IP port or local Unix domain socket file extension on which…'
complete -c postgres -s s -d 'Print time information and other statistics at the end of each command'
complete -c postgres -s S -d 'Specifies the amount of memory to be used by internal sorts and hashes before…'
complete -c postgres -o 'V
.br
--version' -d 'Print the postgres version and exit'
complete -c postgres -l name -d 'Sets a named run-time parameter; a shorter form of -c'
complete -c postgres -l describe-config -d 'This option dumps out the server\\*(Aqs internal configuration variables, desc…'
complete -c postgres -o '?
.br
--help' -d 'Show help about postgres command line arguments, and exit'
complete -c postgres -s f -d 'Forbids the use of particular scan and join methods: s and i disable sequenti…'
complete -c postgres -s n -d 'This option is for debugging problems that cause a server process to die abno…'
complete -c postgres -s O -d 'Allows the structure of system tables to be modified.  This is used by initdb'
complete -c postgres -s P -d 'Ignore system indexes when reading system tables, but still update the indexe…'
complete -c postgres -s t -d 'Print timing statistics for each query relating to each of the major system m…'
complete -c postgres -s T -d 'This option is for debugging problems that cause a server process to die abno…'
complete -c postgres -s v -d 'Specifies the version number of the frontend/backend protocol to be used for …'
complete -c postgres -s W -d 'A delay of this many seconds occurs when a new server process is started, aft…'
complete -c postgres -l single -d 'Selects the single-user mode'
complete -c postgres -s E -d 'Echo all commands to standard output before executing them'
complete -c postgres -s j -d 'Use semicolon followed by two newlines, rather than just newline, as the comm…'
complete -c postgres -s r -d 'Send all server log output to filename'
complete -c postgres -s V
complete -c postgres -l version
complete -c postgres -s '?'
complete -c postgres -l help
complete -c postgres -o fs -d and
complete -c postgres -o fn -d 'options simply discourage the optimizer from using those plan types if it has…'

