# powerline-daemon
# Autogenerated from man page /usr/share/man/man1/powerline-daemon.1.gz
complete -c powerline-daemon -l quiet -s q -d 'Without other options: do not complain about already running powerline-daemon…'
complete -c powerline-daemon -l socket -s s -d 'Specify socket which will be used for connecting to daemon'
complete -c powerline-daemon -l kill -s k -d 'Kill an already running instance'
complete -c powerline-daemon -l foreground -s f -d 'Run in the foreground (donât daemonize)'
complete -c powerline-daemon -l replace -s r -d 'Replace an already running instance'
complete -c powerline-daemon -s h -l help -d 'Display help and exit'

