# powerline
# Autogenerated from man page /usr/share/man/man1/powerline.1.gz
complete -c powerline -s r -l renderer-module -d 'Renderer module.  Usually something like . bash or '
complete -c powerline -s w -l width -d 'Maximum prompt with.  Triggers truncation of some segments'
complete -c powerline -l last-exit-code -d 'Last exit code'
complete -c powerline -l last-pipe-status -d 'Like above, but is supposed to contain space-separated array of statuses, rep…'
complete -c powerline -l jobnum -d 'Number of jobs'
complete -c powerline -s c -l config-override -d 'Configuration overrides for config. json'
complete -c powerline -s t -l theme-override -d 'Like above, but theme-specific'
complete -c powerline -s R -l renderer-arg -d 'Like above, but provides argument for renderer'
complete -c powerline -s p -l config-path -d 'Path to configuration directory'
complete -c powerline -l socket -d 'Socket address to use in daemon clients'
complete -c powerline -s h -l help -d 'Display help and exit'

