# raw
# Autogenerated from man page /usr/share/man/man8/raw.8.gz
complete -c raw -s q -l query -d 'Set query mode'
complete -c raw -s a -l all -d 'With  -q , specify that all bound raw devices should be queried'
complete -c raw -s h -l help -d 'Display help text and exit'
complete -c raw -s V -l version -d 'Display version information and exit'

