# renice
# Autogenerated from man page /usr/share/man/man1/renice.1.gz
complete -c renice -s n -l priority -d 'Specify the scheduling  priority to be used for the process, process group, o…'
complete -c renice -s g -l pgrp -d 'Interpret the succeeding arguments as process group IDs'
complete -c renice -s p -l pid -d 'Interpret the succeeding arguments as process IDs (the default)'
complete -c renice -s u -l user -d 'Interpret the succeeding arguments as usernames or UIDs'
complete -c renice -s V -l version -d 'Display version information and exit'
complete -c renice -s h -l help -d 'Display help text and exit'

