# rfcomm
# Autogenerated from man page /usr/share/man/man1/rfcomm.1.gz
complete -c rfcomm -s h -d 'Gives a list of possible commands'
complete -c rfcomm -s a -d 'Prints information about all configured RFCOMM devices'
complete -c rfcomm -s r -d 'Switch TTY into raw mode (doesn\'t work with "bind")'
complete -c rfcomm -s i -d 'The command is applied to device hciX, which must be the name or the address …'
complete -c rfcomm -s A -d 'Enable authentification'
complete -c rfcomm -s E -d 'Enable encryption'
complete -c rfcomm -s S -d 'Secure connection'
complete -c rfcomm -s M -d 'Become the master of a piconet'
complete -c rfcomm -s L -d 'Set linger timeout COMMANDS'

