# runuser
# Autogenerated from man page /usr/share/man/man1/runuser.1.gz
complete -c runuser -s c -l command -d 'Pass  command to the shell with the  -c option'
complete -c runuser -s f -l fast -d 'Pass  -f to the shell, which may or may not be useful depending on the shell'
complete -c runuser -s g -l group -d 'The primary group to be used.   This option is allowed for the root user only'
complete -c runuser -s G -l supp-group -d 'Specify a supplemental group'
complete -c runuser -s l -l login -d 'Start the shell as a login shell with an environment similar to a real login: '
complete -c runuser -s P -l pty -d 'Create pseudo-terminal for the session'
complete -c runuser -s m -s p -l preserve-environment -d 'Preserve the entire environment, i. e'
complete -c runuser -s s -l shell -d 'Run the specified shell instead of the default'
complete -c runuser -l session-command -d 'Same as  -c , but do not create a new session.   (Discouraged. )'
complete -c runuser -s w -l whitelist-environment -d 'Don\'t reset environment variables specified in comma separated list when clea…'
complete -c runuser -s V -l version -d 'Display version information and exit'
complete -c runuser -s h -l help -d 'Display help text and exit'

