# rzsh
# Autogenerated from man page /usr/share/man/man1/rzsh.1.gz
complete -c rzsh -s c -d 'Take the first argument as a command to execute, rather than reading commands…'
complete -c rzsh -s i -d 'Force shell to be interactive'
complete -c rzsh -s s -d 'Force shell to read commands from the standard input'
complete -c rzsh -s o -d '`-xo shwordsplit\' or `-xoshwordsplit\' is equivalent to `-x -o shwordsplit\''

