# scanimage
# Autogenerated from man page /usr/share/man/man1/scanimage.1.gz
complete -c scanimage -s d -l device-name -d The
complete -c scanimage -l list-devices -d 'option (see below)'
complete -c scanimage -l format -d 'format option selects how image data is written to standard output or the fil…'
complete -c scanimage -s i -d or
complete -c scanimage -l icc-profile -d 'option is used to include an ICC profile into a TIFF file'
complete -c scanimage -s L -d or
complete -c scanimage -s f -d or
complete -c scanimage -l formatted-device-list -d 'option works similar to'
complete -c scanimage -l 'batch*' -d 'options provide the features for scanning documents using document feeders'
complete -c scanimage -l batch -d '[ format ] is used to specify the format of the filename that each page will …'
complete -c scanimage -l batch-start -d 'start selects the page number to start naming files with'
complete -c scanimage -l batch-count -d 'count specifies the number of pages to attempt to scan'
complete -c scanimage -l batch-increment -d 'increment you can change the amount that the number in the filename is increm…'
complete -c scanimage -l batch-double -d 'will automatically set the increment to 2'
complete -c scanimage -l batch-prompt -d 'will ask for pressing RETURN before scanning a page'
complete -c scanimage -l accept-md5-only -d 'option only accepts user authorization requests that support MD5 security'
complete -c scanimage -s p -d or
complete -c scanimage -l progress -d 'option requests that scanimage prints a progress counter'
complete -c scanimage -s o -d or
complete -c scanimage -l output-file -d 'option requests that scanimage saves the scanning output to the given path'
complete -c scanimage -s n -d or
complete -c scanimage -l dont-scan -d 'option requests that scanimage only sets the options provided by the user but…'
complete -c scanimage -s T -d or
complete -c scanimage -l test -d 'option requests that scanimage performs a few simple sanity tests to make sur…'
complete -c scanimage -s A -d or
complete -c scanimage -l all-options -d 'option requests that scanimage lists all available options exposed the backen…'
complete -c scanimage -s h -d or
complete -c scanimage -l help -d 'options request help information'
complete -c scanimage -s v -d or
complete -c scanimage -l verbose -d 'options increase the verbosity of the operation of scanimage'
complete -c scanimage -s B -d 'option without argument changes the input buffer size from the default 32KB t…'
complete -c scanimage -l buffer-size -d 'followed by the number of KB'
complete -c scanimage -s V -d or
complete -c scanimage -l version -d 'option requests that scanimage prints the program and package name, the versi…'
complete -c scanimage -s l -d 'expects an option value in the range from 0 to 218 mm'
complete -c scanimage -l brightness -d 'expects an option value in the range from -100 to 100 percent'
complete -c scanimage -l default-enhancements -d 'has no option value'
complete -c scanimage -l mode -d 'accepts an argument that must be one of the strings Lineart , Gray , or Color '
complete -c scanimage -l custom-gamma -d 'expects either no option value, a "yes" string, or a "no" string'
complete -c scanimage -l gamma-table -d 'expects zero or more values in the range 0 to 255'

