# script
# Autogenerated from man page /usr/share/man/man1/script.1.gz
complete -c script -s a -l append -d 'Append the output to  file or to  typescript , retaining the prior contents'
complete -c script -s c -l command -d 'Run the  command rather than an interactive shell'
complete -c script -s e -l return -d 'Return the exit code of the child process'
complete -c script -s f -l flush -d 'Flush output after each write'
complete -c script -l force -d 'Allow the default output destination, i. e'
complete -c script -s o -l output-limit -d 'Limit the size of the typescript and timing files to  size and stop the child…'
complete -c script -s q -l quiet -d 'Be quiet (do not write start and done messages to standard output)'
complete -c script -s t -l timing -d 'Output timing data to standard error, or to  file when given'
complete -c script -s V -l version -d 'Display version information and exit'
complete -c script -s h -l help -d 'Display help text and exit'

