# scriptreplay
# Autogenerated from man page /usr/share/man/man1/scriptreplay.1.gz
complete -c scriptreplay -s t -l timing -d 'File containing script\'s timing output'
complete -c scriptreplay -s s -l typescript -d 'File containing script\'s terminal output'
complete -c scriptreplay -s d -l divisor -d 'Speed up the replay displaying this  number of times'
complete -c scriptreplay -s m -l maxdelay -d 'Set the maximum delay between transcript updates to  number of seconds'
complete -c scriptreplay -s V -l version -d 'Display version information and exit'
complete -c scriptreplay -s h -l help -d 'Display help text and exit.  EXAMPLE'

