# setpriv
# Autogenerated from man page /usr/share/man/man1/setpriv.1.gz
complete -c setpriv -l clear-groups -d 'Clear supplementary groups'
complete -c setpriv -s d -l dump -d 'Dump current privilege state'
complete -c setpriv -l groups -d 'Set supplementary groups'
complete -c setpriv -l inh-caps -l ambient-caps -l bounding-set -d 'Set the inheritable capabilities, ambient capabilities or the capability boun…'
complete -c setpriv -o all -d 'can be used to add or remove all caps'
complete -c setpriv -l keep-groups -d 'Preserve supplementary groups.   Only useful in conjunction with'
complete -c setpriv -l rgid
complete -c setpriv -l egid
complete -c setpriv -l regid
complete -c setpriv -l init-groups -d 'Initialize supplementary groups using initgroups (3)'
complete -c setpriv -l ruid -d or
complete -c setpriv -l reuid
complete -c setpriv -l list-caps -d 'List all known capabilities.   This option must be specified alone'
complete -c setpriv -l no-new-privs -d 'Set the no_new_privs bit'
complete -c setpriv -l euid -d 'Set the real, effective, or both UIDs'
complete -c setpriv -l securebits -d 'Set or clear securebits.   The argument is a comma-separated list'
complete -c setpriv -l pdeathsig -d 'Keep, clear or set the parent death signal'
complete -c setpriv -l selinux-label -d 'Request a particular SELinux transition (using a transition on exec, not dynt…'
complete -c setpriv -l apparmor-profile -d 'Request a particular AppArmor profile (using a transition on exec)'
complete -c setpriv -l reset-env -d 'Clears all the environment variables except TERM; initializes the environment…'
complete -c setpriv -s V -l version -d 'Display version information and exit'
complete -c setpriv -s h -l help -d 'Display help text and exit'
complete -c setpriv -s g -d 'option), try something like:'

