# setvtrgb
# Autogenerated from man page /usr/share/man/man8/setvtrgb.8.gz
complete -c setvtrgb -s h -d 'Prints usage message and exits'
complete -c setvtrgb -s V -d 'Prints version number and exists'

