# sl
# Autogenerated from man page /usr/share/man/man6/sl.6.gz
complete -c sl -s a -d 'An accident seems to happen.  You\'ll feel pity for people who cry for help'
complete -c sl -s l -d 'shows little one'
complete -c sl -s F -d 'It flies'
complete -c sl -s e -d 'Allow interrupt by Ctrl+C'

