# spumux
# Autogenerated from man page /usr/share/man/man1/spumux.1.gz
complete -c spumux -s m -d 'Sets the encoding for the subtitles.   Can be dvd, cvd, or svcd'
complete -c spumux -s s -d 'Sets the subtitle stream id.   Default is 0'
complete -c spumux -s v -d 'Sets the verbosity level'
complete -c spumux -s P -d 'Enables a progress bar'
complete -c spumux -l nomux -d 'Disables reading of an MPEG stream from standard input'
complete -c spumux -l nodvdauthor-data -d 'Disables passing of color and button info to dvdauthor'

