# symcryptrun
# Autogenerated from man page /usr/share/man/man1/symcryptrun.1.gz
complete -c symcryptrun -s v -d 'TQ   --verbose Output additional information while running'
complete -c symcryptrun -l verbose -d 'Output additional information while running'
complete -c symcryptrun -s q
complete -c symcryptrun -l quiet -d 'Try to be as quiet as possible'
complete -c symcryptrun -l homedir -d 'Set the name of the home directory to dir'
complete -c symcryptrun -l log-file -d 'Append all logging output to file.   Use `socket://\' to log to socket'

