# systemd-socket-proxyd
# Autogenerated from man page /usr/share/man/man8/systemd-socket-proxyd.8.gz
complete -c systemd-socket-proxyd -s h -l help -d 'Print a short help text and exit'
complete -c systemd-socket-proxyd -l version -d 'Print a short version string and exit'
complete -c systemd-socket-proxyd -l connections-max -s c -d 'Sets the maximum number of simultaneous connections, defaults to 256'

