# systemd-resolve
# Autogenerated from man page /usr/share/man/man1/systemd-resolve.1.gz
complete -c systemd-resolve -s 4 -s 6 -d 'By default, when resolving a hostname, both IPv4 and IPv6 addresses are acqui…'
complete -c systemd-resolve -s i -l interface -d 'Specifies the network interface to execute the query on'
complete -c systemd-resolve -s p -l protocol -d 'Specifies the network protocol for the query.  May be one of "dns" (i. e'
complete -c systemd-resolve -s t -l type -s c -l class -d 'Specifies the DNS resource record type (e. g.  A, AAAA, MX, . ) and class (e'
complete -c systemd-resolve -l service-address -d 'Takes a boolean parameter'
complete -c systemd-resolve -l service-txt -d 'Takes a boolean parameter'
complete -c systemd-resolve -l cname -d 'Takes a boolean parameter'
complete -c systemd-resolve -l search -d 'Takes a boolean parameter'
complete -c systemd-resolve -l raw -d 'Dump the answer as binary data'
complete -c systemd-resolve -l legend -d 'Takes a boolean parameter'
complete -c systemd-resolve -s h -l help -d 'Print a short help text and exit'
complete -c systemd-resolve -l version -d 'Print a short version string and exit'
complete -c systemd-resolve -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-resolve -l service -d 'the hostnames contained in the SRV resource records are resolved as well'
complete -c systemd-resolve -s a
complete -c systemd-resolve -s d
complete -c systemd-resolve -s f
complete -c systemd-resolve -s x
complete -c systemd-resolve -s m
complete -c systemd-resolve -s u -s I -s l -s R -s r -s v -s V -l enable-updates -l disable-updates -l are-updates-enabled

