# taskset
# Autogenerated from man page /usr/share/man/man1/taskset.1.gz
complete -c taskset -s a -l all-tasks -d 'Set or retrieve the CPU affinity of all the tasks (threads) for a given PID'
complete -c taskset -s c -l cpu-list -d 'Interpret mask as numerical list of processors instead of a bitmask'
complete -c taskset -s p -l pid -d 'Operate on an existing PID and do not launch a new task'
complete -c taskset -s V -l version -d 'Display version information and exit'
complete -c taskset -l cpu-list0-2 -d 'is processors #0, #1, #2, and #6'
complete -c taskset -s h -l help -d 'Display help text and exit.  USAGE'

