# tldr-hs
# Autogenerated from man page /usr/share/man/man1/tldr-hs.1.gz
complete -c tldr-hs -s h -l help -d 'Show this help text'
complete -c tldr-hs -s v -l version -d 'Show version'
complete -c tldr-hs -l update -d 'Update tldr pages'

