# tldr
# Autogenerated from man page /usr/share/man/man1/tldr.1.gz
complete -c tldr -s h -l help -d 'Show this help text'
complete -c tldr -s v -l version -d 'Show version'
complete -c tldr -l update -d 'Update tldr pages'

