# tracker-export
# Autogenerated from man page /usr/share/man/man1/tracker-export.1.gz
complete -c tracker-export -s g -l show-graphs -d 'This flag causes the relevant GRAPH statements to be output along with the da…'
complete -c tracker-export -s t -l type -d 'Used for exporting a specific type of user data from a Tracker database'

