# usb-creator-gtk
# Autogenerated from man page /usr/share/man/man8/usb-creator-gtk.8.gz
complete -c usb-creator-gtk -s i -l iso -d 'Provide a source image to pre\\(hy populate the UI'
complete -c usb-creator-gtk -s h -l help -d 'Print a summary of command line options and exit'
complete -c usb-creator-gtk -l version -d 'Print the current version and exit'

