# vcdxminfo
# Autogenerated from man page /usr/share/man/man1/vcdxminfo.1.gz
complete -c vcdxminfo -s i -l generic-info -d 'show generic information'
complete -c vcdxminfo -s a -l dump-aps -d 'dump APS data'
complete -c vcdxminfo -l relaxed-aps -d 'relax APS constraints'
complete -c vcdxminfo -s o -l output-file -d 'file for XML output'
complete -c vcdxminfo -s p -l progress -d 'show progress'
complete -c vcdxminfo -s v -l verbose -d 'be verbose'
complete -c vcdxminfo -s q -l quiet -d 'show only critical messages'
complete -c vcdxminfo -l gui -d 'enable GUI mode'
complete -c vcdxminfo -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c vcdxminfo -s '?' -l help -d 'Show this help message'
complete -c vcdxminfo -l usage -d 'Display brief usage message AUTHOR Written by Herbert Valerio Riedel and Rock…'

