# wdctl
# Autogenerated from man page /usr/share/man/man8/wdctl.8.gz
complete -c wdctl -s f -l flags -d 'Print only the specified flags'
complete -c wdctl -s F -l noflags -d 'Do not print information about flags'
complete -c wdctl -s I -l noident -d 'Do not print watchdog identity information'
complete -c wdctl -s n -l noheadings -d 'Do not print a header line for flags table'
complete -c wdctl -s o -l output -d 'Define the output columns to use in table of watchdog flags'
complete -c wdctl -s O -l oneline -d 'Print all wanted information on one line in key="value" output format'
complete -c wdctl -s r -l raw -d 'Use the raw output format'
complete -c wdctl -s s -o settimeout -d 'Set the watchdog timeout in seconds'
complete -c wdctl -s T -l notimeouts -d 'Do not print watchdog timeouts'
complete -c wdctl -s x -l flags-only -d 'Same as -I -T'
complete -c wdctl -s V -l version -d 'Display version information and exit'
complete -c wdctl -l help -d 'to get list of all supported columns'
complete -c wdctl -s h -d 'Display help text and exit.  AUTHORS'

