# whereis
# Autogenerated from man page /usr/share/man/man1/whereis.1.gz
complete -c whereis -s b -d 'Search for binaries'
complete -c whereis -s m -d 'Search for manuals'
complete -c whereis -s s -d 'Search for sources'
complete -c whereis -s u -d 'Only show the command names that have unusual entries'
complete -c whereis -s B -d 'Limit the places where  whereis searches for binaries, by a whitespace-separa…'
complete -c whereis -s M -d 'Limit the places where  whereis searches for manuals and documentation in Inf…'
complete -c whereis -s S -d 'Limit the places where  whereis searches for sources, by a whitespace-separat…'
complete -c whereis -s f -d 'Terminates the directory list and signals the start of filenames'
complete -c whereis -s l -d 'Output the list of effective lookup paths that  whereis is using'
complete -c whereis -s h -l help -d 'Display help text and exit'
complete -c whereis -s V -l version -d 'Display version information and exit'

