# x86_64-linux-gnu-ar
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-ar.1.gz
complete -c x86_64-linux-gnu-ar -l help -d 'Displays the list of command-line options supported by ar and then exits'
complete -c x86_64-linux-gnu-ar -l version -d 'Displays the version information of ar and then exits'
complete -c x86_64-linux-gnu-ar -o X32_64 -d 'ar ignores an initial option spelled -X32_64, for compatibility with \\s-1AIX'
complete -c x86_64-linux-gnu-ar -l plugin -d 'The optional command-line switch --plugin name causes ar to load the plugin c…'
complete -c x86_64-linux-gnu-ar -l target -d 'The optional command-line switch --target bfdname specifies that the archive …'
complete -c x86_64-linux-gnu-ar -l output -d 'The --output option can be used to specify a path to a directory into which a…'

